sickbeard/tv.py
If we want to re-download the same quality, set as WANTED.
As mentioned in here: https://github.com/SiCKRAGETV/sickrage-issues/issues/206
=> Don't re-download same quality if we do MANUAL SEARCH

sickbeard/webserve.py
As mentioned in here:
https://github.com/SiCKRAGETV/sickrage-issues/issues/243
=> Backup/restore: include cache directory

gui/slick/css/dark.css, gui/slick/css/light.css, gui/slick/css/style.css, gui/slick/interfaces/default/home.tmpl
Added a different shade of green for when and only when the show is 100% downloaded
=> Implementation for sickragetv/sickrage-issues#322 - Add extra progress-bar color for when show is fully downloaded

sickbeard/webserve.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/315
=> Auto send user and password when open managetorrents page

gui/slick/interfaces/default/config_general.tmpl, sickbeard/__init__.py, sickbeard/logger.py, sickbeard/webserve.py
Made logging configurable through settings - general page. Changing the
logging requires a restart (since the logger is initialized on startup).
=> Made logging configurable

gui/slick/interfaces/default/config_notifications.tmpl, gui/slick/js/configNotifications.js, sickbeard/webserve.py
Adds missing code for saving per show email notifications
=> fix for SiCKRAGETV/sickrage-issues#347

gui/slick/interfaces/default/inc_rootDirs.tmpl
https://github.com/SiCKRAGETV/sickrage-issues/issues/286
=> Fix issue showing 'unknown dir' when adding shows

sickbeard/helpers.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/297
=> use os.system for file copies on posix systems

gui/slick/js/configSubtitles.js, gui/slick/js/newShow.js, gui/slick/js/recommendedShows.js
Subtiles, newshow and recommandedshows
See SiCKRAGETV/sickrage-issues#421 for bug report.
=> Fix jQuery live not working with 1.9+:

gui/slick/interfaces/default/config_notifications.tmpl, sickbeard/__init__.py, sickbeard/notifiers/plex.py, sickbeard/webserve.py
This because PMS does not allow connections without token when using Plex Home
=> Added support for Plex Media Center updates with Auth Token.

gui/slick/interfaces/default/editShow.tmpl, sickbeard/search.py
See SiCKRAGETV/sickrage-issues#418 for bug report.
=> Patch jquery bwlists

gui/slick/interfaces/default/config_general.tmpl, gui/slick/interfaces/default/displayShow.tmpl, sickbeard/__init__.py, sickbeard/webserve.py
Added config option download_url
Added field to configure download_url in general --> interface
Added link to download episodes in the displayShow template, using download_url
See #1185 for discussions.
=> Adding a download field for the episodes

sickbeard/tv.py
SiCKRAGETV/sickrage-issues#281
=> Fix low quality snatched episode don't appear at backlog

sickbeard/webapi.py
It would be very useful to get IMDB_ID together with `tvdbid` and `tvrage_id`
=> Feature: Add IMDB ID to show webapi

sickbeard/webserve.py
See SiCKRAGETV/sickrage-issues/issues/111 for more info
=> Fix default episode status in display and edit show.

gui/slick/js/displayShow.js
See SiCKRAGETV/sickrage-issues#436 for more info
=> Fix Safari next show button not working.

sickbeard/tv.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/428
=> Re-download episode when manualsearch and quality is Unknown

sickbeard/properFinder.py, sickbeard/search.py
See SiCKRAGETV/sickrage-issues#328 for more info.
Fix:
AttributeError: 'NoneType' object has no attribute 'rls_ignore_words'
AttributeError: object has no attribute 'resultType'
=> Fix no attribute while search for proper.

gui/slick/interfaces/default/displayShow.tmpl
Comments here
https://github.com/SiCKRAGETV/SickRage/pull/1186
=> Fix issue when location is empty and there's no len()

gui/slick/interfaces/default/testRename.tmpl, gui/slick/js/testRename.js
- Added "Select All" check box under new "All Seasons" table
- Duplicated "Rename Selected" and "Cancel Rename" buttons to be
available underneath the "Select All" checkbox.
=> Added Select All Checkbox to Preview Rename page

sickbeard/tv.py
See SiCKRAGETV/sickrage-issues#453
=> Fix absolute numbering used in notification.

sickbeard/helpers.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/51#issuecomment-68071144 for more info.
=> Fix 'Sort with "The", "A", "An"' on dropdown in displayShow not working.

sickbeard/providers/iptorrents.py
Updated iptorrents URL to preferred, block-advoiding iptorrents.eu
=> Updated iptorrents URL

sickbeard/metadata/mede8er.py
- Added plot info to mede8er series.xml metadata file.
=> Add plot info to mede8er series.xml

sickbeard/helpers.py
See SiCKRAGETV/sickrage-issues#485 for more info.
=> Fix moving files across partition

sickbeard/webapi.py
See SiCKRAGETV/sickrage-issues#488 for more info.
=> Remove an extra apostrophe from content-type.

sickbeard/helpers.py
Ignore partially synced files from BTSync 2.0 Alpha
=> Ignore partially synced files from BTSync 2.0 Alpha

tornado/iostream.py
SiCKRAGETV/sickrage-issues#258
related to: SiCKRAGETV/sickrage-issues#471
=> Try to fix issue #258

sickbeard/webserve.py
E.g.: Couchpotato
See SiCKRAGETV/sickrage-issues#214 and SiCKRAGETV/sickrage-issues#331 for more info
=> Change cookie name to prevent name collision.

sickbeard/providers/torrentday.py
Updated torrentday URL to preferred, block-avoiding torrentday.eu
=> Updated torrentday URL

sickbeard/webserve.py
Example: Rage of Bahamut: Genesis
Link: http://thetvdb.com/?tab=series&id=284133
See SiCKRAGETV/sickrage-issues#468 for bug report
=> Fix if network is None

sickbeard/logger.py
See SiCKRAGETV/sickrage-issues#287 for more info
=> Fix GitHub submit error

gui/slick/interfaces/default/displayShow.tmpl
As discussed here:
https://github.com/SiCKRAGETV/sickrage-issues/issues/457
=> Improve code check for list comprehensions

.gitignore
Added IntelliJ IDEA specific files to gitignore.
=> Added IntelliJ IDEA specific gitignores

sickbeard/providers/iptorrents.py
Ref bad pull: SiCKRAGETV/SickRage#1208
=> Fix IPTorrents url.

lib/tvdb_api/tvdb_api.py, lib/tvrage_api/tvrage_api.py
TVRage: Check if node episodelist exist in tvrage show.
TVdb: Check if node episode exist in tvdb show
e.g. New show without episodes
=> TVRage, TVdb: Check if show has episodes

sickbeard/dailysearcher.py
See SiCKRAGETV/sickrage-issues#534 for more info
=> Fix incorrect operator in dailysearcher.py

gui/slick/interfaces/default/config_search.tmpl, gui/slick/js/configSearch.js
See SiCKRAGETV/sickrage-issues#336 for more info.
=> Added default host:port for each torrent clients.

gui/slick/interfaces/default/manage_backlogOverview.tmpl, sickbeard/tv.py
See SiCKRAGETV/sickrage-issues#521 for more info
=> Fix unknown quality

gui/slick/interfaces/default/displayShow.tmpl
Introduce in commit 9c635f81ff484a2774f93ea0ea1073fc7b512f5d
=> Fix typo in displayShow.tmpl

sickbeard/providers/torrentbytes.py
Fixes SiCKRAGETV/sickrage-issues#604.
=> Updated login param value for torrentBytes provider

gui/slick/interfaces/default/inc_rootDirs.tmpl
Fix first path always selected ignoring default in add new show.
See https://github.com/SiCKRAGETV/sickrage-issues/issues/606 for more info
=> Revert commit 32da0199f2690b8b04349ebd495c6a7ad5a2b2f4

.gitignore
- Removes Eclipse Project .settings folder from git tracking
=> Added .settings folder to .gitignore

gui/slick/interfaces/default/displayShow.tmpl, gui/slick/interfaces/default/history.tmpl, gui/slick/js/ajaxEpSubtitles.js, sickbeard/tv.py
When multiSubtitles is not activated:
-Download history show flag of the last 2 chars before ext.
-Subtitle lang was always und.
-Keep lang value between refresh
=>  Fix subtitles display issues.

sickbeard/helpers.py, sickbeard/providers/nyaatorrents.py, sickbeard/show_name_helpers.py
In use in nyaatorrents.py:
E.g.: Kuroko's Basketball
=> Modified sanitizeSceneName() for anime exception.

gui/slick/interfaces/default/displayShow.tmpl
Fix if in wrong position in displayShow.tmpl
=> Fix if in wrong position

gui/slick/js/newShow.js
https://github.com/SiCKRAGETV/sickrage-issues/issues/312#issuecomment-74519161
=> Fixes shows with double quotes

sickbeard/name_parser/regexes.py
Reverts SiCKRAGETV/SickRage#1296 because of issue https://github.com/SiCKRAGETV/sickrage-issues/issues/621
=> Revert "Added new regex 'itunes'"

lib/trakt/trakt.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/616 for more info
=> Trakt: Catch all requests exceptions

gui/slick/js/ajaxEpSearch.js, sickbeard/webserve.py
Changed function getManualSearchStatus to include overview.
Changed all attr to prop
=> Fix color in displayShow when manually searching.

gui/slick/css/lib/bootstrap.css
Re-applied commit f2bcc72 because commit 0da960f erased it
```
From f2bcc7217c391ea823f0e0ed99ababaef4b3622d Thu, 19 Feb 2015 01:49:30-0500
From: markheloking <markheloking@live.nl>
Date: Mon, 8 Dec 2014 15:14:52 +0100
Subject: [PATCH] Fixed bootstrap @grid-float-breakpoint
http://getbootstrap.com/components/
Look in that page for: "Changing the collapsed mobile navbar breakpoint"
Fixed collapse fixed width from 768px to the width of our current
navbar: 1010px
```
=> Fix navbar not collapsing properly

SickBeard.py, sickbeard/__init__.py, sickbeard/helpers.py
=> Fix backup issue with invalid restore folder

gui/slick/css/light.css
https://github.com/SiCKRAGETV/sickrage-issues/issues/617
=> Remove blue color from 100% progress bar

sickbeard/helpers.py, sickbeard/webserve.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/624 for more info
=> AniDB: Fix generating exception on timeout in PP

sickbeard/traktChecker.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/669
=> Trakt remove traceback

sickbeard/providers/oldpiratebay.py
Updated the oldpiratebay provider to get finding season qualities to work, fixing season pack searching.
=> OPB: Fixed season pack searching

sickbeard/tv.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/653
=> Opensubtitle - show only error message not traceback

sickbeard/notifiers/kodi.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/658
=> Possible fix for kodi notify

sickbeard/helpers.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/122
=> Remove trademark from filename

gui/slick/js/ajaxEpSearch.js, sickbeard/webserve.py
Reverts SiCKRAGETV/SickRage#1350
=> Revert "Fix color in displayShow when manually searching."

sickbeard/providers/scc.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/715 for more info
=> Provider SCC: Catch exception on getURL

sickbeard/name_parser/regexes.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/482 for more info
=> Added a specific regex for horriblesubs

sickbeard/providers/t411.py
Reverts SiCKRAGETV/SickRage#1376 to create hotfixe for master
=> Revert "Update T411 to its new domain name"

sickbeard/providers/freshontv.py
If search results are more than 1 page, it now iterates through each page. Also improved login.
Relates to issue https://github.com/SiCKRAGETV/sickrage-issues/issues/632
=> Handles multi-page results and improved login

gui/slick/interfaces/default/viewlogs.tmpl, sickbeard/webserve.py
@abeloin feel free to change anything
=> New Feature - Log search and log filter by SR thread

lib/cachecontrol/__init__.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/748 for more info.
=> Add a missing urllib3.disbale_warning()

lib/subliminal/api.py, lib/subliminal/async.py, lib/subliminal/cache.py, lib/subliminal/core.py, lib/subliminal/language.py, lib/subliminal/services/__init__.py, lib/subliminal/services/addic7ed.py, lib/subliminal/services/bierdopje.py, lib/subliminal/services/itasa.py, lib/subliminal/services/opensubtitles.py, lib/subliminal/services/podnapisi.py, lib/subliminal/services/podnapisiweb.py, lib/subliminal/services/subscenter.py, lib/subliminal/services/subswiki.py, lib/subliminal/services/subtitulos.py, lib/subliminal/services/thesubdb.py, lib/subliminal/services/tvsubtitles.py, lib/subliminal/services/usub.py, lib/subliminal/videos.py
Due to issue converting some character to Windows cp1252 failing, suppress log line from being created on Windows.
=> Subtitles 3/3: Suppressing subliminal logs on windows

gui/slick/js/ajaxEpSearch.js, sickbeard/webserve.py
Changed function getManualSearchStatus to include overview.
Changed all attr to prop
=> Fix color in displayShow when manually searching. v2

sickbeard/providers/btn.py
BTN: If the user didn't ask for season pack don't search via Season.
See https://github.com/SiCKRAGETV/sickrage-issues/issues/767 for more info
=> BTN: Fix searching in season mode for episode

sickbeard/scene_numbering.py
See issue https://github.com/SiCKRAGETV/sickrage-issues/issues/777 for more info
=> Fix changing episode scene number not updating the show's episode cache.

sickbeard/notifiers/emailnotify.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/766 for more info.
=> smtp: Added missing date field in email body

lib/subliminal/language.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/778 for more info
=> Subliminal: Fix ogg subtitles track with und language

sickbeard/providers/rarbg.py
Search SD and HD separately;
Get up to 5 pages of results if needed
=> Enhance RARBG

sickbeard/webserve.py
Possible fix for Fix TypeError: object of type 'NoneType' has no len()
See https://github.com/SiCKRAGETV/sickrage-issues/issues/231 and https://github.com/SiCKRAGETV/sickrage-issues/issues/764
=> Possible fix for Fix TypeError: object of type 'NoneType' has no len()

gui/slick/js/restart.js
Fix timeout on get error.
Fix restart wrong url behind proxy.
Added console.log debug via setting console_debug to true.
See https://github.com/SiCKRAGETV/sickrage-issues/issues/609 for more info
=> Restart: Fix timeout on get error

sickbeard/tv.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/762 for more info
=> Change File Date: Fix set date/time to local tz when local is chosen

sickbeard/webserve.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/779 for more info
=> Don't use sickbeard.SYS_ENCODING for Cheetah's Filter

sickbeard/webserve.py
Reverts SiCKRAGETV/SickRage#1436
=> Revert "Don't use sickbeard.SYS_ENCODING for Cheetah's Filter"

sickbeard/__init__.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/805 for more info
=> Add a warning when gh object is set to None

sickbeard/webserve.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/779 for more info.
See https://github.com/SiCKRAGETV/sickrage-issues/issues/796 for more info.
=> Check for UnicodeDecodeError in Cheetah's Filter

gui/slick/js/restart.js
Use setInterval instead of setTimout
=> Redone restart.js

sickbeard/sbdatetime.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/813 for more info
=> Fix missing en_US not working in certain linux system.

sickbeard/clients/generic.py
Show only error message. Not traceback
https://github.com/SiCKRAGETV/sickrage-issues/issues/830
https://github.com/SiCKRAGETV/sickrage-issues/issues/596
https://github.com/SiCKRAGETV/sickrage-issues/issues/251
=> Remove traceback from generic.py

lib/unrar2/rar_exceptions.py, lib/unrar2/unix.py, sickbeard/processTV.py
Improve why rar archive failed
=> Fix pyUnrar2 on bad archive

.gitignore, sickbeard/webserve.py
Keep the latest backup only.
Saved in DATA_DIR/backup
=> Added backup when updating

gui/slick/js/config.js, sickbeard/webserve.py
Added log messages to DEBUG comparisson
TODO:
- Compare DB when auto-updating
- Compare DB when manual-updating
@abeloin
=> Compare remote DB versions with local before update

gui/slick/interfaces/default/config_providers.tmpl, gui/slick/js/config.js, gui/slick/js/configProviders.js
Fix configProviders refresh
See https://github.com/SiCKRAGETV/sickrage-issues/issues/503 for more info.
=> Fix add newznab provider.

sickbeard/notifiers/emailnotify.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/790 for more info
=> Email notifiy: Fix msg created witout MIMEext

sickbeard/webserve.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/815 for more info
=> Trakt: Catch error when trying to delete library.

sickbeard/providers/scc.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/718 for more info.
=> SCC: Fix season search only in sponly

sickbeard/providers/iptorrents.py, sickbeard/search.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/718 for more info.
=> IPT: force eponly search since as it isn't supported by the provider.

gui/slick/interfaces/default/config_notifications.tmpl, sickbeard/__init__.py, sickbeard/helpers.py, sickbeard/notifiers/trakt.py, sickbeard/postProcessor.py, sickbeard/search.py, sickbeard/show_queue.py, sickbeard/traktChecker.py, sickbeard/tv.py, sickbeard/webserve.py
This pull request is intended to take in sync sickrage with wathclist.
It adds Show to watch list when added to sickrage and remove from watchlist when deleted.
It add Episode to watchlist when the episode is set to wanted or snetched on sickrage and will be removed from watchlist when the episode will be downloaded.
=> Sync wathclist

SickBeard.py, lib/shutil_custom/__init__.py, setup.py, sickbeard/__init__.py, sickbeard/helpers.py, sickbeard/processTV.py, sickbeard/tv.py, sickbeard/versionChecker.py, tests/test_lib.py, updater.py
Replace shutil.copyfile for a faster copy/move. Replace PR https://github.com/SiCKRAGETV/SickRage/pull/1193 and https://github.com/SiCKRAGETV/SickRage/pull/1262.
See https://github.com/SiCKRAGETV/sickrage-issues/issues/545 for more info.
=> Monkeypatch shutil.copyfile

lib/shutil_custom/__init__.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/844 for more info
=> Shutil: Fix compatibility with Python 2.6

gui/slick/interfaces/default/config_general.tmpl, gui/slick/interfaces/default/inc_top.tmpl, sickbeard/webserve.py
=> Fix submit issue.

sickbeard/notifiers/trakt.py, sickbeard/postProcessor.py
=> Added TRAKT_REMOVE_WATCHLIST Function as was before

sickbeard/webserve.py
- Changed the viewlog to read the log from all the logfiles in order if
the number of lines is < maxLines.
- Viewlog will now only count log entries that are significant for your
search entry or filter setting.
=> Change viewLog to use rolled over logfiles

sickbeard/postProcessor.py
- Changed setting base_name to use the old way when subfolders is not
true.
=> Change list_associated_files

sickbeard/notifiers/trakt.py, sickbeard/postProcessor.py, sickbeard/search.py, sickbeard/traktChecker.py, sickbeard/webserve.py
This PR manage alignment beetween sickrage and traktv if for any reason event sent to traktv has been lost.
=> Sync Watchlist for event that has been lost for traktv site problem

gui/slick/interfaces/default/config_general.tmpl
Reverts SiCKRAGETV/SickRage#1471
=> Revert "Change DIV message when list branches is empty, "

gui/slick/interfaces/default/config_general.tmpl, gui/slick/interfaces/default/inc_top.tmpl, sickbeard/__init__.py
=> Fix list branches

gui/slick/interfaces/default/config_providers.tmpl, gui/slick/js/configProviders.js
Added default element in text field
=> Fix RSS search element name

sickbeard/processTV.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/858
=> Fix brackets in UNRAR log message

sickbeard/__init__.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/860
@neoatomic
=> Fix git password not encrypted

gui/slick/interfaces/default/home.tmpl
https://github.com/SiCKRAGETV/sickrage-issues/issues/840
=> Workaround for invalid date(eg 2915)

gui/slick/js/configProviders.js
See https://github.com/SiCKRAGETV/sickrage-issues/issues/855 for more info
=> Fix unable to add torrent rss when nzb search is disable

lib/shutil_custom/__init__.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/859 for more info
=> Shutil: Catch error in finally when files don't exists

sickbeard/traktChecker.py
=> sync watchlist fix

gui/slick/interfaces/default/config_general.tmpl
https://github.com/SiCKRAGETV/sickrage-issues/issues/877
=> Check if $gh_branch is None

gui/slick/interfaces/default/manage_backlogOverview.tmpl
Reverted: Added snatched status in backlog overview.
=> Revert commit 76c8643a6e8c6d0aae6272b2539191916b5c0067

gui/slick/interfaces/default/comingEpisodes.tmpl
OverflowError: mktime argument out of range
https://github.com/SiCKRAGETV/sickrage-issues/issues/883
=> Try to fix invalid date in coming episodes

lib/feedcache/cache.py, sickbeard/rssfeeds.py, sickbeard/tvcache.py
=> Added use of global proxy in tvcache.py/getRSSFeed

sickbeard/providers/rarbg.py
=> rarbg: switch to request library

sickbeard/autoPostProcesser.py, sickbeard/showUpdater.py, sickbeard/versionChecker.py, sickbeard/webserve.py
- Added amActive to showUpdateScheduler and autopostprocessor
thanks ! @abeloin
=> Abort update if remote has new DB version or PP is running or showupdating

sickbeard/metadata/mede8er.py
- Changed mede8er myEp['rating'] assignment.
(hotfix)
=> Fix mede8er rating info

sickbeard/processTV.py
- Show Syncfiles with warning about skipping PP (helps finding files)
=> Show Syncfiles in log when Postpone PP halts because of them

sickbeard/logger.py
@abeloin should we consider NAS/FreeNAS/etc too ?
http://stackoverflow.com/questions/842059/is-there-a-portable-way-to-get-the-current-username-in-python
=> Send user locale when submitting issues

sickbeard/tv.py
@TagForce Complementing https://github.com/SiCKRAGETV/SickRage/pull/1504
=> Don't show paused shows in backlog overview

sickbeard/providers/torrentday.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/909
=> Update torrentday url

sickbeard/show_queue.py
and add more info to log message
https://github.com/SiCKRAGETV/sickrage-issues/issues/370
@TagForce
=> Remove traceback from showupdater

sickbeard/autoPostProcesser.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/821
=> Set amActive to False when return

gui/slick/interfaces/default/errorlogs.tmpl, gui/slick/interfaces/default/viewlogs.tmpl
See https://github.com/SiCKRAGETV/sickrage-issues/issues/923 for more info
=> Added WebSafe filter to log viewer.

sickbeard/versionChecker.py, sickbeard/webserve.py
Proof:
```
2015-03-11 15:40:28 INFO     CHECKVERSION :: New update found for SickRage, starting auto-updater ...
2015-03-11 15:40:30 DEBUG    CHECKVERSION :: We can proceed with the update. New update has same DB version
2015-03-11 15:40:30 DEBUG    CHECKVERSION :: We can proceed with the update. Post-Processor is not running
2015-03-11 15:40:30 DEBUG    CHECKVERSION :: We can proceed with the update. Shows are not being updated
2015-03-11 15:40:30 DEBUG    CHECKVERSION :: Proceeding with auto update
2015-03-11 15:40:30 INFO     CHECKVERSION :: Config backup in progress...
2015-03-11 15:41:34 INFO     CHECKVERSION :: Config backup successful, updating...
2015-03-11 15:41:34 DEBUG    CHECKVERSION :: Executing git symbolic-ref -q HEAD with your shell in /home/pi/SickRage
2015-03-11 15:41:35 …
```
=> Backup when auto updating

lib/subliminal/videos.py
https://github.com/SiCKRAGETV/SickRage/commit/35c1761a0159f96fc6667b595a3199c2e0d5d8d6#diff-db9c820dc4f3b1e2f85a07c95e5b8434
=> Subliminal: reverted commit for path in unicode

SickBeard.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/821
=> Disable daemon mode in MAC

sickbeard/name_parser/regexes.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/891 for more info
=> Added Kaerizaki-Fansub regex

gui/slick/interfaces/default/config_search.tmpl, gui/slick/js/configSearch.js
rTorrent: Hide user/pass/auth when using scgi://
uTorrent: Change seed time label
Transmission: Change seed time label for inactive time
See https://github.com/SiCKRAGETV/sickrage-issues/issues/936 for more info.
See https://github.com/SiCKRAGETV/sickrage-issues/issues/911 for more info.
=> Fix various providers issue in webui

sickbeard/helpers.py, sickbeard/providers/t411.py
Using T411 provider, when trying to connect too many times with wrong password, a captcha can be requested. This captcha is really simple and can be solved by the provider.
This implements the captcha resolution if requested at login time.
Tested OK when my account was locked because of this captcha, it solved the captcha properly and authentication to the tracker is now working.
=> T411 login captcha

gui/slick/interfaces/default/config_postProcessing.tmpl
https://github.com/SiCKRAGETV/sickrage-issues/issues/934
@TagForce
=> Add Note to Post Processing config

gui/slick/interfaces/default/config.tmpl
https://github.com/SiCKRAGETV/sickrage-issues/issues/952
=> Disable legacy import in config.tmpl

sickbeard/webserve.py
- Solves Already Processed when downloading the same release.
https://github.com/SiCKRAGETV/sickrage-issues/issues/770
Basic tests done.
=> Set release_name to "" when changing downloaded status to wanted

sickbeard/metadata/mede8er.py
- override write_ep_file and write_show_file from generic metadata
object to include xml_declaration=True in the data.write call
Fixes issues with mede8er not properly recognizing xml file data by
adding the <?xml version='1.0' encoding='utf-8'?> declaration at the top
of the files.
https://github.com/SiCKRAGETV/sickrage-issues/issues/927
=> Fix mede8er xml declarations

sickbeard/clients/deluge.py
Bug introduced in
https://github.com/SiCKRAGETV/SickRage/commit/646a3092813aa2bd22bbe908951a81a5b9ec7ebe
See https://github.com/SiCKRAGETV/sickrage-issues/issues/964 for more info
Ref PR: https://github.com/SiCKRAGETV/SickRage/pull/1528
=> Fix deluge client not working

sickbeard/providers/torrentday.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/958 for more info
=> TorrentDay: Improved logging

sickbeard/clients/generic.py
To get more detailled logging, see https://github.com/SiCKRAGETV/sickrage-issues/issues/955 for more info
=> Output more info when unable to parse bencoded data

sickbeard/providers/iptorrents.py
Warn user if searching in sponly mode
See https://github.com/SiCKRAGETV/sickrage-issues/issues/852 for more info
=> IPT: Redone findSearchResults forcing search in eponly mode

sickbeard/metadata/generic.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/973
=> Change tvrage error to warning

gui/slick/interfaces/default/inc_addShowOptions.tmpl
If you add a new show, all episodes are missed.
=> Update set status description

sickbeard/clients/generic.py
Reverts SiCKRAGETV/SickRage#1565
=> Revert "Hotfix - Remove BTFailure and add Exception"

sickbeard/versionChecker.py
@abeloin done!
```
2015-03-16 13:19:17 INFO     CHECKVERSION :: Update failed!
2015-03-16 13:19:17 INFO     CHECKVERSION :: Please enable 'git reset' in settings or stash your changes in local files
2015-03-16 13:19:09 INFO     CHECKVERSION :: Config backup successful, updating...
2015-03-16 13:18:08 INFO     CHECKVERSION :: Config backup in progress...
2015-03-16 13:18:07 INFO     CHECKVERSION :: New update found for SickRage, starting auto-updater ...
2015-03-16 13:18:02 INFO     MAIN :: Building internal name cache for all shows
2015-03-16 13:18:02 INFO     MAIN :: No scene exceptions update needed
2015-03-16 13:18:02 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
```
=> Show warning message to enable git reset or stash changes

sickbeard/common.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/975
=> Add 'tp' (Beyond TV) to mediaExtensions

sickbeard/providers/hdtorrents.py
TODO: disable partial search string / season mode
@abeloin to disable season mode, should I only remove the entire "def _get_season_search_strings(self, ep_obj)" ?
=> Fix HDTorrents

sickbeard/webserve.py
Another commit changed this change:
https://github.com/SiCKRAGETV/SickRage/pull/1507
=> Fix restart page

gui/slick/interfaces/default/home_postprocess.tmpl, sickbeard/processTV.py, sickbeard/webserve.py
- Adds a checkbox to delete files/folders just like auto Processing does
- Defaults to off
=> Add option to delete files/folders when using manual Post Processing

sickbeard/__init__.py, sickbeard/common.py, sickbeard/search.py, sickbeard/show_name_helpers.py
see https://github.com/SiCKRAGETV/sickrage-issues/issues/979
=> Support for Foreign Releases based on Show Language

sickbeard/__init__.py, sickbeard/common.py, sickbeard/search.py, sickbeard/show_name_helpers.py
Reverts SiCKRAGETV/SickRage#1570
=> Revert "Support for Foreign Releases based on Show Language"

gui/slick/interfaces/default/config_search.tmpl, sickbeard/__init__.py, sickbeard/sab.py, sickbeard/webserve.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/985
=> Add option to use force priority in SAB

gui/slick/interfaces/default/config_search.tmpl, sickbeard/__init__.py, sickbeard/webserve.py
@neoatomic this fixes the sab_forced
=> Add coming ep missed range & Fix sab_forced addtion

gui/slick/js/recommendedShows.js, sickbeard/webserve.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/301
Also asked trakt to not show this bad shows in recommendations
=> Fix Trakt date and remove bad shows from recommendations

gui/slick/interfaces/default/home.tmpl
See https://github.com/SiCKRAGETV/sickrage-issues/issues/984 for more info
=> Fix network sorting with small poster, banner in home.tmpl

gui/slick/interfaces/default/comingEpisodes.tmpl
See https://github.com/SiCKRAGETV/sickrage-issues/issues/984 for more info
=> Fix network sorting with comingEpisodes.tmpl

sickbeard/logger.py
All submitted issues the shows:
2.7.x (default, Mar 18 2014, 05:13:23)
[GCC 4.6.3]
=> Remove newline from Python Version info

gui/slick/interfaces/default/config.tmpl
@neoatomic can you test this in SYNOLOGY?
check if it will appear:
/share/MD0_DATA/.qpkg/SickBeard-TVRage/config/Logs
or something like that
=> Add Log directory to config page

gui/slick/interfaces/default/home_newShow.tmpl
Bugfix because it should warn user
=> Add message about TVRAGE not support banner/posters

gui/slick/interfaces/default/manage.tmpl, gui/slick/interfaces/default/manage_massEdit.tmpl
https://github.com/SiCKRAGETV/sickrage-issues/issues/836
@Hellowlol can you try? use this file please
=> Fix "mass edit" subtitle enable action

SickBeard.py, gui/slick/interfaces/default/config_general.tmpl, sickbeard/__init__.py, sickbeard/webserve.py
- Added Checkbox in Config - General - Advanced "Restart Only"
- Added check for NO_RESTART to shutdown procedure, if true won't
relaunch SR process.
As requested: https://github.com/SiCKRAGETV/sickrage-issues/issues/222
=> Allow Shutdown Only when restarting

gui/slick/interfaces/default/manage.tmpl, gui/slick/interfaces/default/manage_massEdit.tmpl
Reverts SiCKRAGETV/SickRage#1592
=> Revert "Fix "mass edit" subtitle enable action"

gui/slick/css/dark.css, gui/slick/css/light.css, gui/slick/css/style.css, gui/slick/interfaces/default/home.tmpl, gui/slick/interfaces/default/inc_top.tmpl, gui/slick/js/lib/jquery.tablesorter.widget-columnSelector-2.17.7.js
Added new column "previous episodes", disable by default.
=> Added the ability to choose displaying columns in home.tmpl.

gui/slick/interfaces/default/manage.tmpl
Updated text to "Search Subtitle"
=> Added status column for subtitle.

sickbeard/providers/t411.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1003
=> T411 - Add subcat 639 (tv-show not tv-series)

sickbeard/providers/hdtorrents.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1006
=> Fix HDT proper/repack search

gui/slick/interfaces/default/home.tmpl
Also make sure they are always on top.
=> home.tmpl: Fix loading show js error.

lib/subliminal/videos.py
Revert https://github.com/SiCKRAGETV/SickRage/pull/1540 adding if
=> Fix subliminal not working properly on Windows.

gui/slick/css/dark.css, gui/slick/css/light.css, gui/slick/interfaces/default/displayShow.tmpl, gui/slick/js/ajaxEpSearch.js, sickbeard/providers/btn.py, sickbeard/providers/ezrss.py, sickbeard/providers/generic.py, sickbeard/providers/iptorrents.py, sickbeard/providers/nyaatorrents.py, sickbeard/providers/tokyotoshokan.py, sickbeard/search.py, sickbeard/search_queue.py, sickbeard/tv.py, sickbeard/tvcache.py, sickbeard/webserve.py
Manual Search ask 2 questions:
* If failed enable, ask to mark release failed Yes/No.
* If to download: > or >= currQual Yes/No
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1005 for more info
=> DisplayShow: ManualSearch ask if failed and/or download current qual 

gui/slick/interfaces/default/config_postProcessing.tmpl
=> Remove hardlink and symlink from actions if Win32

sickbeard/helpers.py, sickbeard/providers/generic.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1007 for more info
=> Proxy: Add a check for theGlypeProxy ssl warning for providers proxies 

gui/slick/interfaces/default/comingEpisodes.tmpl, gui/slick/interfaces/default/displayShow.tmpl, gui/slick/js/ajaxEpSearch.js, sickbeard/webserve.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/921 for more info
=> comingEpisodes: Added js logic for forceupdate

sickbeard/properFinder.py, sickbeard/search.py
Torrent file content was dropped along to way to sendtorrent
=> properfind: Fix forgotten content

sickbeard/providers/womble.py
Added the tv-x264 and tv-dvd RSS categories to Wombles Provider
=> Update Wombles for tv-x264 and tv-dvd

gui/slick/interfaces/default/inc_bottom.tmpl
Cherry Pick two features from SickGear
* Add percentage of episodes downloaded to footer and remove double
spaces in text
* Add a link from the footer number of snatched to episode snatched
overview page.
=> Add Percent to Footer and Link to Snatched

sickbeard/__init__.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1011 for more info
=> Move encryption_version to the first item read from the config.

sickbeard/search.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1013 for more info
=> Fix error Torrent file content is empty on magnet torrent

sickbeard/helpers.py, sickbeard/postProcessor.py
- Checks free diskspace on destination before deleting old episodes and
copying/moving the new one over.
=> Added Free Space check in PP before deleting files

gui/slick/interfaces/default/home.tmpl
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1016 for more info
=> home.tmpl: Fix search show name

gui/slick/interfaces/default/config_general.tmpl, sickbeard/__init__.py, sickbeard/helpers.py, sickbeard/metadata/generic.py, sickbeard/metadata/kodi_12plus.py, sickbeard/metadata/mede8er.py, sickbeard/metadata/mediabrowser.py, sickbeard/metadata/tivo.py, sickbeard/metadata/wdtv.py, sickbeard/show_queue.py, sickbeard/webapi.py, sickbeard/webserve.py
Squashed original PR: https://github.com/SiCKRAGETV/SickRage/pull/1372
=> Added Default Info Language in general settings

gui/slick/interfaces/default/home_newShow.tmpl, sickbeard/indexers/indexer_api.py, sickbeard/webapi.py, sickbeard/webserve.py
Indexer valid language returned sorted with default as first.
webapi use langabbv_to_id from indexerapi
Change new show to use default language. For https://github.com/SiCKRAGETV/SickRage/pull/1633
=> Various fixes

sickbeard/providers/hounddawgs.py
Added a check for "Dine cookies er ikke aktiveret." in login.
Added a session.get before the post
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1019 for more info
=> Hounddawgs: Various fixes.

sickbeard/show_queue.py
Reverts SiCKRAGETV/SickRage#1509
=> Revert "Remove traceback from showupdater"

gui/slick/interfaces/default/editShow.tmpl, gui/slick/interfaces/default/home.tmpl, sickbeard/__init__.py, sickbeard/search.py, sickbeard/showUpdater.py, sickbeard/show_queue.py, sickbeard/traktChecker.py, sickbeard/webapi.py, sickbeard/webserve.py
Fix traktRolling enable even if Trakt wasn't. See https://github.com/SiCKRAGETV/sickrage-issues/issues/1025
Restore check mark for ended show in home.
Redone logging showQueue.UpdateShow
=> Various fixes.

sickbeard/tv.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1032
=> Change removed episodes status from IGNORED to ARCHIVED

sickbeard/helpers.py, sickbeard/postProcessor.py
- Changed the call to verify_freespace to check against show_location
- Changed the oldfile check to only check if oldfile.location actually
is a file.
https://github.com/SiCKRAGETV/sickrage-issues/issues/1036
=> Fix verify_freespace to check show location and check old file exists

gui/slick/interfaces/default/editShow.tmpl, sickbeard/postProcessor.py
Prevent conflict between regular and special episode(Same airdate)
https://github.com/SiCKRAGETV/sickrage-issues/issues/72
=> PP Airdate: Check without season 0 first

gui/slick/interfaces/default/home.tmpl
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1037 for more info
=> Fix don't display prev and next airs if date is invalid

gui/slick/interfaces/default/config_notifications.tmpl, gui/slick/js/configNotifications.js, sickbeard/notifiers/trakt.py, sickbeard/webserve.py
Fix for 'Could not connect to Trakt service: error 404 Client Error: Not Found'
Added check for balcklist value
=> fix trending blacklist management

sickbeard/name_parser/regexes.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/329 for more info
=> Added anime regex for 003-004. Show Name - Ep Name.ext

lib/trakt/exceptions.py, lib/trakt/trakt.py, sickbeard/traktChecker.py, sickbeard/webserve.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1041
=> Handle Trakt URL error code 500

sickbeard/webserve.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/937 for more info
=> Add show: fix improperly decoded utf-8 characters

gui/slick/interfaces/default/config_general.tmpl
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1035 for more info
=> Hide proxy_indexers when proxy_settings is empty

gui/slick/interfaces/default/displayShow.tmpl
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1046 for more info
=> Fix: cannot find 'PLAY_VIDEOS'

sickbeard/providers/t411.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1054
=> Fix torrentname with special char

sickbeard/postProcessor.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1023 for more info
=> PostProcess: Fix lower quality, bigger sized file overwriting current episode.

sickbeard/__init__.py, sickbeard/config.py, sickbeard/helpers.py, sickbeard/webserve.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1012 for more info
=> Password encryption switch to v2

lib/trakt/exceptions.py, lib/trakt/trakt.py
Previous commit didn't updated line 87
=> Trakt: Catch all internal server error and log a warning

gui/slick/interfaces/default/config_postProcessing.tmpl
https://github.com/SiCKRAGETV/sickrage-issues/issues/1056
TODO: New Wiki needs some formatting
=> Add note to PP Extra scripts settings

gui/slick/interfaces/default/config_general.tmpl, sickbeard/webserve.py
https://github.com/SiCKRAGETV/SickRage/pull/1660
=> Add DEBUG setting to UI

sickbeard/webserve.py
=> anidb: add log line for editshow

sickbeard/providers/kat.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1055
=> KAT : enclosure season search with " when searching for season number

sickbeard/search.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1065 for more info
=> Fix torrent empty in multi-episode

sickbeard/providers/tntvillage.py
The season pack returned invalid results.
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1017 for more info
=> tntvillage: Cleanup

sickbeard/providers/t411.py
Use T411 API instead of web scrapping
=> Use T411 API instead of web scrapping

sickbeard/providers/tntvillage.py
This PR will get season pack as in TNTVillage (XXX S01E01-24) and change it accordingly to what sickrage expect (xxx S01).
=> Patch tntvillage season pack manage

sickbeard/webserve.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1069
@abeloin
=> Fix episode description decode error in calendar

gui/slick/interfaces/default/config_general.tmpl
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1085 for more info
=> Fix default delete episode in GUI

sickbeard/scene_exceptions.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1086 for more info
=> XEM: Skip invalid entries

sickbeard/logger.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1085 for more info
=> submit error: if no title, use default one

sickbeard/providers/alpharatio.py, sickbeard/providers/animenzb.py, sickbeard/providers/animezb.py, sickbeard/providers/bitsoup.py, sickbeard/providers/btn.py, sickbeard/providers/ezrss.py, sickbeard/providers/eztv.py, sickbeard/providers/freshontv.py, sickbeard/providers/generic.py, sickbeard/providers/hdbits.py, sickbeard/providers/hdtorrents.py, sickbeard/providers/hounddawgs.py, sickbeard/providers/iptorrents.py, sickbeard/providers/kat.py, sickbeard/providers/morethantv.py, sickbeard/providers/newznab.py, sickbeard/providers/nextgen.py, sickbeard/providers/nyaatorrents.py, sickbeard/providers/oldpiratebay.py, sickbeard/providers/omgwtfnzbs.py, sickbeard/providers/rarbg.py, sickbeard/providers/scc.py, sickbeard/providers/speedcd.py, sickbeard/providers/t411.py, sickbeard/providers/thepiratebay.py, sickbeard/providers/tntvillage.py, sickbeard/providers/tokyotoshokan.py, sickbeard/providers/torrentbytes.py, sickbeard/providers/torrentday.py, sickbeard/providers/torrentleech.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/853 for more info
~~Currently min_seeds and min_leechs doesn't work because rarbg return an error. Make sure they are set to nothing in the settings~~ Fixed upstream
=> RarBG: redone using api.

lib/rtorrent/lib/xmlrpc/requests_transport.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1061 for more info
=> rtorrent: Fix encoding issue in windows

lib/trakt/trakt.py, sickbeard/traktChecker.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1059
Changes the API URL to the Trakt V2.0 API URL
Fixes an error that can occur in TracktChecker if show is missing tvrage id on Trakt
=> Trakt API Changes / Tweaks

sickbeard/providers/rarbg.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1102 for more info
=> RarBG: Add new search strings to catch error response

sickbeard/providers/generic.py, sickbeard/providers/hounddawgs.py, sickbeard/providers/iptorrents.py, sickbeard/providers/nextgen.py, sickbeard/providers/nyaatorrents.py, sickbeard/providers/rarbg.py, sickbeard/providers/tokyotoshokan.py
Remove error introduced in https://github.com/SiCKRAGETV/SickRage/pull/1703
=> Providers: Revert _get_title_and_url

gui/slick/interfaces/default/config_general.tmpl, gui/slick/interfaces/default/config_search.tmpl, sickbeard/webserve.py
This setting is for the GUI and as nothing to do with search settings
=> Relocated coming_eps_missed_range to user interface in UI

gui/slick/interfaces/default/config_search.tmpl, sickbeard/webserve.py
Still available via config.ini
=> Remove access to settings backlog days

gui/slick/js/newShow.js
https://github.com/SiCKRAGETV/sickrage-issues/issues/1098
=> Remove white spaces from add show search string

sickbeard/providers/eztv.py
From commit https://github.com/SiCKRAGETV/SickRage/pull/1561
=> EZTV: Fix missing import

gui/slick/interfaces/default/config_notifications.tmpl, gui/slick/interfaces/default/inc_top.tmpl, gui/slick/interfaces/default/status.tmpl, sickbeard/__init__.py, sickbeard/config.py, sickbeard/helpers.py, sickbeard/properFinder.py, sickbeard/providers/rarbg.py, sickbeard/scheduler.py, sickbeard/searchBacklog.py, sickbeard/show_queue.py, sickbeard/subtitles.py, sickbeard/traktChecker.py, sickbeard/webserve.py
Fix proper running 2 times
Fix backlog encoding error in windows
Remove rarbg log line
Added scheduler status page
Added Queue status
Stop thread for all scheduled items
replace except: by except Exception: in sickbeard/__init__.py
Remove condition checker since scheduler.enable replace it
Revert nyaa
Moved try...except in scheduler to catch the whole run
Process add show queue item with a HIGH priority
Make start_time start on the hour
Change TRAKT_ROLLING_FREQUENCY into hours.
Cleanup
=> Feature: Scheduler: Redone

sickbeard/config.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1141 for more info
=> Missing file changes from rebase on the scheduler

sickbeard/tv.py, sickbeard/webserve.py
Revert commit https://github.com/SiCKRAGETV/SickRage/commit/728b79f5db6fd6ead56b874c2a030dafc794e320 which cause issue https://github.com/SiCKRAGETV/sickrage-issues/issues/1138#issuecomment-90972225
=> Show wanted in displayShow

sickbeard/providers/rarbg.py
Get a new token on Inalid token
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1131 for more info
=> RarBG: Retry 3 times before failling.

sickbeard/webserve.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1110
=> Add TRAKTROLLING to filter in viewlog

gui/slick/interfaces/default/home.tmpl
See  https://github.com/SiCKRAGETV/SickRage/pull/1724
=> home filter: change to allow to use parsed data for active(yes/no)

sickbeard/helpers.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1134
=> Check getURL response before return

gui/slick/interfaces/default/config_postProcessing.tmpl
Reverts SiCKRAGETV/SickRage#1612
=> Revert "Remove hardlink and symlink from actions if Win32"

sickbeard/helpers.py
Reverts SiCKRAGETV/SickRage#1727
=> Revert "Check getURL response before return"

sickbeard/providers/eztv.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1177 for more info
And https://github.com/SiCKRAGETV/sickrage-issues/issues/1134
=> EZTV: Temporary fix for getURL json

sickbeard/providers/oldpiratebay.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1074 for more info
=> OldTPB: Check if the returned results are proper|repack

sickbeard/__init__.py, sickbeard/webserveInit.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1156 for more info
**Edited by abeloin: Include ref to issue**
=> Tornado: Ability to switch gzip on/off via config.ini:web_use_gzip

gui/slick/css/dark.css, gui/slick/css/light.css, gui/slick/css/style.css, gui/slick/interfaces/default/displayShow.tmpl
* Added Colum Selector Widget to displayShow
* Cleaned up CSS to not over-ride SickRage CSS colors and font strength
FR https://github.com/SiCKRAGETV/sickrage-issues/issues/1015
=> Add column widget selector to "displayShow"

gui/slick/css/dark.css, gui/slick/css/light.css, gui/slick/css/style.css, gui/slick/interfaces/default/displayShow.tmpl
Reverts SiCKRAGETV/SickRage#1741
=> Revert "Add column widget selector to "displayShow""

gui/slick/interfaces/default/editShow.tmpl
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1217 for more info
=> editShow: Select the default indexer language instead of forcing en

sickbeard/clients/generic.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1215
=> Change timeout errors to WARNING in clients

gui/slick/interfaces/default/displayShow.tmpl, gui/slick/js/displayShow.js, sickbeard/webserve.py
* Adds a pause button on the displayShowPage to Pause/Unpause a show
without needing to go into editShow.
=> FR: Add Pause Button on displayShow page

sickbeard/helpers.py
- Uses DVD order on TVDB and TVRage queries to get the correct episode
https://github.com/SiCKRAGETV/sickrage-issues/issues/1132
=> Fix Episode Thumbnail url when show is in DVD Order

sickbeard/notifiers/libnotify.py
libnotify support was broken by ef4470b which introduced gi.repository for the first time.
This is incompatible with pynotify. Switching to gir-notify resolves the issue.
Also fixes the file path for the notification icon.
Fixes SiCKRAGETV/sickrage-issues#733
Tested, works on Ubuntu 15.04 which uses gir1.2-notify-0.7 (which is same package used in all Debian/Ubuntu versions except Debian Squeeze and Ubuntu Precise).
=> use gir-notify instead of pynotify

sickbeard/notifiers/emailnotify.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1207
=> Catch emailnotify smtp error.

sickbeard/providers/rarbg.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/853
=> Add user agent to RARBG

sickbeard/notifiers/kodi.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1235
=> Catch all errors from Kodi notify

sickbeard/providers/iptorrents.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1201 for more info
=> iptorrent: Add missing import

sickbeard/webserve.py
- Adds a line to the logfile containing the IP address of the client
logging into the web UI.
- Creates an INFO log on success, a WARNING log on failure.
https://github.com/SiCKRAGETV/sickrage-issues/issues/1251
=> Adds a log line containing connecting IP on login

gui/slick/interfaces/default/config_notifications.tmpl, gui/slick/js/configNotifications.js, sickbeard/encodingKludge.py, sickbeard/notifiers/plex.py, sickbeard/webserve.py
* Ported the Plex Notification changes from SickGear.
* Added the option to use Plex Token vs Username / Password.
=> Plex Notification fix

sickbeard/providers/eztv.py
Slight changes in the HTML occurred on 2015-04-14
=> HTML changes of https://eztv.ch

sickbeard/tvcache.py
Fix SiCKRAGETV/sickrage-issues#1017
=> Added msg for partial download of multi-episode torrent isn't supported

gui/slick/interfaces/default/displayShow.tmpl, gui/slick/interfaces/default/inc_top.tmpl, gui/slick/js/displayShow.js, sickbeard/webserve.py
* Moves the pause button to the sub-menu to the right of the edit
button.
* Returns the image indicators back to their previous state
=> FR#835 Patch 1:  Move pause to submenu

sickbeard/webserve.py
* changed KODI Update button to return to show page when clicked
=> FR# 774: Stay on Show Page after "Update Kodie"

sickbeard/webserve.py
=> Fix NameError: global name 'ShowObj' is not defined

sickbeard/webserve.py
The code start the trakt rolling download process on the show that has been unpause from submenu button the sema way it has if you change paramenter in edit show
=> Manage Rolling Download on unpause from submenu button

gui/slick/interfaces/default/config_search.tmpl, gui/slick/js/configSearch.js, sickbeard/__init__.py, sickbeard/clients/__init__.py, sickbeard/clients/qbittorrent.py
Feature request [#838](https://github.com/SiCKRAGETV/sickrage-issues/issues/838)
=> Added qbittorrent support

sickbeard/tv.py
=> Change Opensubtitles 503 error to warning

sickbeard/tv.py
Reverts SiCKRAGETV/SickRage#1782
=> Revert "Change Opensubtitles 503 error to warning"

sickbeard/helpers.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/838
https://github.com/SiCKRAGETV/sickrage-issues/issues/1309
=> Fix code description error

gui/slick/css/light.css
* Fix CSS for Light Theme Season header
=> FR#1015 light.css fix for Season header

sickbeard/providers/iptorrents.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1309
=> Update IPTorrents search URL

sickbeard/providers/iptorrents.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1309
=> Update IPTorrents search URL 2

sickbeard/providers/t411.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1336 for more info
=> T411: Catch invalid data, log, and continue

sickbeard/tv.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1337 for more info
=> Add missing import for ServiceError

sickbeard/db.py, tests/all_tests.py, tests/common_tests.py, tests/config_tests.py, tests/db_tests.py, tests/encoding_tests.py, tests/feedparser_tests.py, tests/issue_submitter_tests.py, tests/name_parser_tests.py, tests/pp_tests.py, tests/scene_helpers_tests.py, tests/snatch_tests.py, tests/test_lib.py, tests/torrent_tests.py, tests/tv_tests.py, tests/xem_tests.py
Fixed travis build tests, all are working and being ran. None of the tests actually got done before.  Fix for #1525 without breaking the build.
Is it ok that I set journal_mode = OFF? Build does not work without this setting.
=> Build tests fix, replaces #1525

sickbeard/webserve.py
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/1349
=> Fix TypeError: cannot concatenate 'str' and 'int' objects

sickbeard/db.py, tests/test_lib.py
Use journal_mode MEMORY when in unit test
=> Unit test: change journal mode when in unit test

sickbeard/notifiers/emailnotify.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1352
=> Fix missing import traceback

sickbeard/versionChecker.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1355
=> Fix missin amActive

sickbeard/providers/scenetime.py
Sorry for the delay. Got hung up with things.
This is essentially the same thing I submitted wednesday. Started rewriting it, but ended up reverting.
=> Fix scenetime index bug (sickrage-issues/#1354)

sickbeard/providers/morethantv.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1321
=> Fix Morethantv (http to https)

sickbeard/webserve.py
* fix shoObj referenced before initialization
=> FIX#1397 - updateKODI showObje error

gui/slick/interfaces/default/config_general.tmpl, gui/slick/interfaces/default/displayShow.tmpl, sickbeard/__init__.py, sickbeard/webserve.py
* Adds an option in general config to collapse all but the current
season
* Buttons to show and hide seasons added to the season headers
=> FR#1040 - Collapse passed seasons

sickbeard/providers/btn.py
@SiCKRAGETV/moderators any of you have BTN to test this?
=> BTN - Show warning instead of error for api call exceeded

gui/slick/css/dark.css, gui/slick/css/light.css, gui/slick/css/style.css, gui/slick/interfaces/default/displayShow.tmpl, gui/slick/interfaces/default/editShow.tmpl, gui/slick/interfaces/default/home_newShow.tmpl, gui/slick/interfaces/default/inc_addShowOptions.tmpl, gui/slick/interfaces/default/inc_blackwhitelist.tmpl, gui/slick/js/newShow.js, sickbeard/blackandwhitelist.py, sickbeard/search.py, sickbeard/show_name_helpers.py, sickbeard/show_queue.py, sickbeard/tv.py, sickbeard/webserve.py
* Change anime release groups to in memory storage for lowered latency
* Add anime release groups to add new show options page
Ports the following two PR's from SickGear
https://github.com/SickGear/SickGear/pull/162
https://github.com/SickGear/SickGear/pull/153
=> Add anime release groups to add new show page

gui/slick/js/blackwhite.js, sickbeard/show_queue.py
* Add missing javascript file
* Add missing import from show_queue.py
=> FIX: Add anime to new show page

gui/slick/interfaces/default/manage.tmpl, gui/slick/js/massUpdate.js
* Adds a confirmation dialog when deleting shows on the Mass Edit page
=> FIX#1226 - Confirm Show Delete for Mass Edit

gui/slick/interfaces/default/home_recommendedShows.tmpl, gui/slick/js/recommendedShows.js, sickbeard/webserve.py
* Modified Recommended Shows to match trending shows
* Recommended Shows uses Blacklist and collection filtering from
Trending Shows
=> FR#1409  Recommended Shows Update

sickbeard/providers/iptorrents.py
adds ability to search for shows in the format SxEE as well as the current SXXEXX format on IPT, sa me code sourced from other providers
=> add multi-search IPT

gui/slick/interfaces/default/home.tmpl
* Saves Last Used Filter on the Home Page when using Filter Row
=> FR: SaveFilter

sickbeard/postProcessor.py
Make sure the show dir is chmodded the same as parent if PP has to make the show dir...
=> Missing chmod

gui/slick/js/manageEpisodeStatuses.js
* Added Persistent Colllapse / Expand feature on Episode Management Page
=> FR#1419: Add Persistent Collapse Expand Buttons on Episode management

lib/requests/__init__.py, lib/requests/adapters.py, lib/requests/api.py, lib/requests/auth.py, lib/requests/compat.py, lib/requests/cookies.py, lib/requests/models.py, lib/requests/packages/__init__.py, lib/requests/packages/urllib3/__init__.py, lib/requests/packages/urllib3/_collections.py, lib/requests/packages/urllib3/connection.py, lib/requests/packages/urllib3/connectionpool.py, lib/requests/packages/urllib3/contrib/pyopenssl.py, lib/requests/packages/urllib3/exceptions.py, lib/requests/packages/urllib3/poolmanager.py, lib/requests/packages/urllib3/response.py, lib/requests/packages/urllib3/util/connection.py, lib/requests/packages/urllib3/util/ssl_.py, lib/requests/sessions.py, lib/requests/utils.py
Reverts SiCKRAGETV/SickRage#1860
=> Revert "Update requests library from v2.5.1 to v2.6.2 ff71b25e"

sickbeard/databases/mainDB.py
Stops SR from creating 10 sickbeard.db* on first launch, and improves first time launch speed.
Gets rid of the logline "Missing idx_indexer_id for TV Shows table detected!, fixing..." on fresh boot, as its that column is created with the initial schema.
=> Update mainDB.InitialSchema to v42 to prevent db upgrades on a fresh DB

gui/slick/css/dark.css, gui/slick/css/light.css, gui/slick/css/style.css
Fixes SiCKRAGETV/sickrage-issues#1504
=> Center Search icon on displayShowTable

gui/slick/css/dark.css, gui/slick/css/light.css, gui/slick/css/style.css, gui/slick/interfaces/default/displayShow.tmpl, gui/slick/interfaces/default/history.tmpl
Fixes Quality colors due to changes for "funky naming"
=> Fix#1558 Fix Quality Colors on History and displayShow pages

gui/slick/js/blackwhite.js
* Fixed manual adding of group to black or white list
=> Fix#1603 - Manual add to Black / White list failed

sickbeard/webapi.py
@TagForce 
https://github.com/SiCKRAGETV/sickrage-issues/issues/1536
=> Add failed option to PP API

gui/slick/js/fuzzyMoment.js
=> Uppercase 'in' and 'a' in fuzzy dates.

sickbeard/providers/generic.py
Hi,
This PR is the simplest fix proposed at
SiCKRAGETV/sickrage-issues#1538
=> Failed Download Handler: Size Fix

gui/slick/interfaces/default/inc_top.tmpl
Reverts SiCKRAGETV/SickRage#1852
=> Revert "Update template"

gui/slick/interfaces/default/config_notifications.tmpl, gui/slick/js/configNotifications.js, lib/trakt/trakt.py, sickbeard/__init__.py, sickbeard/notifiers/trakt.py, sickbeard/traktChecker.py, sickbeard/webserve.py
* Implements Trakt PIN Auth as the V2 API will be deprecating the media
center auth method
NOTE: The TRAKT_API_KEY, TRAKT_API_SECRET, and TRAKT_PIN_URL are test
values.  They need to be replaced before final merge
=> Feature: Trakt PIN Auth

lib/pynma/pynma.py
Fix for https://github.com/SiCKRAGETV/sickrage-issues/issues/1691
Changed the URL.
=> Fix for issue #1691

sickbeard/scene_exceptions.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1643
=> Change check scene exceptions from error to warning

sickbeard/name_parser/regexes.py
Add parser for the web site ISLAND FANSUB
=> Update regexes.py for the web site ISLAND FANSUB (ANIME)

sickbeard/webserve.py
Gives possibility to add coverflow layout to homepage (For a theme i am working on)
=> Small change for additional layout.

sickbeard/notifiers/kodi.py, sickbeard/processTV.py, sickbeard/show_name_helpers.py
Fixes double logging of "Already Processed" files and rars, moves alot of info to debug and a few debug to warning (when user settings are wrong).
=> Logging changes and improvements.

sickbeard/image_cache.py, sickbeard/postProcessor.py, sickbeard/processTV.py, sickbeard/scene_exceptions.py, sickbeard/search.py, sickbeard/searchBacklog.py, sickbeard/tv.py
This will help us find some problems easier with less log clutter we can see the cases where things fail but do not provide enough info.
=> More log cleanup and fixes. Move lower level actions to debug

gui/slick/interfaces/default/home.tmpl, sickbeard/databases/mainDB.py
@fernandog This will fix your DB.
=> Fix for potential bad episode airdates preventing SR from starting.

sickbeard/providers/rarbg.py
https://rarbg.com/pubapi/apidocs_v2.txt
=> Update RARBG category to 'tv'

sickbeard/providers/rarbg.py
Reverts SiCKRAGETV/SickRage#1939
=> Revert "Update RARBG category to 'tv'"

sickbeard/providers/rarbg.py
Some proxies don't support https, fallback to http on failure, check for no-json or dirty json and handle it.
=> Fix SiCKRAGETV/sickrage-issues#1554

sickbeard/common.py, sickbeard/providers/newznab.py, tests/all_tests.py, tests/test_lib.py
Fixes SiCKRAGETV/sickrage-issues#1556
Fixes SiCKRAGETV/sickrage-issues#1808
=> Limit newznab searches to 400 results, clean up logging

sickbeard/name_parser/parser.py
Fixes SiCKRAGETV/sickrage-issues#1835
=> Properly import sickbeard.exceptions.ex

sickbeard/webserve.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1842
=> Fix remove default ep status

lib/trakt/trakt.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1838
=> Add Trakt empty token error message

sickbeard/webserve.py
@miigotu only these two lines in html tag in ui.notification
=> Remove html tags from ui.notifications

sickbeard/providers/torrentday.py
Fix basic torrentday usage. Still may not work with proxies.
=> Fix torrentday

sickbeard/helpers.py, sickbeard/processTV.py, sickbeard/properFinder.py, sickbeard/webserve.py
Missing sleep in properFinder between snatches.
Filter .torrent and .nzb files from pp list.
=> More fixes 2

sickbeard/search.py
SiCKRAGETV/sickrage-issues#1852
=> Failed to load URL? This section needs debugged hard

sickbeard/providers/rarbg.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1858
until SSL gets fixed in SR
=> Remove https from rarbg token

.gitmodules, sickbeard/indexers/indexer_config.py, sickbeard/name_cache.py, sickbeard/network_timezones.py, sickbeard/providers/scc.py, sickbeard/scene_exceptions.py, sickbeard/scene_numbering.py
git submodule update and commit when scene exceptions or network_timezones change.
=> Try again with the name_cache lock. there was a deadlock. Add submodules for scene_exceptions and network_timezones

CHANGES.md
As sugested in: https://github.com/SiCKRAGETV/sickrage-issues/issues/1893
=> Updated Changelog

gui/slick/interfaces/default/displayShow.tmpl
https://github.com/SiCKRAGETV/sickrage-issues/issues/1900
=> Change Trakt genre url

sickbeard/notifiers/plex.py
@Thraxis can you test this please?
https://github.com/SiCKRAGETV/sickrage-issues/issues/1756
=> Check if user needs to add token to PLEX

sickbeard/providers/scc.py
SiCKRAGETV/sickrage-issues/issues/1922
=> Fix a logline string formatting error in SCC.

sickbeard/scene_numbering.py
SiCKRAGETV/sickrage-issues#1913
=> Wrong import

sickbeard/postProcessor.py
Fix SiCKRAGETV/sickrage-issues#1930
=> Fix SiCKRAGETV/sickrage-issues#1930

sickbeard/notifiers/boxcar2.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1855
=> Add timeout to Boxcar2

sickbeard/providers/generic.py
in download page
https://github.com/SiCKRAGETV/sickrage-issues/issues/1932
=> Temporary remove torcache due to JS timer

sickbeard/tv.py
@neoatomic please test this. with this SR will loop th all files without crashing
https://github.com/SiCKRAGETV/sickrage-issues/issues/1913
=> Add new exception handle to avoid break loop th files

sickbeard/tv.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1913
=> Add exception handling to sql commands

sickbeard/search.py
=> Add log message when ignoring result from provider

sickbeard/show_queue.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1959
=> Change message about unable to find show

sickbeard/providers/hdtorrents.py
Why sceneaccess here?
@miigotu
=> Remove www from HDT

gui/slick/interfaces/default/displayShow.tmpl, gui/slick/interfaces/default/history.tmpl, sickbeard/history.py, sickbeard/subtitles.py, sickbeard/tv.py
=> Various fixes for subtitles

sickbeard/providers/hdtorrents.py
=> Fixup HDTorrents provider

sickbeard/helpers.py
Fixes SiCKRAGETV/sickrage-issues#1998
=> Fix possible filename encoding problem

sickbeard/tv.py
=> Wrong module for method - subliminal.subtitle.get_subtitle_path

sickbeard/tv.py
=> Fix release_name extension detection for subtitle downloads

sickbeard/providers/newznab.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/2006
=> Add main TV category to newznab categories

gui/slick/interfaces/default/displayShow.tmpl
Issue: SiCKRAGETV/sickrage-issues#1927
=> Fix for SiCKRAGETV/sickrage-issues#1927

SickBeard.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/2097
=> Re-add namecache creation to SickBeard.py

lib/trakt/trakt.py
Avoid this:
```
AA
AAtraktException: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=5)
AA    raise traktException(e)
AA  File "/home/osmc/SickRage/lib/trakt/trakt.py", line 97, in traktRequest
AA    TraktEpisodeWatchlist = self.trakt_api.traktRequest("sync/watchlist/episodes")
AA  File "/home/osmc/SickRage/sickbeard/traktChecker.py", line 503, in _getEpisodeWatchlist
AA    if self._getEpisodeWatchlist():
AA  File "/home/osmc/SickRage/sickbeard/traktChecker.py", line 237, in syncWatchlist
AA    self.syncWatchlist()
AA  File "/home/osmc/SickRage/sickbeard/traktChecker.py", line 82, in run
```
=> Fix trakt exceptions when connection timed out

lib/trakt/trakt.py
=> Fix trakt return

gui/slick/interfaces/default/inc_addShowOptions.tmpl, gui/slick/js/addShowOptions.js, sickbeard/__init__.py, sickbeard/show_queue.py, sickbeard/webserve.py
@fernandog I think this is good. It won't fix the issues people are having with shows that were added before the default status fix, but it lets you set a default future status while adding the show.
=> Add setting for future episode status

readme.md
=> Update readme.md a little

sickbeard/tv.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/2184
@miigotu agree?
=> Set episodes with airdate as 'never' to UNAIRED status

sickbeard/tv.py
Reverts SiCKRAGETV/SickRage#2122
=> Revert "Set episodes with airdate as 'never' to UNAIRED status"

sickbeard/dailysearcher.py
https://github.com/SiCKRAGETV/SickRage/pull/2123
=> Don not consider episodes with airdate = 1 as aired

sickbeard/tv.py
@fernandog There is no reason to ever ignore an episode with airdate "never" anymore.
People usually had set these from skipped to ignored because they used to show up as missing episodes when they were set to skipped. They no longer get auto set to skipped, and unaired is already not included in missing episodes.
=> Simplify status in tv.py

sickbeard/helpers.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/2210
@miigotu you asked user to do this in forum
https://sickrage.tv/forums/forum/help-support/general-support/24316-updating-zip-creation-error-filesize-would-require-zip64-extensions
=> Fix error: Filesize would require ZIP64 extensions

sickbeard/providers/__init__.py, sickbeard/providers/newznab.py
Fix newznab providers not finding episode/season results
=> Add NZBGeek to newznab providers (Thanks NZBGeek for dev apikey) +fix

gui/slick/interfaces/default/apiBuilder.tmpl, gui/slick/js/apibuilder.js, sickbeard/webapi.py
As suggested by @miigotu in https://github.com/SiCKRAGETV/SickRage/pull/2143#issuecomment-122781376
=> Add an API command to get the fan art of a show

gui/slick/interfaces/default/displayShow.tmpl
@miigotu 
Ntpath has some troubles with single \ in path thats why I did that. Suggestions? OK?
=> Show only basename of filename in display show

sickbeard/traktChecker.py
=> Fix TRAKT log message to use pattern SXXEXX

gui/slick/interfaces/default/config_notifications.tmpl
=> Missing Recommended Shows

gui/slick/interfaces/default/IRC.tmpl, gui/slick/interfaces/default/inc_top.tmpl, sickbeard/webserve.py
Working but you can't leave the page LOL
=> Adds IRC to SickRage

SickBeard.py
=> Remove old clients files

gui/slick/interfaces/default/IRC.tmpl
@miigotu ideia!
maybe we can add two input fields in SR settings to user add user/pass of IRC. 
First we try to use them, if don't exists, use GIT, if don't exist, use "srforum|?"
=> Add GITUSER to IRC

sickbeard/helpers.py
@miigotu when users manually open an issue with this content error we can show them the URL does not work.
will PR this and after some days will remove the 200 log line
=> Fix log lines and add log lines for URL when code is 200

gui/slick/interfaces/default/config_general.tmpl, sickbeard/__init__.py, sickbeard/webserve.py
News,Home,Coming Episodes,History,IRC
@SiCKRAGETV/moderators
=> Adds default page option

gui/slick/interfaces/default/manage_subtitleMissed.tmpl, gui/slick/js/manageSubtitleMissed.js
Fix for SiCKRAGETV/sickrage-issues#2261
=> Add "Collapse" button on subtitles management

sickbeard/helpers.py
intruduced by the cpasbien provider
=> New word ,to removewordlist

sickbeard/helpers.py
=> [www.Cpasbien.pe] to removeWordsList

gui/slick/interfaces/default/history.tmpl, sickbeard/__init__.py, sickbeard/webserve.py
Adds saving history limit by storing it in config.ini
=> Adds option to save history limit selection

sickbeard/providers/generic.py, sickbeard/providers/hdtorrents.py
Cleanup HDTS a bit, fix a small undefined return, fix bug when searching SPONLY for a single episode, which gave logs about it not being a valid season pack.
=> Hdts cleanup

sickbeard/providers/frenchtorrentdb.py, sickbeard/providers/xthor.py
=> Fix returns in xthor and ftdb

sickbeard/scene_numbering.py
Xem refresh was not longer working since commit
12b3da5c4926f3fe12d46b15a17c8b964aca407b
=> Fix Xem refresh

lib/feedparser/feedparser.py, sickbeard/helpers.py, sickbeard/providers/thepiratebay.py
KAT and TPB (and possibly other broken providers via proxy) fixed, as long as you use a client connection and not black hole.
SiCKRAGETV/sickrage-issues#2023
SiCKRAGETV/sickrage-issues#1932
=> Fix KAT and TPB via proxy (need direct client connection, no black hole!)

sickbeard/db.py
SiCKRAGETV/sickrage-issues#2346
=> Revert text factory to may19, until we can fix unicode

sickbeard/logger.py
@miigotu I couldn't not test properly. I got: 
`DEBUG::Thread-53 :: git didn't return newest commit hash`
the logic seems ok. what do you think? No compile errors.
=> Check if SR is updated before submitting an issue

sickbeard/helpers.py
Cause of missing config settings, db, etc on update/restore.
=> Also need zip64 for other methods, and to extract!

gui/slick/interfaces/default/IRC.mako, gui/slick/interfaces/default/apiBuilder.mako, gui/slick/interfaces/default/comingEpisodes.mako, gui/slick/interfaces/default/config.mako, gui/slick/interfaces/default/config_anime.mako, gui/slick/interfaces/default/config_backuprestore.mako, gui/slick/interfaces/default/config_general.mako, gui/slick/interfaces/default/history.mako, gui/slick/interfaces/default/home.mako, gui/slick/interfaces/default/inc_bottom.mako, gui/slick/interfaces/default/inc_top.mako
=> Start converting to mako part 2

gui/slick/interfaces/default/IRC.mako, gui/slick/interfaces/default/comingEpisodes.mako, gui/slick/interfaces/default/errorlogs.mako, gui/slick/interfaces/default/home.mako, gui/slick/interfaces/default/inc_bottom.mako, gui/slick/interfaces/default/inc_top.mako, gui/slick/interfaces/default/manage_episodeStatuses.mako, gui/slick/interfaces/default/restart.mako, gui/slick/interfaces/default/restart_bare.mako, gui/slick/interfaces/default/viewlogs.mako, sickbeard/webserve.py
Some import cleanup, some more work on moving assignments into render for webserve.py
=> Finish manage_episodeStatuses, Finish restart and restart_bare

sickbeard/notifiers/emby.py
Please check the commit, I have limited testing abilities since I do not use emby.
=> Fixing indentation on emby notifier

sickbeard/webserve.py
Needed conversion of webserve.py to mako
=> Mako conversion of webserve.py

sickbeard/metadata/generic.py
```
2015-08-04 03:54:32 WARNING  SHOWQUEUE-REFRESH :: Unable to retrieve image to save in /home/osmc/SickRage/cache/images/thumbnails, skipping
2015-08-04 03:54:31 WARNING  SHOWQUEUE-REFRESH :: Unable to retrieve image to save in /home/osmc/SickRage/cache/images, skipping
2015-08-03 03:48:52 WARNING  SHOWQUEUE-REFRESH :: Unable to retrieve image to save in /home/osmc/SickRage/cache/images/thumbnails, skipping
2015-08-03 03:48:51 WARNING  SHOWQUEUE-REFRESH :: Unable to retrieve image to save in /home/osmc/SickRage/cache/images, skipping
2015-08-02 03:50:08 WARNING  SHOWQUEUE-REFRESH :: Unable to retrieve image to save in /home/osmc/SickRage/cache/images/thumbnails, skipping
2015-08-02 03:50:07 WARNING  SHOWQUEUE-REFRESH :: Unable to retrieve image to save in …
```
=> Display show/episode which image was unable to download

sickbeard/tv.py
Fixes SiCKRAGETV/sickrage-issues/issues/2427
=> Don't accept results for episodes that have not aired yet

sickbeard/common.py
by changing all 264 with (264|265)
=> Added support for support HEVC (x265)

sickbeard/common.py
Reverts SiCKRAGETV/SickRage#2283
=> Revert "Added support for support HEVC (x265)"

sickbeard/versionChecker.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/2091
=> Fix version checker ssl error

gui/slick/interfaces/default/config_notifications.mako, sickbeard/__init__.py, sickbeard/notifiers/tweet.py, sickbeard/webserve.py
Closes SiCKRAGETV/sickrage-issues#542
=> Adds possibility to send tweets via DM as well as normal update

gui/slick/interfaces/default/status.mako, sickbeard/helpers.py, sickbeard/webserve.py
Closes SiCKRAGETV/sickrage-issues#1363
Getting free diskspace in Windows and any python supporting os.statvfs()
=> Adds overview of free diskspace in /home/status

sickbeard/notifiers/emailnotify.py
=> Fixing typo recepients > recipients

sickbeard/providers/nyaatorrents.py
Code has not been evaluated by me, as I don't use nyaa for anything
=> Committing on behalf of @Greg0rz in SiCKRAGETV/sickrage-issues#256

sickbeard/show_queue.py
This is why show queue was taking ages and why it was seeming to be stuck.
=> Don't search backlog on show update! Save episodes from memory to db!

sickbeard/helpers.py
Fixes only checking TV_DOWNLOAD_DIR and failing if not set
=> Corrected faulty filesystem freespace check on non-Windows

gui/slick/interfaces/default/config_general.mako, gui/slick/interfaces/default/config_notifications.mako, gui/slick/interfaces/default/home.mako, gui/slick/interfaces/default/manage_torrents.mako, gui/slick/interfaces/default/status.mako, sickbeard/__init__.py, sickbeard/config.py, sickbeard/dailysearcher.py, sickbeard/show_queue.py, sickbeard/traktChecker.py, sickbeard/webserve.py
=> Remove Trakt Rolling

.gitattributes
So all our favorite editors will pick up.
=> Updating after Cheetah > Mako change

sickbeard/webserve.py
Closes SiCKRAGETV/sickrage-issues#2484
=> Fixes error when saving config

gui/slick/interfaces/default/comingEpisodes.mako
- Adds missing regular expressions
=> Fix for SiCKRAGETV/sickrage-issues#2538

gui/slick/interfaces/default/config_notifications.mako, sickbeard/notifiers/pushover.py
Add option to use to keep sounds 'device specific'
Fixes SiCKRAGETV/sickrage-issues#2529
=> Add option to not forcibly send sound in Pushover

gui/slick/interfaces/default/comingEpisodes.mako, gui/slick/interfaces/default/config_anime.mako, gui/slick/interfaces/default/config_notifications.mako, gui/slick/interfaces/default/config_postProcessing.mako, gui/slick/interfaces/default/config_providers.mako, gui/slick/interfaces/default/config_subtitles.mako, gui/slick/interfaces/default/displayShow.mako, gui/slick/interfaces/default/history.mako, gui/slick/interfaces/default/home.mako, gui/slick/interfaces/default/home_popularShows.mako, gui/slick/interfaces/default/inc_bottom.mako, gui/slick/interfaces/default/inc_top.mako, gui/slick/interfaces/default/manage.mako, gui/slick/interfaces/default/manage_failedDownloads.mako, gui/slick/interfaces/default/restart_bare.mako, gui/slick/interfaces/default/trendingShows.mako, sickbeard/webserve.py
We use Tornado's default v= cache breaker.
This will instruct the browser to cache content until we change commit hash or 10 years, whichever comes first
=> Set up cache control for static content (images)

gui/slick/interfaces/default/comingEpisodes.mako, gui/slick/interfaces/default/config_anime.mako, gui/slick/interfaces/default/config_notifications.mako, gui/slick/interfaces/default/config_postProcessing.mako, gui/slick/interfaces/default/config_providers.mako, gui/slick/interfaces/default/config_subtitles.mako, gui/slick/interfaces/default/displayShow.mako, gui/slick/interfaces/default/history.mako, gui/slick/interfaces/default/home.mako, gui/slick/interfaces/default/home_popularShows.mako, gui/slick/interfaces/default/inc_bottom.mako, gui/slick/interfaces/default/inc_top.mako, gui/slick/interfaces/default/manage.mako, gui/slick/interfaces/default/manage_failedDownloads.mako, gui/slick/interfaces/default/restart_bare.mako, gui/slick/interfaces/default/trendingShows.mako, sickbeard/webserve.py
Reverts SiCKRAGETV/SickRage#2323
Had too many issues, and the large images still dont cache.
=> Revert "Set up cache control for static content (images)"

gui/slick/interfaces/default/displayShow.mako, sickbeard/webapi.py, sickbeard/webserve.py
Still is a 302 redirect for poster and probably network icon, however it is redirecting to a cached image.
=> Let tornado handle etags for browser caching~

sickbeard/common.py, sickbeard/tv.py
@OmgImAlexis Hopefully this fixes it! And this might be a partial contributor to other issues as well. Someone did not implement archived completely, WAY BACK.
=> Add archived for composite status'

sickbeard/subtitles.py, sickbeard/traktChecker.py, sickbeard/versionChecker.py
Obs: Subtitle scheduler has def __init__(self)
https://github.com/SiCKRAGETV/sickrage-issues/issues/2552
=> Add AmActive to schedulers

sickbeard/subtitles.py
@fernandog 
SiCKRAGETV/SickRage/pull/2339
=> Initialize amActive for SubtitlesFinder

sickbeard/clients/deluged_client.py
Removed superfluous code that was duplicating hash extraction.
Cleaned up unused imports & print calls.
=> Fixed up deluge daemon handling of torrents that are already added.

gui/slick/css/print.css, gui/slick/interfaces/default/home.mako, gui/slick/interfaces/default/inc_top.mako
Do not merge yet, as some points still need discussion in https://github.com/SiCKRAGETV/sickrage-issues/issues/2498.
Current status:
=> Fix for SiCKRAGETV/sickrage-issues#2498: Include a print "Shows list" feature

lib/guessit/__init__.py, lib/guessit/__main__.py, lib/guessit/__version__.py, lib/guessit/containers.py, lib/guessit/guess.py, lib/guessit/language.py, lib/guessit/matcher.py, lib/guessit/matchtree.py, lib/guessit/patterns/list.py, lib/guessit/test/episodes.yaml, lib/guessit/test/guessittest.py, lib/guessit/test/movies.yaml, lib/guessit/transfo/guess_date.py, lib/guessit/transfo/guess_episode_info_from_position.py, lib/guessit/transfo/guess_episodes_rexps.py, lib/guessit/transfo/guess_filetype.py, lib/guessit/transfo/guess_language.py, lib/guessit/transfo/guess_movie_title_from_position.py, lib/guessit/transfo/guess_properties.py, lib/guessit/transfo/guess_weak_episodes_rexps.py, lib/guessit/transfo/split_explicit_groups.py, lib/guessit/transfo/split_on_dash.py, lib/guessit/transfo/split_path_components.py
SiCKRAGETV/sickrage-issues/issues/2339
=> Update guessit to f25e1b30c60f334ad378d1146a900797e8f76240

gui/slick/interfaces/default/home.mako
Had to redo my branch as I was accidently working from the wrong dev branch.
=> Fixes SiCKRAGETV/sickrage-issues#2584

gui/slick/interfaces/default/home.mako
This follow  https://github.com/SiCKRAGETV/SickRage/pull/2365
I think this approach is a bit better, as we directly sort what we need, without having to split a string.
=> Sort the appropriate value in the "Downloads" column

gui/slick/css/dark.css
Know issues:
Can you mark as "DO NOT MERGE" until all issues are fixed?
=> Fix CSS after #2336

gui/slick/css/style.css, gui/slick/interfaces/default/comingEpisodes.mako, gui/slick/interfaces/default/displayShow.mako, gui/slick/interfaces/default/history.mako, gui/slick/interfaces/default/home.mako, gui/slick/interfaces/default/inc_defs.mako, gui/slick/interfaces/default/manage.mako, sickbeard/common.py
Squashed SiCKRAGETV/SickRage/pull/2369
=> Vince val more specific quality pills

sickbeard/show_queue.py
Replaces SiCKRAGETV/SickRage/pull/2366
=> Remove show from trakt watchlist that are not on tvdb

sickbeard/exceptions.py, sickbeard/show_queue.py, sickbeard/traktChecker.py, sickbeard/webapi.py, sickbeard/webserve.py
Incomplete, but the better way to do this.
Instead of SiCKRAGETV/SickRage/pull/2277
=> Use show_queue to remove shows

gui/slick/interfaces/default/inc_bottom.mako, gui/slick/interfaces/default/inc_top.mako, sickbeard/webserve.py
@miigotu @MGaetan89 When we can, more of the javascript needs to be moved to files instead of inline and added to the inc_bottom.mako instead of the top as it'll increase performance by loading the files after the page is done rendering. This won't change any functionality.
=> Move submenu js to webserve

lib/guessit/guess.py, lib/guessit/language.py, lib/guessit/test/episodes.yaml, lib/guessit/transfo/guess_properties.py
Helps fix SiCKRAGETV/sickrage-issues#2339
=> Updating guessit to wackou/guessit@8ec4d7b642

lib/guessit/__version__.py, lib/guessit/language.py, lib/guessit/test/episodes.yaml, lib/guessit/transfo/guess_episode_info_from_position.py, lib/guessit/transfo/guess_language.py, lib/guessit/transfo/guess_movie_title_from_position.py
SiCKRAGETV/sickrage-issues#2647
=> Update guessit to 0.11.0 commit 2516111ea7bf910df32d1b0c11a3e8e64490aaab

sickbeard/providers/nextgen.py
A lot of content on nextgen is danish, so adding support for danish characters seems obvious.
=> Add support for non-ASCII chars in search string

sickbeard/clients/deluged_client.py
Also removed some error logging that was duplicating generic.py logging.
General tidying up.
=> Added handling of seed ratio and high priority for new releases.

gui/slick/interfaces/default/history.mako, sickbeard/webserve.py
Fix for https://github.com/SiCKRAGETV/sickrage-issues/issues/2649
=> Fix history limit

gui/slick/css/style.css
https://github.com/SiCKRAGETV/sickrage-issues/issues/2625
I don't know if these were changed by jQuery-UI (the version did not change, so I don't think so) or if it was a manual change (as for Bootstrap), but the design should be fixed now.
=> Override some jQuery-UI values

sickbeard/__init__.py
Fixes SiCKRAGETV/sickrage-issues#2663
=> Fix typo that prevents pushover sound from saving

sickbeard/notifiers/libnotify.py
Fixes SiCKRAGETV/sickrage-issues#2648
=> Change libnotify import. 

.gitignore
Reverts SiCKRAGETV/SickRage#2409
=> Revert "Only keep /cache/images. Delete everything else..."

gui/slick/views/home.mako, sickbeard/helpers.py
It needs to be tested for potential performance issue before being included in `develop`/`master`.
I only have 2 shows with files in my dev environment, so I am not sure about the result.
=> Fix for SiCKRAGETV/sickrage-issues#2578: Add a "Size" column on shows list

gui/slick/views/manage_backlogOverview.mako
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/2673
=> Only cached imports work on the whole file

gui/slick/views/home.mako, sickbeard/webapi.py, sickbeard/webserve.py, sickrage/media/GenericMedia.py, sickrage/media/ShowBanner.py, sickrage/media/ShowFanArt.py, sickrage/media/ShowNetworkLogo.py, sickrage/media/ShowPoster.py
I was already ready to send a PR for this, so it does a bit more than just fixing the loading issue.
Basically, it was because I was comparing string with `is` instead of `==`.
=> Fix images loading

sickbeard/tv.py
Fixes SiCKRAGETV/sickrage-issues#2680 and related
=> Temporarily disable show updates from TVRage since it's down

sickbeard/helpers.py
=> Add tensiontorrent.com to removewords

sickbeard/providers/tntvillage.py
Reverts SiCKRAGETV/SickRage#2457
=> Revert "tntvillage: Fix torrents searching"

gui/slick/views/home.mako
Replaces https://github.com/SiCKRAGETV/SickRage/pull/2454
=> Display "Add anime" after the anime table

sickbeard/providers/hdtorrents.py
Want to check if I'm the only one having this issue
=> Add temp log lines to HDT

gui/slick/views/home.mako
This will be added back in once we work out how to make it not kill loading times. Ref: https://github.com/SiCKRAGETV/sickrage-issues/issues/2723
=> Remove jQuery image loading and size checking

sickrage/show/History.py
Restore subtitles in the history.
Now subtitles are also included in the API.
=> Fix for https://github.com/SiCKRAGETV/sickrage-issues/issues/2719

gui/slick/views/home.mako
Related to https://github.com/SiCKRAGETV/SickRage/pull/2471
=> Removes size column

lib/BeautifulSoup.py, sickbeard/providers/hdtorrents.py
https://github.com/SiCKRAGETV/SickRage/commit/36fefecb06e74219f68ee34f43fd1b37b0565ce1
=> Fix HDT: use bs3 instead of bs4

gui/slick/views/layouts/main.mako, sickbeard/webserve.py
Fixes Confirmation for:
Remove Show
Submit Errors
Trim History
Clear History
=> Fix confirmation dialogues not showing.

SickBeard.py, sickbeard/__init__.py, sickbeard/versionChecker.py
Fills FR SiCKRAGETV/sickrage-issues#2712
=> Adding mako cache cleaner upon startup of new version

sickbeard/versionChecker.py
Currenty mostly used in /contrib
=> Update submodules as well when we update SR

sickbeard/versionChecker.py
https://github.com/SiCKRAGETV/SickRage/pull/2486#issuecomment-139837400
=> Missed space in git submodule command

sickbeard/providers/bitsoup.py
To resolve issue https://github.com/SiCKRAGETV/sickrage-issues/issues/2804
=> BitSoup: Change searchURL to search_string

sickbeard/subtitles.py, sickbeard/tv.py
=> Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/2774

gui/slick/js/new/home.js
Since Sickrage sometimes uses `True` and sometimes uses `1` we can't be sure which one will be present on the meta tag so we need to use an array to check for either of them.
=> Fixes fuzzydates being used & fixes if checks in js

sickbeard/webapi.py, sickbeard/webserve.py, sickrage/show/Show.py, sickrage/show/__init__.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/2567
=> Use common code to delete a show

sickbeard/webapi.py, sickbeard/webserve.py, sickrage/show/Show.py
I also update the delete show logic a bit.
https://github.com/SiCKRAGETV/sickrage-issues/issues/2567
=> Use common code to pause/resume a show

sickrage/show/Show.py
As per https://github.com/SiCKRAGETV/SickRage/pull/2513#issuecomment-140837111 and the following comments.
=> Return exception as error message if deleting a show fails

sickbeard/indexers/test/__init__.py
I guess this ended up here by mistake, as there is a `tests` folder at the root of the project.
=> Remove file

sickbeard/autoPostProcesser.py, sickbeard/blackandwhitelist.py, sickbeard/browser.py, sickbeard/bs4_parser.py, sickbeard/classes.py, sickbeard/common.py, sickbeard/config.py, sickbeard/dailysearcher.py, sickbeard/db.py, sickbeard/encodingKludge.py, sickbeard/event_queue.py, sickbeard/exceptions.py, sickbeard/failedProcessor.py, sickbeard/failed_history.py, sickbeard/generic_queue.py, sickbeard/helpers.py, sickbeard/history.py, sickbeard/image_cache.py, sickbeard/imdbPopular.py, sickbeard/logger.py, sickbeard/name_cache.py, sickbeard/naming.py
Adds missing docstrings / some minor fixes for all files in sickbeard/ up till naming.py
(DO NOT MERGE, will work on other files in same branch)
=> Adds missing docstrings / some minor fixes

sickbeard/providers/tvchaosuk.py
Fix series pack searches (I hope)
No longer needs silly scene exceptions.
Quality is not known for this provider yet, so you must select 'Any' Quality for shows that will use it.
@daveyboy37
=> Make Series packs work for TVChaosUK, Fix episode searches

sickrage/show/Show.py
Fix for https://github.com/SiCKRAGETV/sickrage-issues/issues/2872
=> Use full name of `showQueueScheduler` to delete a show

sickrage/show/ComingEpisodes.py
Fix for https://github.com/SiCKRAGETV/sickrage-issues/issues/846
=> Make coming episodes results mutable

sickbeard/common.py
Get screen size with hachoir, match webdl, bluray, or dvd in filename to get a more accurate quality when guessing.
=> Try to fix SiCKRAGETV/sickrage-issues/issues/2841

gui/slick/js/displayShow.js, gui/slick/views/displayShow.mako
I also added a small feature: when we selected a season in the dropdown, that season is automatically expanded.
=> Fix "Jump to Season* dropdrown

gui/slick/views/config_providers.mako
Ref: https://github.com/SiCKRAGETV/SickRage/pull/2548
Just add some CSS to change the `background-color` to whatever you want.
=> Added public/private class to provider list

gui/slick/css/dark.css, gui/slick/css/style.css, gui/slick/views/config_providers.mako
Add classes to color providers by type: nzb or torrent
Not sure what the colors should be yet, need to test some out.
Will rebase and merge once decided.
=> Add locked icon for private providers, and unlocked icon for public.

sickbeard/providers/xthor.py
add quotes to search string for better results in searching.
=> update xthor add quotes to search string

sickbeard/providers/btdigg.py
@miigotu in order to avoid future "confusion"
=> Add webage url to btdigg

gui/slick/views/home_popularShows.mako, sickbeard/imdbPopular.py
changed code. now it's working
any better way to do this?
=> Don't show 'add' button in imdb popular if user already have the show

gui/slick/css/style.css
The reason for the massive amount of additions and deletion is my editor "fixed" the indenting to use 4 spaces instead of the tab character.
=> Fixes "Snatched (Proper) 1080p WEB-DL" not fitting on a single line

sickbeard/providers/libertalia.py
switch to warning the log level of login unsuccessful
=> libertalia login unsuccessful warning

gui/slick/js/new/home_trendingShows.js, gui/slick/js/new/manage.js, gui/slick/js/new/trendingShows.js, gui/slick/js/new/viewlogs.js, gui/slick/views/home_trendingShows.mako, gui/slick/views/manage.mako, gui/slick/views/trendingShows.mako, gui/slick/views/viewlogs.mako
@MGaetan89 I think table parsing should be moved to a generic file so we don't have duplicates of it, what do you think?
=> Move js and lint

gui/slick/views/config_general.mako
I tried to add a JS tip in "Airdate" column like the episode plot but I couldn't 
Suggestions to the text?
=> Add tip to timezone setting

sickbeard/webapi.py
This is just some changes in the API documentation to make in look better after https://github.com/SiCKRAGETV/SickRage/pull/2581 is merged.
=> Update API documentation

gui/slick/views/history.mako
=> Add more values to history limit

sickbeard/webapi.py
https://github.com/SiCKRAGETV/SickRage/pull/2589#issuecomment-143106205
=> API images fix

sickbeard/providers/fnt.py, sickbeard/providers/freshontv.py, sickbeard/providers/kat.py, sickbeard/providers/morethantv.py, sickbeard/providers/scc.py, sickbeard/providers/scenetime.py, sickbeard/providers/speedcd.py, sickbeard/providers/strike.py, sickbeard/providers/thepiratebay.py, sickbeard/providers/tntvillage.py, sickbeard/providers/torrentbytes.py, sickbeard/providers/torrentleech.py, sickbeard/providers/transmitthenet.py, sickbeard/providers/tvchaosuk.py
Others providers don't have minleed/minseed added to code
=> Add log message about discarded torrent

sickbeard/providers/newznab.py
This will be part of a quick merge to master tonight.
=> Preliminary support for tvdbid search on indexers.

gui/slick/views/config_postProcessing.mako
Change class from 'icon-info-sign' to 'glyphicon glyphicon-info-sign'.
=> Fix info icon on custom naming legend

sickbeard/common.py
Fix leak when testing "if int(status) in statusStrings"
=> Fix not being able to set status to compound archived qualities

sickbeard/tv.py
And possibly fixes the "Could not refresh subtitles" problem.
=> Fix subfolder not created for new shows

gui/slick/js/addShowOptions.js, gui/slick/views/inc_addShowOptions.mako, sickbeard/__init__.py, sickbeard/show_queue.py, sickbeard/traktChecker.py, sickbeard/webapi.py, sickbeard/webserve.py
Fixes SiCKRAGETV/sickrage-issues#495
=> Added 'archive on first match' option when adding a show

sickbeard/subtitles.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/2774
=> Fixes subtitle recognition with sigle language

gui/slick/js/apibuilder.js, gui/slick/views/apiBuilder.mako
@MGaetan89 next time you make changes to this could you move everything into the body so we validate HTML spec. Nothing should be outside of it.
=> Lint new API Builder

gui/slick/js/qualityChooser.js
@OmgImAlexis Please do not lint this file because it breaks functionality
=> Fixed qualityChooser not expanding custom qualities fields

sickbeard/webapi.py
Fixes SiCKRAGETV/sickrage-issues#2991
=> Missing import in webapi, fixes SiCKRAGETV/sickrage-issues#2991

lib/lockfile/__init__.py, lib/lockfile/linklockfile.py, lib/lockfile/mkdirlockfile.py, lib/lockfile/pidlockfile.py, lib/lockfile/sqlitelockfile.py, lib/lockfile/symlinklockfile.py
Update lockfile to get the latest fixes.
=> Update pylockfile to 4a7a20d91c44d2be6396be5fc64d27b0b5afa4e2

sickbeard/subtitles.py
Fixes SiCKRAGETV/sickrage-issues/issues/1645
=> error->warning for not enough enabled services in subtitles.

gui/slick/views/displayShow.mako
SiCKRAGETV/sickrage-issues/issues/3002
=> Fixes displayShow date format

sickbeard/providers/extratorrent.py, sickbeard/providers/generic.py
=> Finalize extratorrent provider

sickbeard/providers/fnt.py
Check for auth was missing in _doSearch
=> Add missing check for auth to _doSearch

sickbeard/providers/thepiratebay.py
Fixes SiCKRAGETV/sickrage-issues/issues/2947
=> Tempfix TPB (cloudflare)

sickbeard/processTV.py
=> Also ignore thumbnail dirs on syno when processing a folder

sickbeard/subtitles.py
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/3024, https://github.com/SiCKRAGETV/sickrage-issues/issues/2936, https://github.com/SiCKRAGETV/sickrage-issues/issues/2874. Probably also https://github.com/SiCKRAGETV/sickrage-issues/issues/2965.
Credits to @Diaoul for the original code.
=> Use enzyme to detect embedded subtitles instead of subliminal

sickbeard/webapi.py
Fix for https://github.com/SiCKRAGETV/sickrage-issues/issues/2988
I checked the default value of boolean parameter and fixed the `_check_param_type` method.
=> Fix issue #2988

sickbeard/providers/extratorrent.py
=> Fix for when seeders/Leechers is "---" instead of a number

gui/slick/views/config_postProcessing.mako, sickbeard/webserve.py
@jorgb
create_missing_show_dirs
add_shows_wo_dir
=> Add missing config settings to UI

sickbeard/common.py
as suggested here http://feathub.com/SiCKRAGETV/SickRage/+9
DVDMux ,BDMux are the same as a DVDRip and BDRip ,but with muxed/embebed subs
=> Add DVDMux & BDMux as valid SDDVD qualities

sickbeard/webserve.py
This fixes SiCKRAGETV/sickrage-issues#2852.
=> Improve the way quality class is generated

sickbeard/versionChecker.py
@miigotu this way instead of return 'error' we return the error message.
=> Fix SiCKRAGETV/sickrage-issues/issues/2905

sickbeard/common.py
=> Add TVMux ,WebMux and BRMux

gui/slick/views/comingEpisodes.mako
@MGaetan89 agree? I checked with ShowsRage
=> Change comingEpisodes keys to be aligned with API

sickbeard/versionChecker.py, sickbeard/webserve.py
=> Check if is safe to update when user click "update" in UI

gui/slick/views/layouts/main.mako
In some cases, two class attriutes were being added and the active class
wasn't being picked up. Also added topmenu detection for system menu.
Also gets rid of extraneous spaces.
=> Fixes class attribute on navbar items

gui/slick/views/layouts/main.mako
Clicking the dropdown will take you to the most logical option on that
menu instead of just toggling the menu open/closed.
=> Make navbar dropdowns clickable links

gui/slick/views/config_general.mako, gui/slick/views/config_postProcessing.mako, sickbeard/tv.py
>>> import sys;sys.path.insert(1,'lib');from sickbeard import common
>>> status = 6404
>>> print common.statusStrings[status]
Downloaded (1080p WEB-DL)
>>> oldStatus, oldQuality = common.Quality.splitCompositeStatus(status)
>>> new_status = common.Quality.compositeStatus(common.ARCHIVED, oldQuality)
>>> print new_status
6406
>>> print common.statusStrings[new_status]
Archived (1080p WEB-DL)
=> Fixes SiCKRAGETV/sickrage-issues/issues/3039

sickbeard/webserve.py
=> Fix SKIP_REMOVED_FILES not saving

sickbeard/subtitles.py, sickbeard/tv.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/3024 and https://github.com/SiCKRAGETV/sickrage-issues/issues/3049
=> Fixes #3049 and #3024

sickbeard/providers/tntvillage.py, sickbeard/providers/torrentbytes.py, sickbeard/providers/torrentleech.py, sickbeard/providers/tvchaosuk.py
Now using correct title of torrent
=> Fixes SiCKRAGETV/sickrage-issues/issues/3056

gui/slick/js/new/comingEpisodes.js, gui/slick/js/new/errorlogs.js, gui/slick/js/new/home_recommendedShows.js, gui/slick/js/new/trendingShows.js, gui/slick/js/new/viewlogs.js
Since we want to move to either using sockets or ajax there's no point in keeping these even for now as they cause more harm than good.
=> Removed auto refresh

gui/slick/views/comingEpisodes.mako, gui/slick/views/config_subtitles.mako
Nothing being used was removed, just indented a few things and removed some of the old commented code I had from testing.
=> General code cleanup

gui/slick/js/new/meta.js, gui/slick/js/script.js, gui/slick/views/comingEpisodes.mako, gui/slick/views/history.mako, gui/slick/views/home.mako, gui/slick/views/home_addExistingShow.mako, gui/slick/views/home_recommendedShows.mako, gui/slick/views/home_trendingShows.mako, gui/slick/views/layouts/main.mako
I've also moved the inline js from `main.mako` to the top of `script.js`.
=> Deduplicated metas

.gitignore, SickBeard.py, sickbeard/__init__.py
Reverts SiCKRAGETV/SickRage#2561
@WebSpider first try it would not use my config/db.
```
dusted@PC:~/Projects/SickRage: ./SickBeard.py
Unable to find '/home/dusted/Projects/SickRage/data/config.ini' , all settings will be default!
^C04:39:04 INFO::MAIN :: Signal 2 caught, saving and exiting...
04:39:07 INFO::MAIN :: New API generated
Starting up SickRage develop from /home/dusted/Projects/SickRage/data/config.ini
04:39:07 INFO::TORNADO :: Starting SickRage on http://0.0.0.0:8081/
```
=> Revert "Change default DATA_DIR to PROG_DIR/data"

sickbeard/providers/extratorrent.py
@duramato I will rebase this before merge but here you can see what I mean.
=> Duramato patch 2

sickbeard/versionChecker.py, sickbeard/webserve.py
Reverts SiCKRAGETV/SickRage#2668
=> Revert "Check if is safe to update when user click "update" in UI"

gui/slick/js/config.js
I'm pretty sure this was only removed as my global .gitignore fucked up!
=> Added config.js back

sickbeard/providers/transmitthenet.py
-Changed category from 1 to 0 so that all categories (1,2,3,4)(TV only tracker) are searched
-Replaced full stop in title with a space as searches with full stop were producing no results
-General tidy up
=> TTN: Fix category & search_string

gui/slick/views/displayShow.mako
Still needs to be tested but I think this is correct, @miigotu can you confirm?
=> Fixes SiCKRAGETV/sickrage-issues/issues/3007

sickbeard/show_queue.py
=> Fixes SiCKRAGETV/sickrage-issues/issues/2368

gui/slick/css/style.css, gui/slick/views/layouts/main.mako
This hopefully resolves some UI and mobile/touch issues with #2674.
=> Create split navbar dropdowns

sickbeard/webserve.py
The Add Shows, Manual Post-Processing, and various update buttons are
now redundant since the Shows navbar button is a dropdown. The update
and torrent buttons are on the Manage dropdown.
=> Remove redundant buttons from various pages

gui/slick/views/layouts/main.mako
=> Change default log menu href

gui/slick/views/layouts/main.mako, sickbeard/__init__.py, sickbeard/versionChecker.py, sickbeard/webserve.py
- Move News, IRC, and Support to Tools menu
- Reorganize the menu a bit and add a couple dividers
- Notify user when new news exists
=> News notify and tools menu

sickbeard/webserve.py
Forgot to do this in PR #2717.
=> Fix the topmenu for News and IRC

gui/slick/views/displayShow.mako, gui/slick/views/manage_backlogOverview.mako
@miigotu
history don't need change AFAI checked
=> Respect timezone setting in displayShow, backlogOverview

gui/slick/views/displayShow.mako, gui/slick/views/manage_backlogOverview.mako
Reverts SiCKRAGETV/SickRage#2721
=> Revert "Respect timezone setting in displayShow, backlogOverview"

gui/slick/views/errorlogs.mako, gui/slick/views/layouts/main.mako, sickbeard/classes.py, sickbeard/logger.py, sickbeard/webserve.py
This also removes PageTemplate.arguments['menu'] which I don't think is being used anymore.
=> Render a badge with error count on Logs & Errors

sickbeard/providers/t411.py
Too much spam on the warning log view..
=> Clean warning logs for t411

.gitignore
Fixes SiCKRAGETV/sickrage-issues/issues/3109
=> Fixup .gitignore

sickbeard/webserve.py
Closes SiCKRAGETV/sickrage-issues#3122:
- Show "Clear Errors" and "Submit Errors" on "View Errors" page.
- Show "Clear Warnings" on "View Warnings" page.
- Don't show any submenu on "View Log" page.
=> Only show appropriate error submenus

gui/slick/views/layouts/main.mako
sbLogin is True when authentication is disabled.
This should close SiCKRAGETV/sickrage-issues#2667.
=> Don't show logout option when auth is disabled

gui/slick/css/style.css
Requested by @OmgImAlexis in SiCKRAGETV/SickRage#2713.
=> Remove line between text and caret for split items

gui/slick/js/new/comingEpisodes.js, gui/slick/views/comingEpisodes.mako
Ref: https://github.com/SiCKRAGETV/SickRage/pull/2766
=> Fix comingEpisodes sorting

sickbeard/tv.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/3176
=> Fixes SiCKRAGETV/sickrage-issues/issues/3176

gui/slick/views/errorlogs.mako
Allows scrolling on error pages
=> Allows scrolling on error pages

sickbeard/providers/torrentproject.py
Error: https://www.irccloud.com/pastebin/bNP6RvhP/
@miigotu ok?
=> Fix Torrentproject: ValueError: too many values to unpack

sickbeard/logger.py
@miigotu
if is ok we can cherry pick to master
=> Avoid submit mutliple ascii errors

sickbeard/providers/rarbg.py
=> Parse size from RARBG results

gui/slick/js/apibuilder.js, gui/slick/views/apiBuilder.mako
Added srRoot to apibuilder otherwise it doesn't work at all if you've got a web_root set.
=> Added srRoot to apibuilder

sickbeard/providers/extratorrent.py, sickbeard/providers/kat.py, sickbeard/providers/thepiratebay.py
Help debug this:
https://gist.github.com/OmgImAlexis/cda23169e014b6e30ec5
@miigotu @OmgImAlexis
=> Add "searchURL" log message to KAT/TPB

sickbeard/logger.py
=> Filter another recurrent issue

sickbeard/tv.py
@OmgImAlexis i think this will help you
@miigotu
=> Fix some of the log messages from tv.py

sickbeard/traktChecker.py
...TraktChecker
@miigotu 
Fixes tons of this errors in my logs:
```
AA    raise ConnectionError(err, request=request)
AA  File "/home/osmc/SickRage/lib/requests/adapters.py", line 415, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/home/osmc/SickRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/home/osmc/SickRage/lib/requests/sessions.py", line 464, in request
AA    data=json.dumps(data) if data else [], verify=self.verify)
AA  File "/home/osmc/SickRage/lib/libtrakt/trakt.py", line 85, in traktRequest
AATraceback (most recent call last):
```
=> Add try|except for trakt_api.traktRequest and fix log messages in 

sickbeard/providers/extratorrent.py, sickbeard/providers/kat.py
@miigotu should we run search_tests everytime as travis don't run?
=> Fix SiCKRAGETV/sickrage-issues/issues/3223

sickbeard/providers/iptorrents.py
=> Fixes SiCKRAGETV/sickrage-issues/issues/3215

sickbeard/webapi.py
Fix https://github.com/SiCKRAGETV/sickrage-issues/issues/3204
=> Fix boolean values in API

sickbeard/providers/fnt.py
@miigotu
File from: https://github.com/SiCKRAGETV/sickrage-issues/issues/3231#issuecomment-146983582
http://pastebin.com/kAQG2rpc
=> Fix SiCKRAGETV/sickrage-issues/issues/3231

sickbeard/helpers.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/3167
@miigotu ok?
I converted all errors to warning. Agree?
=> Check sockets timeout and fix log messages

lib/subliminal/__init__.py, lib/subliminal/api.py, lib/subliminal/cache.py, lib/subliminal/cli.py, lib/subliminal/converters/addic7ed.py, lib/subliminal/converters/tvsubtitles.py, lib/subliminal/exceptions.py, lib/subliminal/providers/__init__.py, lib/subliminal/providers/addic7ed.py, lib/subliminal/providers/opensubtitles.py, lib/subliminal/providers/podnapisi.py, lib/subliminal/providers/thesubdb.py, lib/subliminal/providers/tvsubtitles.py, lib/subliminal/score.py, lib/subliminal/subtitle.py, lib/subliminal/video.py, sickbeard/postProcessor.py, sickbeard/subtitles.py, sickbeard/tv.py
This PR brings a few important changes:
- Subliminal updated to version 1.0.1
- Performance has been dramatically improved! Now the video file is scanned 1 time at most.
- The most important subtitle functions are now located in subtitles.py
- Subtitles will be refreshed now, before they are downloaded (avoids unnecessary download attempts)
- Added support for alpha3 country codes (e.g. "eng")
- Overall improvement of code logic (e.g. embedded subtitles are only being searched for, if desired)
=> Update sublimnal to 1.0.1, subtitle logic in subtitles.py, much more

sickbeard/providers/nyaatorrents.py
=> Fix SiCKRAGETV/sickrage-issues/issues/3242

lib/xmltodict.py
Reverts SiCKRAGETV/SickRage#2683
=> Revert "Update xmltodict to v 0.9.2"

lib/xmltodict.py, sickbeard/providers/extratorrent.py, sickbeard/providers/kat.py
Fixes SiCKRAGETV/sickrage-issues#3240
=> Hotfix xmltodict issue

sickbeard/common.py, sickbeard/image_cache.py
Fixes SiCKRAGETV/sickrage-issues/issues/2547
=> Disable logging with print in hachoir_core so pythonw.exe isnt failing.

sickbeard/providers/nyaatorrents.py
Adds setting to allow only Trusted results
Adds minseed/minleech setting
Adds size to the result
Adds sorting results by seeds
Fixes search string types to conform with our provider template
Fixes SiCKRAGETV/sickrage-issues/issues/3246
=> Fix NyaaTorrents

gui/slick/views/config_providers.mako, sickbeard/__init__.py, sickbeard/providers/tntvillage.py, sickbeard/webserve.py
As Suggested here: http://feathub.com/SiCKRAGETV/SickRage/+7
=> Add option to only download english releases on TNTVillage

sickbeard/webserve.py
=> Fix SiCKRAGETV/sickrage-issues/issues/3248

sickbeard/postProcessor.py
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/3252
=> Check that the file being processed exists after unrar.

sickbeard/postProcessor.py
@miigotu today PP stops if something goes wrong with notifications
https://github.com/SiCKRAGETV/sickrage-issues/issues/3254
=> Dont stop PP if any notifications fails

sickbeard/providers/hdbits.py
=> Fix SiCKRAGETV/sickrage-issues/issues/3229

sickbeard/providers/hdbits.py
@miigotu the other was hotfixed too?
=> Hotfix hdbits

sickbeard/webserve.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/3262
=> Change ' Refusing to change status of' to WARNING

sickbeard/processTV.py
Fixes SiCKRAGETV/sickrage-issues/issues/3271
=> Don't WARN about miseed sync files on PP.

sickbeard/helpers.py
=> Fixes SiCKRAGETV/sickrage-issues/issues/3274

sickbeard/postProcessor.py
Changes all log messages that return false to WARNING. So user can know why PP failed
@OmgImAlexis is this ok for you?
=> Fix SiCKRAGETV/sickrage-issues/issues/3219

sickbeard/helpers.py
=> Handle ConnectionError

sickbeard/helpers.py
Reverts SiCKRAGETV/SickRage#2868
=> Revert "Handle ConnectionError"

sickbeard/clients/generic.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/1735
=> Change "Authentication Failed" to warning

sickbeard/tv.py
=> Fix SiCKRAGETV/sickrage-issues/issues/3296

sickbeard/webserve.py
=> Fix SiCKRAGETV/sickrage-issues/issues/3297

sickbeard/providers/hdtorrents.py
@miigotu 
it shows "The server made a boo boo, please try later" with 200 code
=> Try to fix HDT 503 error

sickbeard/providers/nextgen.py
@Jopand Thanks for the html, can you test this out?
=> Add size parsing and freeleech option for nextgen

sickbeard/notifiers/plex.py
=> Fix SiCKRAGETV/sickrage-issues/issues/3286

sickbeard/scene_exceptions.py
convert warning and error to debug
=> Fix SiCKRAGETV/sickrage-issues/issues/2383

sickbeard/tv.py
=> Fix SiCKRAGETV/sickrage-issues/issues/3319

sickbeard/providers/tntvillage.py
@miigot my fixup script did a mess in the other PR...
=> Fix SiCKRAGETV/sickrage-issues/issues/3177

gui/slick/views/errorlogs.mako
It's only warning logs. not errors
=> No point show Logs & Errors [WARNING] when log show only warnings

sickbeard/notifiers/plex.py
Reverts SiCKRAGETV/SickRage#2886
=> Revert "Fix SiCKRAGETV/sickrage-issues/issues/3286"

sickbeard/metadata/generic.py, sickbeard/metadata/kodi_12plus.py, sickbeard/metadata/mede8er.py, sickbeard/metadata/mediabrowser.py, sickbeard/metadata/tivo.py, sickbeard/metadata/wdtv.py
fix actors in mede8er, mediabrowser, tivo, wdtv episode xml, include guest stars
dont create nodes if there is no data to put in them
Dont always check is None or not None, otherwise empty strings is a True
=> Clean up, fix, and improve metadata creation for all metadata types

sickbeard/providers/torrentproject.py
@miigotu & @fernandog this is intended to be a temp solution until a better one can be done...
BUT it cannot continue as it is now...
=> Temp Solution for SR DDOSing TorrentProject

sickbeard/providers/extratorrent.py
@miigotu 
why we need .strip() ?
=> Fix SiCKRAGETV/sickrage-issues/issues/3357

sickbeard/providers/hdtorrents.py
HD-Torrents has some invalid html on the page with search results. Using
the default html parser wasn't returning the correct data. Substituted
it with html5 parser to fix the problem.
P.S. I've also created another PR with a different fix to that issue. Not sure which one would you prefere.
=> Fix SiCKRAGETV/sickrage-issues/issues/3347

lib/tvdb_api/tvdb_api.py, sickbeard/show_queue.py
=> Fix SiCKRAGETV/sickrage-issues/issues/3370 traceback

sickbeard/subtitles.py
https://github.com/SiCKRAGETV/SickRage/pull/2894
=> Should fix #2894

sickbeard/common.py
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/3287
=> Add WebHD quality detection

sickbeard/postProcessor.py, sickbeard/processTV.py
Attempt to fix https://github.com/SiCKRAGETV/sickrage-issues/issues/3330
=> Ignore .AppleDouble

gui/slick/views/inc_qualityChooser.mako
Fix for alignment issue in @fernandog last comment for pull request #2911 .
=> Fix custom quality alignment in Edit Show

gui/slick/views/status.mako, sickbeard/helpers.py, sickbeard/webapi.py, sickbeard/webserve.py
Remove dupe code
Use the same method call in webapi
Fixes https://github.com/SiCKRAGETV/SickRage/pull/2930
=> Display free space in human readable numbers

gui/slick/views/config_postProcessing.mako, sickbeard/__init__.py, sickbeard/tv.py, sickbeard/webserve.py
http://feathub.com/SiCKRAGETV/SickRage/+223
SiCKRAGETV/sickrage-issues/issues/3402
Defaults to 'network'
=> Let user choose which timezone to timestamp file

sickbeard/providers/alpharatio.py, sickbeard/providers/cpasbien.py, sickbeard/providers/generic.py, sickbeard/providers/hdtorrents.py, sickbeard/providers/morethantv.py, sickbeard/providers/rarbg.py, sickbeard/providers/speedcd.py, sickbeard/providers/tntvillage.py, sickbeard/providers/torrentbytes.py, sickbeard/providers/torrentleech.py
If torrent provider doesnt support | search, override self.proper_strings with a list of terms
Small cleanup in general.TorrentProvider.findPropers and _clean_title_from_provider
=> Fix HDTorrents findPropers and others.

gui/slick/views/config_search.mako, sickbeard/__init__.py, sickbeard/show_name_helpers.py, sickbeard/webserve.py
In collaboration with @medariox 
https://github.com/SiCKRAGETV/sickrage-issues/issues/3401
=> Allow user to Ignore subbed releases based on language names. Used to be hardcoded

sickbeard/helpers.py
Added `_remove_file_failed(filename)` after exception
=> Fix missing code when exception and pylint

sickbeard/tv.py
=> Fix typo in log message

readme.md
@fernandog & @miigotu is this ok with you guys?
=> Add TorrentProject link

sickbeard/providers/rarbg.py
Seems like refreshing RARBG's cache every 5 minutes is a bit of overkill, no?
=> Upped RARBG's cache checking interval to 10min

sickbeard/providers/scc.py
@fernandog size added to SCC provider
=> Add size to SCC

gui/slick/views/config_subtitles.mako, sickbeard/webserve.py
Adds the necessary mako/html to set login details for subtitle providers that need it.
=> Add login fields for opensubtitles, addic7ed, and legendas.tv

sickbeard/providers/extratorrent.py, sickbeard/providers/kat.py
=> Fix SiCKRAGETV/sickrage-issues/issues/3418

sickbeard/providers/extratorrent.py, sickbeard/providers/kat.py
=> Fix SiCKRAGETV/sickrage-issues/issues/3418 

sickbeard/helpers.py
=> Change line from error to warning

sickbeard/providers/torrentproject.py
=> Handle server maintenance mode on TorrentProject

sickbeard/providers/generic.py
=> We are not checking for propers when snached_best

sickbeard/providers/torrentbytes.py
- Fixed no results detection for Torrentbytes
- Added torrent size parsing for Torrentbytes
=> Torrentbytes provider fixes

sickbeard/providers/torrentbytes.py
Added support for freeleech only torrents to Torrentbytes
=> Added support for freeleech only torrents to Torrentbytes

sickbeard/providers/hdtorrents.py
@miigotu ok?
From website: Carnivàle S02 1080p WEB-DL DD5.1 H.264-BS
```
DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: Attempting to add item to cache: Carniv%C3%A0le.S01.1080p.WEB-DL.DD5.1.H.264-BS
DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: Unable to parse the filename Carniv%C3%A0le.S02.1080p.WEB-DL.DD5.1.H.264-BS into
Also H*s.R*.S01E05.The.Lion%27s.Den.1080p.WEB-DL.DD5.1.H.264-Oosh
=> Try to fix encode/decode in HDT title

sickbeard/providers/thepiratebay.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/3376
=> Temporary change TPB URL

sickbeard/providers/hdtorrents.py
=> Fix HDT AttributeError

sickbeard/providers/morethantv.py
The search there doesn't like brackets.
=> Fixed MTV provider specific issue with search

sickbeard/providers/btdigg.py
=> Add Ratio to BTDigg

sickbeard/providers/morethantv.py
Fixed session timeout issues
Removed freeleech configuration
Added torrent size parsing
=> MTV provider fixes/improvements

gui/slick/views/manage_massEdit.mako, sickbeard/webserve.py
@miigotu I also added "&nbsp" to align the folders names
From: /media
To:__/media
**Screenshot:**
=> Display show names while massEditing

gui/slick/views/displayShow.mako, gui/slick/views/manage.mako, gui/slick/views/manage_massEdit.mako
=> Fix Season folders

readme.md
Fix link to rarbg from readme :)
=> Fix link to rarbg from readme :)

sickbeard/logger.py
@SiCKRAGETV/moderators 
I commented the test strings
Mako errors were missing ".*" in the beginning of the string
=> Fix issue filter - prevent issue SPAM

sickbeard/clients/rtorrent_client.py
Fixes https://github.com/SiCKRAGETV/SickRage/pull/3004
=> Do not make torrent labels lower case for rtorrent client

sickbeard/providers/pretome.py
=> There isnt any Freelech torrents on tracker nor implementation

sickbeard/network_timezones.py
@labrys did you try this change without the 1970 check? Please try this (and remove the 1970 check from the template). Also try with the 1970 check to see if this is safe to merge for me please, I can't be asked to install windows any time soon =P/
I'll wait until I hear some reports before merging this.
=> Use tzwinlocal for sb_timezone on windows.

sickbeard/processTV.py
@miigotu I'm not sure if this is correct but had some issues without this fix. Please review
=> Check scene exceptions while PostProcessing

sickbeard/providers/hdtorrents.py
=> Replacing tabs with spaces before giving data to soup.

sickbeard/network_timezones.py, sickbeard/tv.py
=> Need to convert from datetime to ordinal and make sure is > 0! 

sickbeard/notifiers/freemobile.py, sickbeard/webserve.py
Hella linting (much more to go in webserve)
Need to use rh instead of self.arguments soon to clean up the page template calss
=> Fix mako cache bug

sickbeard/versionChecker.py
Lint versionChecker
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/2089
=> Make sure news var is defined before finditer on it.

gui/slick/js/browser.js, gui/slick/js/new/config_search.js, sickbeard/webserve.py
- fix a JS error on search settings screen
- don't let the browser cache notifications or directories, so we don't receive endless notifications or get stuck in an out of date directory
- fix small bug where using autocomplete and then the file browser left your values out of sync
There are still some styling problems with the autocomplete (it's all white on IE), but this should be a bit less wonky now.
=> fix several front end bugs with initial setup

sickbeard/tv.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/2258
=> wantEpisode was totally broken (may partially still be)

gui/slick/views/editShow.mako
Fixes issue https://github.com/SiCKRAGETV/sickrage-issues/issues/3491
=> Fix issue #3491

sickbeard/postProcessor.py
Fix call to subtitles.wantedLanguages when subtitles was actually a boolean param name(this killed PP!)
Fix https://github.com/SiCKRAGETV/sickrage-issues/issues/3527
=> Lint postProcessor

sickbeard/name_parser/regexes.py, tests/name_parser_tests.py, tests/test_lib.py
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/3544
=> Remove roman numberal matching from "no season" regexes

sickbeard/metadata/__init__.py, sickbeard/metadata/generic.py, sickbeard/metadata/kodi.py, sickbeard/metadata/kodi_12plus.py, sickbeard/metadata/mede8er.py, sickbeard/metadata/mediabrowser.py, sickbeard/metadata/ps3.py, sickbeard/metadata/tivo.py, sickbeard/metadata/wdtv.py
Don't use ek to open files, it returns a unicode object and you cant close the file!
=> Clean up metadata providers a bit more.

sickbeard/__init__.py
=> Lint sickbeard/__init__.py

gui/slick/views/home.mako, sickbeard/webserve.py
Move SQL out of home.mako. Replaces #2635
=> Fix show download statistics (downloaded, snatched, totals) cache issue

sickbeard/providers/cpasbien.py
=> Update CPasbian URL

sickbeard/providers/newpct.py
=> Added quality string to newpct (rebased for @CristianBB)

sickbeard/blackandwhitelist.py
- c4cc2ea PEP 0008: Convert membership test from `not x in y` to `x not in y` 
- 1ae38ce PEP 0257: Convert docstrings to triple quoted docstrings 
- 272eaf4 PEP 0008: Add blank lines for consistency 
- 50ed65c PEP 0263: Add encoding declaration
=> Update blackandwhitelist.py for PEPs 8, 257, and 263

sickbeard/traktChecker.py
- d7202f5 PEP 8: Convert membership test from 'not x in y' to 'x not in y' 	
- e6db3e3 PEP 8: Add missing whitespace around operators and removed excess 	
- 5315277 PEP 8: Add and remove blank lines for consistency 	
- b0f531c PEP 8: Fix under-indented continuation lines 	
- 5d77186 PEP 263: Add encoding declaration 	
- 98d2dfb Remove redundant parentheses
=> Update traktChecker.py for PEPs 8, 263

sickbeard/helpers.py
- c12733b PEP 0008: Convert membership test from 'not x in y' to 'x not in y'	
- a9ff03a PEP 0008: Convert None comparisons from operators to 'is / is not None'	
- 5d9cbdf PEP 0008: Convert lambda expression to a def
- a6cb625 Streamline datetime call for backup file time-stamping	
- b5333d8 PEP 0008: Add missing whitespace around operators and removed excess	
- 8cd170c PEP 0008: Fix indentation	
- 0fcb652 PEP 0257: Convert docstrings to triple double-quoted docstrings	
- 59db3d1 PEP 0263: Add encoding declaration	
- 8d68fb9 Remove redundant parentheses
=> Update helpers.py for PEPs 8, 257 and 263 and streamline datetime call

sickbeard/webapi.py
@MGaetan the inheritance chain is hella broken in webapi, we need some major changes
=> Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/3569

sickbeard/webserve.py
- f9a880c PEP 0008: Change deprecated '.has_key()' to 'in'	
- 81de546 PEP 0008: Convert comparisons	
- 2a15eb8 PEP 0203: Replace assignment with augmented assignment	
- d87ef3d Streamline dict and list creation	
- a4bf5d0 PEP 0008: Add/remove lines and whitespace for consistency
- daae720 PEP 0257: Convert docstrings to triple double-quoted docstrings	
- 3f2d776 PEP 0263: Add encoding declaration	
- 27d1c36 Remove redundant parentheses
=> Update webserve.py for PEPs 8, 203, 257 and 263 and streamline dict/list creation

sickbeard/clients/__init__.py
https://support.cloudflare.com/hc/en-us/sections/200820298-Error-Pages
=> Add missing CF error codes - fix SiCKRAGETV/sickrage-issues/issues/3577

sickbeard/sab.py
=> Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/3580

gui/slick/js/configSearch.js, gui/slick/views/config_search.mako, sickbeard/__init__.py, sickbeard/clients/__init__.py, sickbeard/clients/mlnet_client.py
These changes add MLDonkey (http://mldonkey.sourceforge.net) torrent client to SickRage with basic functions. It only has download functionality. No priority handling or option to start downloads as paused.
=> Added MLDonkey basic client

sickbeard/providers/tntvillage.py
- f273b45 PEP 0008: Convert lambda expression to a def	
- ea44a79 PEP 0008: Add and remove whitespace and blank lines	
- 73e3203 PEP 0263: Add encoding declaration
=> Update tntvillage.py for PEPs 8 and 263

sickbeard/clients/deluge_client.py
- ca2b8a0 PEP 8: Convert None comparisons from operators to 'is / is not None'	
- 3fdb89e PEP 263: Add encoding declaration	
- 13794b2 PEP 8: Remove blank lines for consistency
=> Update deulge_client.py for PEPs 8 and 263

sickbeard/clients/qbittorrent_client.py
- 023c21c PEP 0008: Add and remove whitespace and blank lines	
- 6fdc535 PEP 0263: Add encoding declaration
=> Update rtorrent client for PEPs 8 and 263

sickbeard/clients/mlnet_client.py
- 5074c1b PEP 0008: Add and remove whitespace and blank lines	
- 7a556fb PEP 0263: Add encoding declaration
=> Update mlnet_client.py for PEPs 8 and 263

sickbeard/clients/generic.py
- 627d096 PEP 0008: Add blank lines for consistency	
- 214b274 PEP 0263: Add encoding declaration
=> Update clients/generic.py for PEPs 8 and 263

sickbeard/clients/download_station_client.py
- f5c9e75 PEP 0008: Add and remove whitespace and blank lines	
- e09c239 PEP 0263: Add encoding declaration
=> Update download_station_client.py for PEPs 8 and 263

sickbeard/clients/deluged_client.py
- fc62243 Combine duplicate conditional check	
- 306e128 PEP 0008: Add and remove blank lines for consistency	
- 3020f6c PEP 0263: Add encoding declaration
=> Update deluged_client.py for PEPs 8 and 263 and streamline conditional

sickbeard/databases/cache_db.py
- cd91907 PEP 0008: Add and remove blank lines for consistency	
- 49af8d2 PEP 0263: Add encoding declaration
=> Update cache_db.py for PEPs 8 and 263

sickbeard/clients/transmission_client.py
- 4767c90 PEP 0203: Replace assignment with augmented assignment	
- 3ac9dd8 PEP 0263: Add encoding declaration
=> Update transmission_client.py for PEPs 203 and 263

sickbeard/databases/mainDB.py
- 48c5c76 PEP 0008: Convert None comparisons from operators to 'is / is not None'	
- 8e1a17c PEP 0008: Convert membership test from 'not x in y' to 'x not in y'	
- e1d2e95 PEP 0203: Replace assignment with augmented assignment	
- 8589490 PEP 0203: Replace list creation with list literal	
- de1cae3 PEP 0008: Fix indentation and add/remove blank lines for consistency	
- d87efd9 PEP 0263: Add encoding declaration	
- 3e0c7cc Remove redundant parentheses	
- 0bee383 Add a todo for correcting spelling of compound
=> Update maindb.py for PEPs 8, 203 and 263

sickbeard/indexers/indexer_config.py
- 251493f PEP 203: Replace dict creation with dict literal
- 7f6c151 PEP 263: Add encoding declaration
=> Update indexers_config.py for PEPs 203 and 263

sickbeard/metadata/ps3.py
- bce75e5 Remove redundant parentheses	
- ef71f19 PEP 0263: Add encoding declaration
=> Update ps3.py for PEP 263

sickbeard/metadata/helpers.py
- e51ec7a PEP 0008: Remove unused variable	
- 922f763 PEP 0008: Convert None comparisons from operators to 'is / is not None'
- 5c98750 PEP 0008: Add and remove whitespace and blank lines	
- 9862eba PEP 0263: Add encoding declaration
=> Update helpers.py for PEPs 8 and 263

sickbeard/metadata/generic.py
- 4b1d6a0 Remove unreachable code	
- 0111c52 PEP 0008: Refactor variables that shadow built-in names	
- 3257c71 PEP 0008: Convert None comparisons from operators to 'is / is not None'	
- cc473f8 PEP 0008: Add and remove blank lines for consistency	
- 3248c58 PEP 0263: Add encoding declaration	
- 609e6d3 Remove redundant parentheses
=> Update generic.py for PEPs 8 and 263 and remove unreachable code

sickbeard/metadata/mediabrowser.py
- ff7907f PEP 0203: Replace dict creation with dict literal	
- 6070bb0 PEP 0008: Add and remove whitespace and blank lines	
- 00f511b PEP 0263: Add encoding declaration	
- fa1c8fe Remove redundant parentheses
=> Update mediabrowser.py for PEPs 8 and 263

sickbeard/metadata/mede8er.py
- b21b797 PEP 0008: Add and remove whitespace and blank lines	
- b0fb54f PEP 0263: Add encoding declaration
=> Update mede8er.py for PEPs 8 and 263

sickbeard/metadata/kodi_12plus.py
- d0702c0 PEP 0008: Refactor variables that shadow built-in names	
- c3b644f PEP 0008: Add and remove whitespace and blank lines	
- 69f4294 PEP 0263: Add encoding declaration
=> Update kodi_12plus.py for PEPs 8 and 263

sickbeard/metadata/wdtv.py
- f4f5f55 Remove redundant parentheses	
- 4a7e8d1 PEP 0263: Add encoding declaration
=> Update wdtv.py for PEP 263

sickbeard/metadata/tivo.py
- c675674 Remove redundant parentheses
- 6edd83d PEP 0008: Add and remove whitespace and blank lines
- b2b842b PEP 0263: Add encoding declaration
=> Update tivo.py for PEPs 8 and 263

sickbeard/name_parser/regexes.py
- 4566d2c PEP 0008: Convert tabbedindents to spaces	
- 34a1d21 PEP 0263: Add encoding declaration
=> Update regexes.py for PEPs 8 and 263

sickbeard/name_parser/parser.py
- 3824491 PEP 0008: Convert None comparisons from operators to 'is / is not None'	
- 54edd29 PEP 0008: Fix indentation	
- 1bfa2e5 PEP 0263: Add encoding declaration
=> Update parser.py for PEPs 8 and 263

SickBeard.py, sickbeard/classes.py, sickbeard/helpers.py, sickbeard/name_cache.py, sickbeard/network_timezones.py, sickbeard/notifiers/pushbullet.py, sickbeard/sbdatetime.py, sickbeard/scene_exceptions.py, sickbeard/search.py
Select sbtimezone correctly for windows/linux
Rewrite pushbullet notifier to use requests and better code
Fix snatching (calling init for SearchResult)
Return uncode from sbdatetime
Lint scene_exceptions
=> Multiple fixes

gui/slick/js/new/displayShow.js, gui/slick/views/displayShow.mako
@OmgImAlexis let me know if this isnt correct, it fixes the issue (the js change did)
Will merge for now, change it if necessary.
=> Fix missing episodes in displayShow

gui/slick/js/new/displayShow.js, sickbeard/webapi.py
=> Fix forgotten import in webapi

sickbeard/helpers.py, sickbeard/providers/torrentz.py, sickbeard/scene_exceptions.py
Remove unneeded global keywords in sceme_exceptions
Clarify log message for torrentz
=> Fix synoindex calls in helpers

gui/slick/views/config_providers.mako, gui/slick/views/displayShow.mako, gui/slick/views/history.mako, gui/slick/views/home_popularShows.mako, gui/slick/views/manage_massEdit.mako, gui/slick/views/schedule.mako
=> Fix history layout caching issue (cant define mutables inside <%!)

sickbeard/providers/generic.py
Adds REAL to proper strings ,not real REAL handling
Examples
```
Family Guy S14E02 REAL HDTV x264 KILLERS
Mr Robot S01E08 REAL 720p HDTV x264 KILLERS
The Last Man On Earth S01E06 REAL HDTV x264 KILLERS
```
=> Add real to proper strings

sickbeard/__init__.py
This pull request updates the initial Github constructor to use the authentication method provided by the config file. This allows the use of expanded API limits for update checking.
=> Use login on initial Github request if defined.

gui/slick/views/inc_blackwhitelist.mako
Inform the user about Black- and Whitelisting validations and what to do in case of a validation fail.
related issue: https://github.com/SiCKRAGETV/sickrage-issues/issues/2266
=> update user information on anime Black- and Whitelisting behaviour

sickbeard/processTV.py, sickbeard/webserve.py
Reverts SiCKRAGETV/SickRage#3176
=> Revert "Fix post processing non-ascii"

sickbeard/providers/bluetigers.py
fix bluet... not logged in while searching
=> fix bluetiger auth

sickrage/core/webserver/gui/default/views/layouts/main.mako
@echel0n migrating a few of the fixes from https://github.com/SiCKRAGETV/SiCKRAGE/pull/3278 that were missed in https://github.com/SiCKRAGETV/SiCKRAGE/commit/5d0de3105c1e75df1072715a88e7e9842e97c66a and https://github.com/SiCKRAGETV/SiCKRAGE/commit/1e68c51ea7f2a6aeba8869fbcb16229768ee37bc.
=> Fix some issues with web root in templates and core.js

sickrage/core/webserver/gui/default/views/layouts/main.mako
Reverts SiCKRAGETV/SiCKRAGE#3279
=> Revert "Fix some issues with web root in templates and core.js"

sickrage/core/webserver/views.py
Reverts SiCKRAGETV/SiCKRAGE#3281
=> Revert "Use showObj when referencing indexerid"
