SiCKRAGETV/SiCKRAGE

gui/slick/js/displayShow.js
this correctly selects the value for the statusSelect id and fixes the ``invalid literal for int() with base 10: 'undefined'`` error when scheduling shows to wanted for example.
=> correct jquery syntax to select value to fix issue #285

sickbeard/versionChecker.py
The "x" option ignores the .gitignore
-x
Don’t use the standard ignore rules read from .gitignore (per directory) and $GIT_DIR/info/exclude, but do still use the ignore rules given with -e options. This allows removing all untracked files, including build products. This can be used (possibly in conjunction with git reset) to create a pristine working directory to test a clean build.
http://git-scm.com/docs/git-clean
=> Don't clean user files when GIT CLEAN

sickbeard/processTV.py
When post processing a directory with multipart rars, the same video file from each of the parts is added to the list of files to be processed. This causes problems when using symbolic or hard link process method, as the video file is deleted after the first time its processed. Subsequent attempts to process the same video fail.
This fix simply makes sure that the video file name is not already listed in the `unpacked_files` list before adding it. If multiple rars contain different files but identically named, this may cause issues, but I don't think SickRage copes with that situation anyway.
Let me know your thoughts and I'll update the PR with any comments.
=> Fix multipart rars causing the same extracted video to be postprocessed more than once

sickbeard/helpers.py
Processing postpone will happened if there is file with .part extension - incomplete transmission file.
=> Postpone Processing for incomplete torrents.

sickbeard/config.py, tests/config_tests.py
Also adds some simple tests so we can avoid future regressions.
Upstream SickBeard pull request is available here: https://github.com/midgetspy/Sick-Beard/pull/910
=> config.clean_url may add trailing /'s in unsuitable circumstances.

sickbeard/providers/t411.py
Problem with the user-agent. I logged with python User-Agent and download torrent with SickRage User-Agent. I think t411 have migrated to cloudflare. When you're logged with a different User-Agent, you have a different authKey in the cookie and 2 request with 2 User-Agent don't work.
=> Fix for https://github.com/SiCKRAGETV/sickrage-issues/issues/178

gui/slick/interfaces/default/config_general.tmpl
It's causing 'NoneType' object is not iterable when GIT timeout while connection to HTTPS
Discussion here:
https://github.com/SiCKRAGETV/sickrage-issues/issues/307
https://github.com/SiCKRAGETV/sickrage-issues/issues/388
https://github.com/SiCKRAGETV/sickrage-issues/issues/416
=> Check if list_remote_branches is empty before for-loop

sickbeard/versionChecker.py
In CheckVersion.init (sickbeard/versionChecker.py, line 41), the install_type attribute is only assigned if sickbeard.gh has been set, and it won't be if SR couldn't connect to Github. The restart code (SickBeard.py, line 482) tries to access install_type to determine which update command to run, which raises an AttributeError and prevents SR from restarting.
SiCKRAGETV/sickrage-issues#307 (comment)
=> Fix versionchecker

sickbeard/failedProcessor.py, sickbeard/webserve.py
- Fixes the erroneous use of segment as a list, when it is already a
list of episodes. This causes various errors in debug log complaining
about missing attributes.
=> Fix for 'List type has no attribute' on setting failed

sickbeard/processTV.py
- Fixes issue when Post-Processing a file with a generic filename in a
subfolder resulting in "Already Processed" errors
- Added a Show, Season, Episode parse to the dirname, and if that
results in usable data it adds it to the history check so this is
performed on that specific episode only
=> Added Episode check to PP history check

sickbeard/tv.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/493#issuecomment-71538630
UNKNOWN quality will always be low quality no matter what.
It's different from unknown episode status.
=> Set UNKNOWN quality as Low Quality

gui/slick/css/light.css
because the actual color don't have contrast with black font.
=> Change color of 100% progress bar light theme

sickbeard/providers/freshontv.py
Change HTTP to HTTPS as FreshonTV now supports secure connections
=> FreshonTV now supports HTTPS

gui/slick/interfaces/default/config_general.tmpl, gui/slick/interfaces/default/displayShow.tmpl, sickbeard/__init__.py, sickbeard/webserve.py
- Added option checkbox under General -> GUI (display filesizes)
- Added filesize column on Show Page to display filesize when episode is
Downloaded
- Changed style min-width for Episode Name when display_filesize = True
to keep episode names from wrapping around earlier on mobile devices.
(min-width: 190px)
=> Added option to display file sizes in Show page

gui/slick/interfaces/default/config_notifications.tmpl, gui/slick/interfaces/default/trendingShows.tmpl, gui/slick/js/configNotifications.js, gui/slick/js/recommendedShows.js, lib/trakt/trakt.py, sickbeard/__init__.py, sickbeard/notifiers/trakt.py, sickbeard/traktChecker.py, sickbeard/webserve.py
Should close SiCKRAGETV/sickrage-issues#301 and update Trakt.tv functionality to the new 2.0 API. 
This currently uses a borrowed API key for [Authentication for Media Centers](http://docs.trakt.apiary.io/#reference/authentication-media-centers) in `sickbeard.py/__init__.py` on line **483**, so a more permanent API key should be created/requested from the Trakt.tv folks.
=> Update to Trakt.tv API 2.0

gui/slick/interfaces/default/home_newShow.tmpl
Add a notice to inform the user about the current TVRage's indexer implementation missing the ability to retrieve specials.
See SiCKRAGETV/sickrage-issues#292 for more info
=> Add notice in addShow for special with TVRage

sickbeard/webserve.py, sickbeard/webserveInit.py
This commit put webcal in its own handler so the option CALENDAR_UNPROTECTED can work.
See SiCKRAGETV/sickrage-issues#456 for more info.
=> Fix access to webcal without password.

SickBeard.py
See https://www.python.org/dev/peps/pep-0476/ for more info.
=> Temporary fix for Python 2.7.9 for SSL

sickbeard/postProcessor.py, sickbeard/tv.py
- Renamer now handles metadata files that have add-ons to the
filename itself (fixes
https://github.com/SiCKRAGETV/sickrage-issues/issues/358)
- Renamer now handles subfolders for metadata (fixes
MediaBrowser and TiVO metadata renaming issues)
=> Fix for issue 358 (filename-thumb.jpg not renaming)

gui/slick/js/configNotifications.js
Fix TypeError: testBoxcar2() got an unexpected keyword argument 'accessToken'
=> Fix case issue for accesstoken

gui/slick/js/configProviders.js
When adding Newznab Categories other than 5030(SD) or 5040(HD), new categories don't get saved.
=> Newznab Categories not beeing saved

sickbeard/subtitles.py
Related to :
https://github.com/SiCKRAGETV/sickrage-issues/issues/457
This is why we have comma on the database like here ",en". Because alpha2 variable is empty.
Also, they have an error on the display page, this is already PR https://github.com/SiCKRAGETV/SickRage/pull/1260
=> Improve code check for list comprehensions on subtitle

gui/slick/interfaces/default/home.tmpl
Added sortAppend in the home.tmpl table to always sort by name asc
after selecting an other column.
See SiCKRAGETV/sickrage-issues#51 for more info
=> Always sort last by asc name.

sickbeard/providers/t411.py
so that category "tv series" is used for cache building
=> changed subcategories order

sickbeard/providers/kat.py
Cast the string item['torrent_verified'] as an integer so that 'verified' will be False if the returned string is "0" which would otherwise be True because it is a non-empty string.
=> Fix verified status of torrents from KAT

sickbeard/clients/utorrent.py
Put the token in first place.
See https://github.com/SiCKRAGETV/sickrage-issues/issues/483 for more
info.
=> Fix for uTorrent 2.2.1 token order.

sickbeard/providers/newznab.py, sickbeard/search.py
Some newznab feed don't return a date when the proper is a movie resulting in a KeyError.
When findpropper call pickBestResult the instance provided as no attribute
'size'. Added a check.
=> Fix issues with newznab provider

gui/slick/js/configNotifications.js
Sets the default device to "All devices" (string choice may need changing). A user may still select a specific device if desired. Fixes SiCKRAGETV/sickrage-issues#511. Also corrects the handling of current_pushbullet_device, the variable was not defined in the inner function before.
=> Set the default Pushbullet target to all devices

lib/cachecontrol/adapter.py, lib/lockfile/linklockfile.py
Function acquire will run in infinite loop if the fs doesn't support
link creation(OSError: (38, 'Function not implemented'))
E.g.: Unraid shares
=> Added detection of fs not implemented link creation

sickbeard/clients/download_station.py
Doesn't use TORRENT_VERIFY_CERT as underlying generic._request use verify=False.
See SiCKRAGETV/sickrage-issues#431 for more info
=> Disable ssl checking in synology client

sickbeard/failedProcessor.py
- Reverts changes made to failedProcessor.py by PR 1258
- Fixes miscelaneous errors on setting a single episode to failed.
=> Partial Revert 1258

sickbeard/helpers.py
To better distinguish between file permissions and not implemented.
=> Modified touchfile() to detect ENOSYS and EACCES.

gui/slick/interfaces/default/home.tmpl
Exception in tablesorter.bindsearch when table empty.
See SiCKRAGETV/sickrage-issues#7 for more info.
=> Fix progress bar vanishing when shows table empty.

sickbeard/tv.py
- Added a check for release_group field in db
- Added a check for location field in db (filename, requires
qual-RLSGROUP convention to be succesful)
- If release_group field in db empty and the releasegroup was found in
either release_name or location fields, then updates the db with the
releasegroup. Except when releasegroup is 'SiCKRAGE'
- If release_name is empty, and SR wants to replace it with a generic
one, it will now use the releasegroup if found, and otherwise replace
with SiCKRAGE.
=> Changed Releasegroup handling in Renamer

gui/slick/interfaces/default/config_general.tmpl, sickbeard/__init__.py, sickbeard/webserve.py
- Changed hardcoded value from 3am to SHOWUPDATE_HOUR
- Added field in Config General to set SHOWUPDATE_HOUR
- Default value is still 3 (am), added check if value over 23 or under 0
set to 0 (12am).
This will help people that turn off their rig for the night and, in doing so, miss showupdates in SR causing downloads to not work.
=> Added option to set ShowUpdate time

sickbeard/name_parser/regexes.py
Almost identical to no_season regex but omitted the "of joiner line" to make sure that iTunes maintained TV Show folders can still be scanned.
=> Added new regex 'itunes'

sickbeard/helpers.py, sickbeard/processTV.py
- Changed helpers.is_hidden_folder to utilize Windows GetAttributesW DLL
function to get folder attributes.
- Changed call to is_hidden_folder to use the entire path for the call,
instead of just the foldername.
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/554
=> Added Hidden Folder check for Windows Attributes

sickbeard/providers/freshontv.py
Improved logging to detect when CloudFlare is blocking via javascript challenge.
Relates to issue
https://github.com/SiCKRAGETV/sickrage-issues/issues/504
=> Improved logging to detect CloudFlare blocking

sickbeard/providers/rarbg.py
Manage the case where the torrent name got spaces in it
(Thanks @fernandog for noticing it)
=> Fix for RARBG provider

sickbeard/providers/tntvillage.py
Python 2.6 report syntax error
=> Fix self.hdtext declared as list instead of dict

sickbeard/providers/thepiratebay.py
TPB's ajax_details_filelist.php call seems to only return 
> File list not available. 
so season search mode will not work using TPB at this moment.
I suppressed the error message as it's annoying (see SiCKRAGETV/sickrage-issues#631 and SiCKRAGETV/sickrage-issues#641) and also added a missing `return None` when the file list cannot be retrieved (so always atm.)
=> TPB: Suppressed torrent list not found error message

sickbeard/providers/rarbg.py
Previously, the search was conducted only TV HD Episodes. Now searches
into TV Episodes, without making 2 http requests
=> Add SD search to RARBG provider

sickbeard/providers/t411.py
T411 has changed its domain name: t411.io
=> Update T411 to its new domain name

sickbeard/providers/alpharatio.py
Fix for alpharatio per sickrage issue https://github.com/SiCKRAGETV/sickrage-issues/issues/654  Backlog: failed parsing AlphaRatio Traceback
=> Fix for 654 Backlog: failed parsing AlphaRatio Traceback

gui/slick/interfaces/default/displayShow.tmpl
Use the existing pretty_filesize helper to format the file size of each file in DisplayShow. This results in much nicer output of the human readable file size. (e.g. 1.46 GB instead of 1460 MB)
=> Prettier file sizes in DisplayShow

sickbeard/logger.py
This is needed because Newznab apikey isn't stored as key=value in a
section in config.ini.
=> Added apikey to censoredformatter

gui/slick/interfaces/default/config_postProcessing.tmpl, sickbeard/__init__.py, sickbeard/processTV.py, sickbeard/webserve.py
- Adds option to delete RAR contents to Config -> Post-Processing
- Added check to ProcessTV to delete Rarcontents when Process_Method !=
Move
Implements feature requested here:
https://github.com/SiCKRAGETV/sickrage-issues/issues/539
=> Add option to delete RAR contents when Process_method != Move

SickBeard.py, sickbeard/logger.py, sickbeard/webapi.py, sickbeard/webserve.py
Windows UTF-8 console via cp65001
Enable usage of UTF-8 in Windows console via cp65001
To enable: chcp 65001 before launching SickRage
Fix opening log with cp1252 decode error
=> Subtitles 1/3: Windows UTF-8 console via cp65001

.gitignore
git reset should only reset git files not user files
@abeloin what do you think about set "get reset" by default in config.ini?
=> Don't remove logs folder when git reset is enabled in UI

gui/slick/interfaces/default/config_postProcessing.tmpl, sickbeard/__init__.py, sickbeard/helpers.py, sickbeard/postProcessor.py, sickbeard/processTV.py, sickbeard/tv.py, sickbeard/webserve.py
Fixes the following:
- List_associated_files also looks in subfolders to allow metadata in subfolders to be renamed properly. This causes associated_files for Post Processing (not renaming) to also include subfolders, which in turn can lead to files being deleted that are still in the queue to be processed.
- Delete RAR contents uses delete_files, which checks if result is true. If it isn't then it won't delete rar contents. It will now Delete RAR contents regardless if the process_method is not 'move'.
Adds the following:
- Config option under Post Processing to add your own syncfile extensions in a comma seperated value list.
- Changed is_syncfile function to accept a list, rather than hardcoded values.
=> PP Syncfiles, List_associated_files fix, and Delete RAR contents fix

sickbeard/helpers.py
- Now actually returns the correct show instead of nothing for post
processing.
Fixes:
Shownames not being found with "Show not in DB, you need to add it..."
messages during Post Processing. (most notably Forever (US) or Forever (2014))
=> Fix Show Lookups on Indexer

sickbeard/metadata/mede8er.py
- Fixes POSTPROCESSER :: Exception generated in thread POSTPROCESSER:
Cannot find attribute 'contentrating' errors in Mede8ter metadata
creation.
=> Fix Exception generated: Cannot find attribute 'contentrating'

gui/slick/js/fuzzyMoment.js
When enabling 'Display fuzzy dates' and 'Trim zero padding' in
combination with an 24 hour time style, SickRage would for example show
"Last Thu, 9:59:31" instead of "Last Thu, 21:59:31". This happened because fuzzy would case-insensitive replace "hh" with "h", thus also replacing "HH"(21h) with "h"(9h).
*This is the simplest solution I could find. If anybody has a better solution, please let me know (not sure how to change the pull though, haha).*
**Screenshots**
[Settings](http://i.imgur.com/kAsk3BJ.png) - [Wrong (old) display](http://i.imgur.com/XCstrSe.png) - [Good (new) display](http://i.imgur.com/LnwBoCF.png)
=> Fix time display for fuzzy dates with trim zero and 24 hour time style 

gui/slick/interfaces/default/home_trendingShows.tmpl
When adding trending show, the UI header has 'Coming Episodes' selected. 
Correct behavior would be having 'Shows' selected, as with recommended shows, adding shows etc.
=> Fix sickrage UI header when adding 'trending' show

sickbeard/providers/freshontv.py
Search was iterating through 15 pages of results for the regular RSS cache search. Limited this to 3 pages.
=> freshontv: Limit number of pages for RSS search

sickbeard/providers/alpharatio.py
Fix AR torrent ID.  Was getting the wrong ID from the torrents.  Also
fixed seeders and leechers for proper numbers.
Tested and working on my system
=> Fix AR torrent ID

sickbeard/tv.py
Currently when "archive first match" is selected and custom quality is used downloaded episodes with quality in archive list but lower than best are colored as low quality (despite they wont be redownloaded). 
It also applies to qualities that are better than minimal archive quality but are not in archive list (for example when downloaded manually or quality preference was changed).
=> Fix coloring episodes as good when "archive first match" selected

sickbeard/__init__.py
- Fixes NameError: name 'shutil' is not defined caused by monkeypatching
shutil.copyfile
=> Fix shutil import error

sickbeard/webserve.py
```
2015-03-04 14:17:18 ERROR Thread-53 :: Checkout branch couldn't compare DB version - Requests error AASSLError: [Errno 1] _ssl.c:499: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed AA raise SSLError(e, request=request) AA File "/share/MD0_DATA/.qpkg/SickRage/lib/requests/adapters.py", line 431, in send AA r = adapter.send(request, **kwargs) AA File "/share/MD0_DATA/.qpkg/SickRage/lib/requests/sessions.py", line 573, in send AA resp = self.send(prep, **send_kwargs) AA File "/share/MD0_DATA/.qpkg/SickRage/lib/requests/sessions.py", line 461, in request AA response = session.request(method=method, url=url, **kwargs) AA File "/share/MD0_DATA/.qpkg/SickRage/lib/requests/api.py", line 49, in request AA return request('get', url, **kwargs) AA File …
```
=> Don't check SSL certificate when fetching DB version

gui/slick/interfaces/default/inc_top.tmpl
- Adds warning at the top of the page when branch is anything other than
master. Encourages users to switch to master.
=> Add Branch Warning when branch is not master

gui/slick/interfaces/default/config_providers.tmpl, gui/slick/js/configProviders.js, sickbeard/providers/__init__.py, sickbeard/providers/rsstorrent.py, sickbeard/webserve.py
I have created a field to the torrent rss providers config so that a custom title tag can be used instead of just the text 'title' it was tested and working with 'http://showrss.info/feeds/all.rss' using 'showrss_rawtitle'. Hopefully the label and description are good, let me know if you think it should automatically replace ':' with '_'  and if '<' & '>' should be striped if it was put in the text box.
This feature was requested https://github.com/SiCKRAGETV/sickrage-issues/issues/607
=> Torrentrss custom title tag

sickbeard/postProcessor.py
- Changed PostProcessor._delete to include base_name_only = True, and
subfolders = True
Makes sure that when replacing old episodes in PostProcessing ALL the
old metadata is deleted, including those that have an addition to the
filename (-thumb.jpg) or are in subfolders (.meta and .metadata
subfolders for some mediaplayers).
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/842
=> Change PostProcessor._delete function to delete ALL associated files

sickbeard/notifiers/pushbullet.py
- notify_git_update missed the notificationType value on calling
_sendPushbullet, which may cause the Content-length header to be
corrupted.
Hopefully fixes:
2015-03-05 09:06:58 ERROR    Thread-186 :: Pushbullet notification
failed.
AA
AA  
POST requests require a Content-length header.  That’s all we know.
AA  
411. That’s an error.
AA  
AA
=> Possible Fix for Pushbullet update notification

sickbeard/metadata/mede8er.py
- Redid most of the metadata assignments using getattr() to keep it from
throwing exceptions when info is not available for a certain show or
episode.
=> Redo metadata assignments for mede8er

sickbeard/helpers.py, sickbeard/name_parser/parser.py, sickbeard/postProcessor.py, sickbeard/processTV.py
- Changed NameParser to include trySceneExceptions boolean
- Changed calls to NameParser from Post Processing function to include
trySceneException=True when tryIndexers is also True.
- Changed get_show function to try looking up a parsed showname in the
scene exceptions table (using get_scene_exception_by_name) if both cache
and Indexer lookups fail and trySceneException is True.
As found here:
https://github.com/SiCKRAGETV/sickrage-issues/issues/25
https://github.com/SiCKRAGETV/sickrage-issues/issues/769
https://github.com/SiCKRAGETV/sickrage-issues/issues/582
https://github.com/SiCKRAGETV/sickrage-issues/issues/356
https://github.com/SiCKRAGETV/sickrage-issues/issues/864
And others.
=> Use Scene Exceptions in Post Processing

sickbeard/helpers.py
Whoops... I failed to account for shows actually not being in the scene exceptions. Since it then passes a None to int(), that will throw an exception.
- Assigns ShowID instead of direct calling it. If not None, then it will pass to findCertainShow as an int.
=> Fixed exception on failing to find show in Scene Exceptions

sickbeard/processTV.py
- result.result was falsely assigned the value from the process function
return, which doesn't return anything.
- Will now return the correct strings (Problem when there was a problem,
or succesfully Processed if not)
This problem was exaggerated by changing the function and copying the
erroneous line to all methods.
=> Fix for PP always returning "Problem(s) during Processing"

sickbeard/__init__.py, sickbeard/logger.py
- Added logging.shutdown() on stopping/restarting SR. Should release
opened logfiles.
=> Fix error 32 file in use when rotating logfiles on windows

sickbeard/webserve.py
- Fixes the update not using the inc_top.tmpl which handles the css
The restarting page when updating was foogly because it called restart_bare.tmpl. Restart_bare.tmpl is called by restart.tmpl in between the top and bottom templates. This makes sure it uses the correct css for the currently selected theme... This should make it look a lot better.
=> Change update restart page to restart.tmpl instead of restart_bare.tmpl

sickbeard/processTV.py
- Now ignores hidden folders inside folders
- Changed delete_folder to ignore folders that are not empty, so that
those ignored folders are not deleted.
=> Fix for trying to process hidden sub/sub folders

sickbeard/webserve.py
- Will skip adding the episode to the backlog search when changing
status to Wanted and the show is paused.
- Adds log message "some episodes were set to Wanted but show is paused.
Not adding to backlog until show is unpaused"
=> Dont backlog when paused

SickBeard.py, sickbeard/__init__.py
- Moved logging.shutdown() from sickbeard/init to SickRage.py
- Call logging.shutdown() right before spawning new SR instance
- Call logging.shutdown() right before os._exit(0)
This makes sure that the file handles are closed, and that they do not
get reopened by late log entries in the shutdown process (last log entry
is about restarting SR right before respawning the process).
=> Fix error 32: file in use on logrotation on Windows

sickbeard/processTV.py
- Makes sure that it only deletes an empty folder. os.rmdir will throw an exception when it encounters a folder that is not empty, whereas shutil.rmtree will simply remove the folder.
Also adds some more descriptive logging so it's easier to find which call caused a folder to be deleted (different logmessage for check_empty = True than check_empty = False).
Solves https://github.com/SiCKRAGETV/sickrage-issues/issues/920
Note: Also on the TO DO list for a future PR is to continue Processing a folder when it encounters a file that fails to process. Right now it stops. This will need a cumulative process_result which will inform the user of the fact that it failed a file, and list the files it failed (so measures can be taken to correct this).
=> Change Delete_folder to use rmdir when check_empty = True

sickbeard/clients/deluge.py
Use deluge configuration when `move_completed_path` is not defined in sickrage.
With actual code, if deluge is configured to move downloaded files to another directory, it will be overriden with a blank path making deluge keep files in initial download location.
Tested OK !
=> Fix deluge move completed default value

gui/slick/interfaces/default/config_search.tmpl, gui/slick/interfaces/default/editShow.tmpl, sickbeard/search.py, sickbeard/show_name_helpers.py
Following discution from https://github.com/SiCKRAGETV/sickrage-issues/issues/919
This implements consistent word filtering for global words filtering and show words filtering. In both case, regexp are escaped and only full words are catched.
This has been refactored using a single function `show_name_helpers.containsAtLeastOneWord`. Also labels in UI have been updated accordingly.
=> Use consistent behavior in word filtering (global and show settings)

sickbeard/processTV.py
- Will now continue if an error is encountered with a single file
- Will skip only the current folder when syncfiles are encountered
- Will keep track of failed items using an aggresult variable in
processResult()
- Will show a summary at the end of Post Processing listing all failed
items (files and folders) with the reason for failing.
- Will only set aggresult to False when actual processing fails for a
file, not if no processable items are found or files are already
processed (will show those in the summary)
=> Changed failure handling in PostProcessing

sickbeard/tvcache.py
Avoid all this. DebuG log is full with this traceback. We only need the error message: timeout
```
2015-03-15 09:01:26 DEBUG    SEARCHQUEUE-BACKLOG-262414 :: [<PROVIDER>] :: Traceback (most recent call last):
AAConnectTimeout: HTTPSConnectionPool(host='****', port=443): Max retries exceeded with url: /login.php (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b11090>, 'Connection to **** timed out. (connect timeout=30)'))
AA    raise ConnectTimeout(e, request=request)
AA  File "/home/pi/SickRage/lib/requests/adapters.py", line 419, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/home/pi/SickRage/lib/requests/sessions.py", line 573, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File …
```
=> Remove tvcache traceback and change to DEBUG

apparmor_profile
You may not want to merge this, at least not in its current state, but this pull request contains the apparmor profile that I use with sickrage.
=> Add apparmor profile.

sickbeard/webapi.py
Phantom changes to the DB connection results in the return of
sqlite3.row results when the connections was set to return dict.row
results before queries are called.  Possible cause is multi-threading
with a global DB connection.
=> Safety feature to convert sqlite3.row results to dict 

gui/slick/interfaces/default/config_postProcessing.tmpl
@TagForce until we change DB to fix this
UPDATE: the name patterns that SR have, only one have "quality" in it. Won't this cause issues if user select them?
=> Add note to reminder user to add quality pattern in PP renaming

sickbeard/tv.py
- When status for a new episode is unknown and it is a special, it
should now change its status to SKIPPED rather than default status set
in Show settings.
https://github.com/SiCKRAGETV/sickrage-issues/issues/21
=> Fix default new special status

gui/slick/interfaces/default/config_postProcessing.tmpl, sickbeard/__init__.py, sickbeard/processTV.py, sickbeard/webserve.py
- Adds option to not delete empty folders to Post Processing Config.
- Only valid when Auto Post Processing, manual overrides the setting.
https://github.com/SiCKRAGETV/sickrage-issues/issues/327
=> Option to not delete empty folders during Post Processing

sickbeard/postProcessor.py
- List_associated_files would check the wrong folder when deleting files
- Fixes issue when downloaded file has the same namepattern as the old
file. Would then proceed to delete the new file.
Hotfix, merge with master and develop
=> [hotfix] Fix List_associated_files checking wrong folder

sickbeard/config.py, tests/config_tests.py
The newly added test should demonstrate the currently broken behavior.
Corresponding Sick-Beard pull request can be found here: https://github.com/midgetspy/Sick-Beard/pull/932
=> Add workaround for improperly cleaned scgi over unix domain socket URI

sickbeard/__init__.py, sickbeard/providers/__init__.py, sickbeard/providers/eztv.py, sickbeard/providers/generic.py
This is a EZTV provider using the PopcornTime API http://eztvapi.re/. I started working on it since there is no EZRSS feed working as of today (ezrss.ch, ezrss.it and ezrss-proxy.net are down). 
The provider only supports a search mode by episode. This is by design, since the PopcornTime API does not provide a RSS feed, and that EZTV does not provide season packs. So far, it works fine, but some adjustments will probably be necessary.
Any feedback welcome :)
=> EZTV provider

gui/slick/interfaces/default/config_subtitles.tmpl, lib/subliminal/services/addic7ed.py, lib/subliminal/videos.py, sickbeard/__init__.py, sickbeard/webserve.py
Embedded subtitles are not always of good quality. This adds the ability to ignore embedded subtitles so new subtitles are downloaded. Also added NL in the addic7ed provider.
Note: it would be better to make this function a show setting, but this would need database changes..
=> Ability to ignore embedded subtitles and layout fixes in config_subtitles.tmpl

sickbeard/postProcessor.py
- Adds check for quality even if SR initiated the download
is_priority will now return False if the episode status is not snatched
and the new quality is lower than the old quality (or lower or equal if
its a proper)
https://github.com/SiCKRAGETV/sickrage-issues/issues/1023 for more info
=> Added Quality check even if SR itself downloaded the episode

sickbeard/helpers.py
- Fixes unicode error by using EncodingKludge for isfile check instead
of assuming it is unicode.
=> Fix unicode error in verify_freespace

sickbeard/notifiers/plex.py
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1123 for more info
=> PlexNotifier: Fix calling KODI notify instead of pmc

sickbeard/notifiers/plex.py
This reverts commit d5e198f3375dd1754b7bba2563c158c8f63e6157.
=> Revert "PlexNotifier: Fix calling KODI notify instead of pmc"

sickbeard/metadata/mede8er.py
SiCKRAGETV/sickrage-issues#1166
Must be 'UTF-8' instead of 'utf-8' to get automatically written as xml and portable across python versions, as xml_declaration does not exist in 2.6.
Should work regardless of version now. Needs Tested.
Note:If this does not work as expected, method="xml" instead of xml_declaration=True should be tried.
=> Fix for xml_declaration unexpected keyword in python 2.6.

sickbeard/providers/eztv.py
Use of https://eztv.ch as URL for RSS feed, since http://eztvapi.re does not provide RSS.
=> Add RSS to EZTV provider

sickbeard/helpers.py
Fix bug where a broken symlink will break viewing a show.
Reference: SiCKRAGETV/sickrage-issues#1224
=> Ignore OSError when obtaining the size of a path.

sickbeard/postProcessor.py
Shows which associated files were found. Previously made no mention of which files are associated.
=> Add logline to show found associated files

sickbeard/postProcessor.py
Changes the Associated files check when running during PP (subfolders =
False) to do the following:
- Lists all files in current folder
- Loops through each file and checks if they are the same as the
videofile in a case-insensitive way
This is needed because both glob.glob and fnmatch act in a
case-sensitive matter on case-sensitive file systems.
Should fix https://github.com/SiCKRAGETV/sickrage-issues/issues/1117 for
the most part. Differently named files (not only case differences) will
still be missed
=> Fix Case Sensitive associated files check

sickbeard/postProcessor.py
- Fixes issues where a snatch history returning quality 'Unknown' is
accepted as an acceptable quality without trying to get an actual
quality from _get_quality()
https://github.com/SiCKRAGETV/sickrage-issues/issues/1225
=> Fix unknown quality being accepted as a valid quality in PP

sickbeard/showUpdater.py
A small change to fix https://github.com/SiCKRAGETV/sickrage-issues/issues/1193 : 
UnboundLocalError exception can be thrown at piList.append(curQueueItem) in cases where the CantUpdateException is thrown in the earlier try block around line 81. In this case, curQueueItem is never assigned a value and the list appending fails.
This change just skips the need for a temp holding variable "curQueueItem" and appends directly to the list the return from the updateShow/refreshShow methods.
Now if updateShow does throw a CantUpdateException, the piList.append in the try block is never attempted and so the UnboundLocalError is avoided.
Note: This is my fist github contribution, so apologies if I mess anything up.
=> ShowUpdater: referenced before assignment curQueueItem

sickbeard/metadata/generic.py, sickbeard/metadata/kodi_12plus.py
Fixes adding existing shows automation.
Removed "episodeguideurl" tag from being created in the nfo as it is not valid and kodi doesn't even read it.
TODO: Find why indexer and id are set twice each in nfo files created by SR
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/1205
=> Auto determine indexer when indexer tag not present in nfo

sickbeard/classes.py
- Changes the title assignment to use the message if there is no
Exception that generated the error. Should fix submitting errors that
were handled by SR itself, rather than an exception like configuration
errors or the like.
fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/1282
=> Fix Title of None for Errors submitted through UI

sickbeard/webserve.py
- Fixes AttributeError: 'NoneType' object has no attribute 'getOverview'
exception in rare cases when removing a show for which a search is still
running.
Will handle the exception and log the show's indexerID to make debugging
easier.
This will not fix the root cause, which is that the search queues will
not be properly emptied when deleting a show. This will make sure we are
able to check if this is really the cause.
=> Fix NoneType object has no attribute getOverview

sickbeard/clients/__init__.py
Fixes erroneous error messages in download clients, causing nzb/torrent
sending to not finish succesfully and causing extra settings to not be
sent (like labels).
Effectively removes http status codes in the 100 - 299 range from the
list (those are success messages and should not be handled as errors)
https://github.com/SiCKRAGETV/sickrage-issues/issues/1331
=> Hotfix: Remove Success codes from http_error_code list

sickbeard/metadata/generic.py, sickbeard/metadata/kodi_12plus.py, sickbeard/metadata/mediabrowser.py
I think there is still some work to be done to make this process more proper.  I don't think that any other indexer_id should be stored in `<id>` other than tvdb, as kodi has no idea that it isn't thetvdb, and an art refresh from kodi could return the wrong show.
One problem of removing `<indexer>` (which needs to be done), is that Series.xml has no epg, or any urls at all, to check for theTVDB or TVRage and decide what indexer the `<id>` is referencing.
There should be a method to query each indexer with the provided `<id>` and compare it to the `<title>` we have, and set the indexer in SR db accordingly.  Once it is in our db, it never needs to be read again.
Finally, all of these problems exist prior to these changes, and this is a step in the right direction.
=> Remove indexer from tvshow.nfo and series.xml

sickbeard/notifiers/plex.py
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/1348 and allows the use of just an authentication token for Plex Media Servers again.
Further work is needed to get the notifications working properly again, currently this reports a connection error, but still talks to the server properly.
=> Fix Plex Authentication Token

sickbeard/webserve.py
The return value of update_library() was changed from True/False to None/Error string in https://github.com/SiCKRAGETV/SickRage/commit/4c9d9185b0c25d435a6bbb20efa60b1f4337a016 but the check for the return value was never updated. This corrects that so the notification sent out correctly states that it sent a notification to the server instead of defaulting to stating it was unable to connect.
This fixes the rest of the issues described in SiCKRAGETV/sickrage-issues#1348.
=> Fix Plex notification status check

sickbeard/tv.py
https://github.com/SiCKRAGETV/SickRage/pull/1796 adds a check for
Exception ServiceError, but doesn't return on the exception. For every
other exception the function is returned from.
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/1359
=> HotFix for: local variable 'subtitles' referenced before assignment

sickbeard/providers/generic.py
Changed the _doSearch call in generic.py to only use
_get_season_search_strings when search_mode is 'sponly'
https://github.com/SiCKRAGETV/sickrage-issues/issues/1350
=> Fix SeasonPack searchstrings for episode search on multiple ep search

gui/slick/interfaces/default/home.tmpl
* Return episode count weighted sorting
* Episode 'Downloads' field can be filtered by Percent value now
* supports >, >=, <=, < ,  xx to yy , xx - yy as well as exact value
with or without pre / post fix of '='
Note: >, >=, <=, < should be first, followed by a space, then the value.
ie.  '>= 50'
=> FR#574 - Home Page - Show List Filtering

sickbeard/postProcessor.py
* Sends Episode Object on Post process
* If the path of the PLEX Show Section is found within the Episode
Object Location,  only that section is sent an update request.
otherwise all sections are.
Note: Functionality was introduced in the Plex Notification update,
sending Episode Object on Post Process was not included at that time.
=> FR#1078 Update Specific Plex Sections

sickbeard/logger.py, sickbeard/webserve.py, tests/issue_submitter_tests.py, tests/name_parser_tests.py, tests/torrent_tests.py, tests/xem_tests.py
Duplicate submitted issues are now comments to the original instead of
duplicating. ***DO NOT CHANGE APP SUBMITTED ISSUE TITLES FOR NOW**
Maybe later we can move to parsing issue comments to match errors and
make it ok to change APP SUBMITTED issue titles, but currently I have it using
the issue title to search for originals.
Fix some unit tests not running some or all of their tests when ran standalone.
See how it just adds a comment instead of a  new issue in SiCKRAGETV/sickrage-issues/issues/1392
Also, the gists it pasts are just the error it finds, not the entire log, which was the original writer's intent.
=> Fixup regex for issue submitter, Dont allow dupe app submitted issues. More

sickbeard/providers/kat.py
http://torrentfreak.com/kickasstorrents-moves-to-isle-of-man-domain-name-150423/
=> New KAT domain page

.travis.yml
Will show up in the travis build log, and aid in debugging failed builds.
=> Cat sickrage.log generated by unit testing if travis build fails.

sickbeard/db.py, sickbeard/postProcessor.py, tests/test_lib.py
I think its not wise to make the build tests operate on the db differently than normal operation.  It fixes the build but down the road there may be a divergence between test and run where tests succeed and run has problems.
This uses exclusive locking on the db, which is fine because we only ever have one connection to any given db at one time, and we do not want other applications touching it while we have it open anyways.  It also gives a small performance gain overall.
=> Build tests

sickbeard/logger.py, sickbeard/webserve.py
If user presses button to submit again while its already processing/submitting, they get a notification to wait.
=> Block issue submitter from running more than once at a time. Fixes #1305

sickbeard/logger.py
* Modified Regex substitution to account for 3 possible keys that the
API can be attached to
* Modified Regex to account for API Key being at the end of the string
or followed by an & or a space
* Used capture groups to only mask out the API Key, matched prefix and
ending are kept
=> FIX#1292 Masking NZB API Keys in logs

sickbeard/__init__.py
SiCKRAGETV/sickrage-issues/issues/1156#issuecomment-96308300
SiCKRAGETV/sickrage-issues/issues/1156
Need to save the default setting as int, to avoid confusing users. "False" as a setting does not work, 0 will.
=> HOTFIX: convert the bool to int for default web_use_gzip config

init.upstart
Currently spawns 2 instances, and the second cannot be stopped by the service. Cannot be stopped in SR ui is service is running, and does not stop service.
PR fixes this.
=> Fix upstart multi pid

sickbeard/config.py
To help prevent confusing users modifying the config directly.
With this, any case variation of 'true' will work the same as 1, and 
any case variation of 'false' will work the same as 0.
=> Make check_setting_int understand True/False from settings

sickbeard/providers/eztv.py
Fix SiCKRAGETV/sickrage-issues/issues/1437
=> if re.search returns None due to no match, .group() will cause an exception

gui/slick/interfaces/default/config_postProcessing.tmpl, gui/slick/interfaces/default/config_search.tmpl, lib/unrar2/unix.py, sickbeard/providers/morethantv.py
Replace two out of place tabs with spaces, identified by python -i
This reference helped confuse me about failed download handling.  Because the file doesn't exist, I opted to not even try it for worry that something bad could happen without being able to RTFM.
Closes SiCKRAGETV/sickrage-issues/issues/1430
=> Remove reference to readme-FailedDownloads.md, which doesnt exist.

.travis.yml
Oops, adding || cat sickrage.log makes travis think we have a successful build, since cat returns 0.
=> Fix travis reporting failed builds as successful

lib/tvdb_api/tvdb_api.py, lib/tvrage_api/tvrage_api.py, sickbeard/webapi.py
Fixes SiCKRAGETV/sickrage-issues#1491 so that an empty result set is returned rather than an internal error when no show results are found.
=> Fix webapi error when show search returns 0 results

sickbeard/providers/scc.py
As the commit message says, currently SickRage is attempting to search dates with the pipe character as a delimiter, which isn't supported by SCC.
E.g. 
```Jimmy.Fallon.2015|04|27``` returns no results
```Jimmy.Fallon.2015.04.27``` returns 2 results
=> SCC doesn't support searching dates with pipe characters. Use '.'

sickbeard/providers/eztv.py
1) try magnet link
2) try rarbg link
3) try extratorrent link
4) try '([^/]+$)' : everything after last slash character (not accurate)
5) fallback, title is equal to link
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/1437
=> Add flexibility when determine title from link in eztvapi.re:

sickbeard/logger.py
Regex was too broad and would replace more than it should have.  Fixed
with better matching for keys.
=> Fix#1450 - Update Regex to be more specific to for replacement

sickbeard/show_name_helpers.py
There should have always been a check if the show was anime here.  As
only anime had white and blacklists.  Added both check for is_anime and
that release_groups is not none
=> Fix#1453 - Fix 'NoneType' object has no attribute 'whitelist

sickbeard/image_cache.py, sickbeard/webserve.py
* Adds FanArt to the local image cache for the web interface.
* Call to show fanart in templates would be:
"$sbRoot/showPoster/?show=$show.indexerid&amp;which=fanart"
=> FR#1585 - Add Fanart to local image cache

sickbeard/notifiers/kodi.py
Sometimes my Kobi will return an httplib.BadStatusLine exception if it doesn't boot up. Catch this error and log it correctly.
=> Also catch BadStatusLine

sickbeard/db.py
while reading the DB
```
2015-05-19 11:19:18 Thread-19 :: Failed doing webui callback: Traceback (most recent call last):
File "/home/osmc/SickRage/sickbeard/webserve.py", line 258, in async_call
result = function(**kwargs)
File "/home/osmc/SickRage/sickbeard/webserve.py", line 1174, in displayShow
[showObj.indexerid]
File "/home/osmc/SickRage/sickbeard/db.py", line 192, in select
sqlResults = self.action(query, args, fetchall=True)
File "/home/osmc/SickRage/sickbeard/db.py", line 170, in action
sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
File "/home/osmc/SickRage/sickbeard/db.py", line 86, in execute
return self._execute(query, args).fetchall()
File "/home/osmc/SickRage/sickbeard/db.py", line 235, in _unicode_text_factory
return unicode(x, …
```
=> Try to fix 'utf8' codec can't decode byte

sickbeard/providers/newznab.py
When I was debugging the cache yesterday, I realised that providers.newsznab.NewznabCache._parseItem() was looking for an attribute named "tvrageid" when the  name that Newsznab returns is "rageid".
This error provoqued TVCache._addCacheEntry() never added an entry was it was called from NewznabCache._parseItem()
=> Fix name of attribute in providers.newsznab.NewznabCache._parseItem()

sickbeard/indexers/indexer_config.py, sickbeard/network_timezones.py, sickbeard/notifiers/growl.py, sickbeard/notifiers/kodi.py
Sometime soon, sb_network_timezones should be added directly to SR source as a pre-populated submodule and we can avoid the web requests to it altogether since it rarely changes
=> Change urls to use http github.io pages from our repos

sickbeard/helpers.py, sickbeard/postProcessor.py
- When copying or hardlinking checks if the source file is locked for
reading
- When moving or moveAndSymlinking checks if the source file is locked
for reading and writing
=> Check file lock

gui/slick/interfaces/default/config_providers.tmpl, sickbeard/__init__.py, sickbeard/providers/rarbg.py, sickbeard/webserve.py
Ranked: If checked will only return rartv, ettv, and scene releases released internally on rarbg. Otherwise returns all results from rarbg site.
Sorting: By seeders, leechers, or newest first
=> Add ranked and sorting options to RARBG settings

sickbeard/helpers.py
Fixes SiCKRAGETV/sickrage-issues#1726 
Fixes SiCKRAGETV/sickrage-issues#1586
```
Strip [vtv] and -20-40 From release group.
Strip '[ www.TorrentDay.com ] - ' and '[ www.Cpasbien.pw ] ' release_name prefixes.
```
=> Add '[vtv]' and '-20-40' to non-rlsgroups

sickbeard/providers/hdtorrents.py
```
>>> Title = "History - A"
>>> print Title.strip('History - ')
A
>>> Title = "History - B"
>>> print Title.strip('History - ')
B
>>> Title = "History - C"
>>> print Title.strip('History - ')
C
>>> Title = "History - D"
>>> print Title.strip('History - ')
D
>>> Title = "History - E"
>>> print Title.strip('History - ')
E
>>> Title = "History - F"
>>> print Title.strip('History - ')
F
>>> Title = "History - G"
>>> print Title.strip('History - ')
G
>>> Title = "History - H"
>>> print Title.strip('History - ')
>>>
=> Fix HDT removing first letter of the file

sickbeard/webapi.py
webapi does not update the database for the "show.pause" command till SickRage restarts. This causes the SickRage web interface to not show the "Coming Episodes" paused or not accurately. And any addons retrieving the pause data will not be correct after a webapi "show.pause" command till after a restart.
Added
showObj.saveToDB()
to lines 2391 and 2395
=> webapi CMD_ShowPause doesn't update database

gui/slick/interfaces/default/editShow.tmpl
because it's only usefull when adding a show
https://github.com/SiCKRAGETV/sickrage-issues/issues/1483
=> Remove "Default Episode Status" from editshow

gui/slick/interfaces/default/history.tmpl, sickbeard/helpers.py, sickbeard/providers/newznab.py, sickbeard/providers/rarbg.py
Fix SiCKRAGETV/sickrage-issues#1862
Fix SiCKRAGETV/sickrage-issues#1825 (Hopefully)
Fix Fix SiCKRAGETV/sickrage-issues#1858 (Might not catch it still)
Strip '. -' after removeWords.
regexes need updated but are quite complicated. failing regex is the only reason we need removeWords, and even after they are not perfect. I have a perfect working regex without removing subrls suffix but atm it breaks down if there is no release group at all in the name.
=> Multiple fixes

sickbeard/providers/iptorrents.py
Updated search stings with airdate from "|" to " " to narrow searches
"|" is used as an and function, this searches all entries that include the month and date specified, replaced with a space instead to bring only relevant entries to create successful searches.
=> Updated search stings with airdate

sickbeard/subtitles.py, sickbeard/tv.py
@fernandog @neoatomic 
This is what I mean about using a link named as release name (with extension), scan the video, then remove the link.
Then later name the subs right.
This works beautifully btw. It got every subtitle I had configured super quick, doesnt error or leave junk, and it has nearly every piece of imformation it could get. I suggest we use this method for now, and ask subliminal for a new paramter.
=> Use a temp hard link to get better subs matches

gui/slick/interfaces/default/apiBuilder.tmpl, sickbeard/versionChecker.py, sickbeard/webapi.py
I added the two following methods to SickRage's API:
- `sb.checkversion`:
- Get information about the current version
- Get information about the latest version
- Check if an update is required
- Get the number of commits between the current version and the latest version
- `sb.update`: update SickRage if necessary
Request:
```
GET /?cmd=sb.checkversion
```
Response:
```json
{
"data": {
"commits_offset": 0, 
"current_version": {
"branch": "develop", 
"commit": "ddc0fca21d9030612a5c810ecc24463a7f64112b", 
"version": "v4.0.24"
}, 
"latest_version": {
"branch": "develop", 
"commit": "3565ec70dc924d8117f506983fc18a9351f487e4", 
"version": "v4.0.24"
}, 
"needs_update": false
}, 
"message": "", 
"result": "success"
}
```
Request:
```
GET /?cmd=sb.update
```
Response:
```json
// If no update is …
```
=> Add API methods to check for update and perform update

sickbeard/helpers.py
The code without .format result in this:
Unknown exception in getURL ****: ('Connection aborted.', gaierror(-2, 'Nome ou servi\xc3\xa7o desconhecido'))
with .format shows correctly:
MAIN :: Unable to setup github properly, github will not be available. Error: error -2 : Nome ou serviço desconhecido
@miigotu ok?
=> Fix log messages with chars like \xc3\xa7o

sickbeard/providers/tntvillage.py
Error log:
2015-07-08 10:50:37 ERROR    SEARCHQUEUE-BACKLOG-248835 :: [TNTVillage] :: Failed parsing TNTVillage Traceback: Traceback (most recent call last):
File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/providers/tntvillage.py", line 436, in _doSearch
if not self._is_italian(result) and not self.subtitle:
File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/providers/tntvillage.py", line 309, in _is_italian
if not re.search(sub, name, re.I):
File "/usr/lib/python2.7/re.py", line 142, in search
return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
Traceback (most recent call last):
File "/home/mediacenter/src/sickbeard/sickrage/sickrage/sickbeard/providers/tntvillage.py", line 436, in _doSearch
if not self._is_italian(result) …
=> Fix TypeError on tntvillage provider

sickbeard/providers/newznab.py
All items in the list referred to the same object, so when this object was mutated all the items in the list got mutated.
This resulted in exactly the same search url multiple times when we had a list of scene exceptions.
Appended a copy of the original params dictionary object to the list, instead os the original object.
=> Scene exceptions list overwite results in multiple identical search url's

gui/slick/interfaces/default/status.tmpl, sickbeard/helpers.py
This change the formatting of the the *Start time*, *Cycle time* and *Next run* columns in the *Scheduler* table.
Before:
After:
=> Small visual improvement in server status

gui/slick/interfaces/default/inc_top.tmpl
This PR makes SickRage looks a bit better in Chrome for Android (don't know if it works on iOS too).
Before:
After:
=> Better integration in Chrome for Android

gui/slick/interfaces/default/apiBuilder.tmpl, gui/slick/interfaces/default/home.tmpl, sickbeard/tv.py, sickbeard/webapi.py, sickbeard/webserve.py
For SiCKRAGETV/sickrage-issues#1763.
This adds a new API method to get the network logo of a show. I also updated the web part.
I think it would be nice to merge some code between the API and the web part. Right now the code to get a show banner/poster/network logo is duplicated between those two parts.
=> Add an API method to get a network logo

gui/slick/interfaces/default/config_general.tmpl, gui/slick/interfaces/default/config_notifications.tmpl, lib/trakt/trakt.py, sickbeard/__init__.py, sickbeard/helpers.py, sickbeard/notifiers/trakt.py, sickbeard/traktChecker.py, sickbeard/webserve.py
NEW OPTION in config/general advanced settings (SSL Verify)  - Disable this for QNAP SSL problems.
REMOVED OPTION in Trakt notification settings (Disable SSL Verify) - Handled by the new option above
Helps? QNAP
=> NEW OPTION in config/general advanced settings (SSL Verify) - QNAP/Etc

sickbeard/webapi.py
Currently, if you use the `sb.searchtvdb` and `sb.searchtvrage` API commands, they both returns the search results for all indexers (TVDb and TVRage).
With this PR, the behavior is as follow:
- `sb.searchindexers` returns the results for all indexers
- `sb.searchtvdb` returns the results for TVDb only
- `sb.searchtvrage` returns the results for TVRage only
=> Fix search indexers api

sickbeard/providers/generic.py
removed zoink.ch as it appears to be hijacked by the ones running eztv ,as it is redirecting to their website
=> Remove zoink.ch

sickbeard/webapi.py
This adds an optional argument to set future episode status.
WebAPI CMD_ShowAddNew was not updating "default_ep_status" when adding new shows to function "addShow" in  "show_queue.py".  So new shows were having "default_status_after" set to None.  Leaving new shows added via webapi not being set to "wanted" or anything useful, requiring a manual episode status change to "wanted".
=> Add Default Ep Status to WebAPI CMD_ShowAddNew

.travis.yml
As per the documentation http://docs.travis-ci.com/user/migrating-from-legacy/
This should make the build start faster on Tavis (event if they are not taking a lot of time right now :wink:).
=> Migrate travis to a container-based infrastructure

gui/slick/interfaces/default/config_subtitles.tmpl, sickbeard/__init__.py, sickbeard/logger.py, sickbeard/subtitles.py, sickbeard/tv.py, sickbeard/webapi.py, sickbeard/webserve.py
SiCKRAGETV/sickrage-issues#1075
Argument 1 is the absolute path to the video file
Argument 2 is the absolute path to the new subtitle downloaded
Argument 3 OpenSubtitles 3 letter language code (Or should it be the full name of the language?)
Argument 4 Series name
Argument 5 Season
Argument 6 Episode
Argument 7 Episode title
Currently:
Gets called once for each subtitle downloaded for each video, so if a video downloads 10 subtitles, it is ran 10 times for that video. (I don't like this, I'd rather pass all of the subtitles at once, but we can decide that maybe after it gets some use)
Only gets called if embeded subtitles are allowed/not disabled (to prevent a race condition if your script deletes the srt after embedding it and SR keeps trying to re-download the subs)
Only gets called for …
=> Add post subtitle download scripts

sickbeard/webapi.py
@MGaetan89
@miigotu
This fixes the error issue when no URI parameters are provided for "status" or "future_status".  Basically reverting to the original code for checking URI provided arguments, which I believe is/was correct based on how the webapi.py was written.  The actual default values are set later in the code if not provided by the URI parameters.  It's the same format used throughout the webapi. 
The default value "None" represents no URI provided argument, for doing the comparison to the string list of possible input.  The system integer default values "STATUS_DEFAULT" and "STATUS_DEFAULT_AFTER" are used later in the function if no argument was supplied.
Thanks.
=> Fix default argument when not provided.

sickbeard/logger.py
This PR will make issues submitted from inside SR always use an existing issue whether it is opened or closed, instead of creating a new issue. It will only create a new issue if one does not exit with the same title.
=> Use issues even if they are closed for issue submitter

gui/slick/interfaces/default/displayShow.tmpl
- The "Show/Hide Episodes" button is properly aligned with the title
- The first season can also be collapsed but is shown by default
Before:
After:
=> Fix for SiCKRAGETV/sickrage-issues#2337

sickbeard/providers/xthor.py
AA. Error: XthorProvider instance has no attribute 'ratio'
AARelease Group: ADDiCTiON
AASize: -1
AAName: Dominion.S02E03.FASTSUB.VOSTFR.720p.HDTV.x264-ADDiCTiON
AAQuality: HDTV
AAEpisode: [<sickbeard.tv.TVEpisode object at 0x1ed1cb0>]
AAExtra Info:
2015-07-27 10:48:20 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Transmission: Exception raised when sending torrent: Xthor @ https://xthor.bz/download.php?torrent=14372
AAAttributeError: XthorProvider instance has no attribute 'ratio'
AA    return self.ratio
AA  File "/opt/sickrage/sickbeard/providers/xthor.py", line 208, in seedRatio
AA    result.ratio = result.provider.seedRatio()
AA  File "/opt/sickrage/sickbeard/clients/generic.py", line 183, in sendTORRENT
AATraceback (most recent call last):
2015-07-27 10:48:20 ERROR    SEARCHQUEUE-DAILY-SEARCH …
=> fix xthor crash (ratio)

sickbeard/nzbSplitter.py, sickbeard/providers/btn.py, sickbeard/providers/generic.py, sickbeard/providers/iptorrents.py, sickbeard/tvcache.py
User's can easily check why files was skipped without need to see DEBUG logs.
=> Show skipped files in log INFO, not DEBUG

.travis.yml
This will only send an email on the first build that fails, and then the first build that is fixed, not every single push anymore.
=> Only email committer if build fails in travis

runscripts/init.fedora
After a recent update, Python 2.6 is no longer supported. Some older OSes don't come packaged with 2.7 and you have to compile it yourself. Overriding the default Python versions on theses OSes also causes issues so is not advisable.
The current init script for Fedora (Redhat, centos, etc) doesn't allow you to set the Python path to use and just uses the system's default. I've added a variable in this init script to allow you to set PYTHON_BIN in your init config file.
=> Add variable in init.fedora to allow changing the Python path

sickbeard/webapi.py
Updating the SQL query to include paused value from tv_shows table, allows for filtering of non-paused shows only.  
Currently paused shows are being included in webapi backlog query.  
Please see me full explanation in my comment dated today in issue #2267.  
https://github.com/SiCKRAGETV/sickrage-issues/issues/2267
=> Paused Shows are Showing in webapi Backlog Query

contributing.md
My develop was stale (pre-mako) and I followed the steps listed, after a few minutes of development I realised that my feature branch (based off develop) still have tmpl files, and no mako files.  This step might be obvious for non-noobs, but I figure it makes sense to be explicit.
=> Adding a new step to make sure that develop is up to date.

sickbeard/webserve.py
Closes SiCKRAGETV/sickrage-issues#2425
=> Remove trailing '/' from torrent path because some clients don't like it

SickBeard.py, autoProcessTV/mediaToSickbeard.py, gui/slick/interfaces/default/config_search.mako, gui/slick/js/configSearch.js, lib/synchronousdeluge/__init__.py, lib/synchronousdeluge/client.py, lib/synchronousdeluge/exceptions.py, lib/synchronousdeluge/protocol.py, lib/synchronousdeluge/rencode.py, lib/synchronousdeluge/transfer.py, sickbeard/__init__.py, sickbeard/clients/__init__.py, sickbeard/clients/deluged_client.py
As requested from originally submitted pull request https://github.com/SiCKRAGETV/SickRage/pull/2274 to submit to develop not master:
Add new client method to support directly connecting to the Deluge Daemon service, without the requirement to go via the WebUI.
Existing WebUI Client method is still retained, so the option for either still exists.
Helpful for fully headless clients, or minimal installs of Deluge, or where access via WebUI is not available.
=> Add new Deluge Daemon Client

sickbeard/subtitles.py
> Unable to run subs_extra_script: execv() arg 2 must contain only strings
> +ADD epObj.show.indexerid arguments
=> FIX: Subtitles Extra Scripts

sickbeard/webserve.py
To prevent errors in saving config
=> Adding missing variables to notifications

runscripts/init.debian
The status command of the init.d script should reflect the actual status based on LSB exit status code.
The function "status_of_proc" garantees that.
Modification tested on raspbian.
=> status command should not always return 0 

gui/slick/interfaces/default/config_search.mako, sickbeard/__init__.py, sickbeard/webserve.py
forcing searches on startup is no good, and defeats the purpose of a timer between searches. We must set the interval in relation to last daily/backlog time set in the database instead.
=> Dont allow forcing daily/backlog search on startup

gui/slick/interfaces/default/home.mako
Since @MGaetan89 added the print view we now get back a duplicate result like `33+1 / 3733+1 / 37` instead of `33+1 / 37` so we need to split the string in half.
=> Fixes progressbar sorting

gui/slick/js/displayShow.js
Fix for SiCKRAGETV/sickrage-issues#2592
This does not collapse back the season if the checkbox is unchecked. It only expand the season if it is collapsed.
=> Display episodes list of collapsed season when select all is checked

gui/slick/interfaces/default/home.mako
Loading the images after the page has finishes gave me a 200ms - 300ms decrease in page loading time.
This still needs to be tested though but honestly can't break anything.
=> Load images after page finishes

gui/slick/interfaces/default/home.mako
The last line of the shows table include a "Add Show" link. If anime are separated from the other shows, the label is still "Add Show", instead of "Add Anime". This simply changes that :)
=> Show "Add Anime" at the bottom of the anime tables

gui/slick/interfaces/default/displayShow.mako
we should remove the FAILED status from API in "Episodes.SetStatus' but this function it's nor working! I can't select the second listbox. it's empty
@MGaetan89  can you confirm please?
=> Remove failed status if feature not enabled

gui/slick/interfaces/default/inc_bottom.mako, sickbeard/webserve.py
This PR adds a new line at the bottom of each page with some useful debug information. Those information are only display if the current branch is not `master`.
Currently, this line includes:
- Memory usage of the process SickRage is running in
- Overall load time of the page
- Load time for Mako
Loading times need to be improved I guess, I'm not sure it's the best way to do it.
I would also like to display the number of DB queries + time to perform them, but I'm not sure how to do that yet.
The idea behind this PR is to have data to know the impact of a specific change. If you have more ideas to include in it, feel free to suggest them.
Do no merge this PR yet, this is really a Work in progress.
=> Display debug data

sickbeard/webapi.py, sickbeard/webserve.py, sickrage/media/GenericMedia.py, sickrage/media/ShowBanner.py, sickrage/media/ShowFanart.py, sickrage/media/ShowNetworkLogo.py, sickrage/media/ShowPoster.py, sickrage/media/__init__.py
Working on https://github.com/SiCKRAGETV/sickrage-issues/issues/2567
This PR creates reusable classes to load a show fan art, banner, poster and network logo.
I still need to implement the part about network logo, so don't merge it yet.
The goal of this PR is also to agree on the structure. It's easier to adapt things now, rather than in two month, when everything is done.
- In my opinion, SR is mature enough to move away from the `sickbeard` folder. So I created a `sickrage` folder where I put all the new files
- I use one file per class. Coming from Java, it's an obvious choice. I don't know what is the recommended way in Python
- Instead of simply doing `import somename`, I use `from somename import somename2`. I don't know how Python handles import internally, but I guess it's better …
=> Move logic to load images (fanart/banner/poster/network logo) into reusable classes

sickbeard/webapi.py
https://github.com/SiCKRAGETV/sickrage-issues/issues/2671
In my opinion, the real issue is that [`ApiCall`](https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webapi.py#L270) does not call its parent constructor.
I tried to fix that, but in some case `args` is empty and the parent constructor call fails. I guess that's why `rh` is undefined sometimes (https://github.com/SiCKRAGETV/SickRage/pull/2414#issuecomment-138077018).
=> Fix SiCKRAGETV/sickrage-issues#2671

gui/slick/views/history.mako, sickbeard/failed_history.py, sickbeard/history.py, sickbeard/properFinder.py, sickbeard/webapi.py, sickbeard/webserve.py, sickrage/show/History.py, sickrage/show/__init__.py
The code to get, clear and trim the history is now the same for the web UI and the API.
From what I saw, the failed history use almost the same code. So it should be easy to change that part too.
=> Move history logic into a reusable class

sickbeard/__init__.py, sickbeard/webapi.py, sickbeard/webserve.py, sickrage/system/Restart.py, sickrage/system/Shutdown.py, sickrage/system/__init__.py
I did not test the restart part, so if someone can confirm that it works, it would be great.
This PR does not change a lot, but the idea is really to have a common code base between the web UI and the API.
=> Move logic to shutdown and restart SickRage into reusable classes

sickbeard/providers/tntvillage.py
This commit fix a no-match when episodes are named with
concatenated original and italian serie's name on TntVillage.
i.e. searching for an episode of "The game of thrones" on
TntVillage returns results named "Il trono di spade - Game
of thrones S0XeXX...".
With this fix if the returned show tilte differs from (and
contains the) searched one, the returned title is replaced
with the desired one before continuing the matching process.
=> tntvillage: Fix torrents searching

sickbeard/subtitles.py, sickbeard/tv.py
This PR restores support for relative paths and includes many little fixes regarding subtitles recognition/download. It has been been tested with all possible variants (relative, absolute and empty paths) for a few days and should be working correctly in all situations.
_What has been done in this PR?_
- Restored support for relative paths
- Subtitles are being correctly recognized in all situations (afaik never really worked for relative paths)
- Subtitles won't be downloaded multiple times (overwritten), if not necessary
- Subtitles in the show directory will be ignored, if the subtitles directory differs from the show directory (this bug affects the current branch with the absolute path)
- Empty SUBTITLES_DIR defaults to /show/season/
- Probably something else that I don't remember now …
=> Restore support for relative, absolute and empty paths

sickbeard/providers/tntvillage.py
This commit fix a no-match when episodes are named with
concatenated original and italian serie's name on TntVillage.
i.e. searching for an episode of "The game of thrones" on
TntVillage returns results named "Il trono di spade - Game
of thrones S0XeXX...".
With this fix if the returned show tilte differs from (and
contains the) searched one, the returned title is replaced
with the desired one before continuing the matching process.
=> Fix tntvillage match

sickbeard/webserve.py
Trending shows was displaying FixMe as the page title. Changed to 'Trending Shows'
=> Fixes Page Title for Trending Shows

sickbeard/webserve.py, sickrage/media/GenericMedia.py, sickrage/media/ShowNetworkLogo.py
What I changed is:
- Set the `Content-Type` header before returning an image. Now we can see the image in a new tab instead of its content
- Use `os.path.join` to build every images path
I don't have a Windows machine with me now, so if someone can give me a feedback on this, that would be great.
=> Trying to fix broken images

sickbeard/clients/deluged_client.py
Won't raise ERROR when ratio is blank, etc.
Resolves SiCKRAGETV/sickrage-issues#2737
=> Fix for blank options Deluge

sickrage/media/GenericMedia.py
As suggested here [here](http://stackoverflow.com/a/3198124/1914223), the `b` mode might be necessary are images are not text files.
=> Images are binary files

sickrage/media/GenericMedia.py
I noticed this issue after using the Windows installer which uses a custom DATA_DIR.
Issue: https://github.com/SiCKRAGETV/sickrage-issues/issues/2708
=> Fixed loading network logos when using custom data directory

sickrage/show/History.py
An other potential performance improvement for people with a lot of shows: only select fields that we use, instead of `SELECT *`.
I'll try to do that everywhere during my refactoring.
=> Only select required field in history

gui/slick/views/comingEpisodes.mako, gui/slick/views/status.mako, sickbeard/classes.py, sickbeard/databases/mainDB.py, sickbeard/logger.py, sickbeard/metadata/kodi_12plus.py, sickbeard/metadata/mede8er.py, sickbeard/metadata/mediabrowser.py, sickbeard/metadata/wdtv.py, sickbeard/subtitles.py, sickbeard/tv.py, sickbeard/webapi.py, sickbeard/webserve.py, sickrage/helper/common.py, sickrage/helper/quality.py, sickrage/show/ComingEpisodes.py, sickrage/show/__init__.py
I am still working on this PR. But as I found a couple of differences between the API and the web UI, I decided to open this PR to track the changes and see which version is the best and validate the choices.
- Qualities definition:
- API ([source](https://github.com/SiCKRAGETV/SickRage/blob/v4.0.55/sickbeard/webapi.py#L736)): `qualList = Quality.DOWNLOADED + Quality.SNATCHED + [ARCHIVED, IGNORED]`
- Web UI ([source](https://github.com/SiCKRAGETV/SickRage/blob/v4.0.55/sickbeard/webserve.py#L499)): `qualList = Quality.DOWNLOADED + Quality.SNATCHED + [ARCHIVED, IGNORED]`
- Solution: @miigotu confirmed that `Quality.ARCHIVED` should be used (https://github.com/SiCKRAGETV/sickrage-issues/issues/2567#issuecomment-138367874)
- Sorting methods:
- API …
=> Move "Coming episodes" logic into a dedicated class

gui/slick/views/comingEpisodes.mako, gui/slick/views/home.mako, gui/slick/views/inc_defs.mako, gui/slick/views/manage.mako
- When the initial and preferred qualities are the same, show the
quality instead of 'Custom'.
- Where it makes sense, show a title (mouse hover) for the pill showing
the specific initial and preferred qualities.
=> Enhance quality pills

sickbeard/providers/alpharatio.py
Currently alpharatio does not respond on the https:// any more and i'm getting the following error's
```
2015-09-19 22:03:59 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [AlphaRatio] :: Unable to connect to AlphaRatio provider.
AA
AATooManyRedirects: Exceeded 30 redirects.
AA    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 114, in resolve_redirects
AA    history = [resp for resp in gen] if allow_redirects else []
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 602, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/usr/local/sickrage/var/SickRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('POST', url, data=data, json=json, …
```
=> Alpharatio does not respond to the SSL version

sickbeard/providers/nextgen.py
The provider NextGen has moved to a new domain. This change uses the new domain in favor of the old.
=> Provider domain change

.gitignore
autoProcessTV.cfg and SR data dirs cannot be ignored absolutely in the root, since the user might have them set to be in a subdir or the source such as /data/ or /settings/ or /config/ or the like.
=> Remove leading slash from folders in gitignore

sickbeard/common.py
Use raw strings for regex search strings
Ignore too many branches pylint warning (last of the pylint warnings in common.py)
=> Change quality regex from hdtv to hd.?tv for source matching

sickbeard/subtitles.py, sickbeard/tv.py
This time really for real.
Please note:
Some embedded subtitles are not being correctly recognized by subliminal (actually enzyme: https://github.com/Diaoul/enzyme) and will be tagged as "und" (undefined), in that case the correct subtitle will be downloaded. There is nothing we can do to solve this, I guess it depends on how the subtitle has been embedded.
=> Really fixes SiCKRAGETV/sickrage-issues#2774

gui/slick/views/comingEpisodes.mako
Until we add column widget in comingEpisodes ( https://github.com/SiCKRAGETV/sickrage-issues/issues/2626 ) we should warn user about airdate.
In the future we can add both columns 'Airdate local' and 'Airdate network'
=> Show timezone setting in the 'Airdate' column in comingEpisodes

sickbeard/dailysearcher.py
When local enabled the time that show ends is using network GMT not user local timezone
DAILYSEARCHER :: Show **** ends at 2015-09-24 21:00:00-04:00 and now it is 2015-09-23 10:00:49.733573-03:00. Runtime is 60 and airs Thursday 8:00 PM
with this fix:
DAILYSEARCHER :: Show ***** ends at 2015-09-24 22:00:00-03:00 and now it is 2015-09-23 09:53:19.452325-03:00. Runtime is 60 and airs Thursday 8:00 PM
So in this show. the conversion from UNAIRED > WANTED was delayed 2 hours. User could not notice this error because dailysearch frequency could be high and user don't mind start searching for shows MINUTES after airdate+runtime
=> Fix dailysearch not respecting timezone setting

sickbeard/webapi.py
With this PR, the JSON response of every API commands will no longer be formatted. This save some data when using the API (and maybe improve speed, as there is no formatting to do).
For my list of shows, I have to downloaded 35ko before this PR, and 19ko after.
If someone is calling an API command directly from the browser and want a formatted response, there are a lot of good browser extensions that do that (and way better than what we currently do).
The new API builder will format the result on the client side, so it won't be affected.
=> Don't format JSON before sending the response

sickbeard/webapi.py
This PR is here to help https://github.com/SiCKRAGETV/SickRage/pull/2581 so it does not mix too many things.
The goal is to make image API commands (currently, `show.getbanner`, `show.getfanart`, `show.getnetworklogo` and `show.getposter`)  return the correct `Content-Type`, instead of `text/html`.
This way, the new API builder can automatically detect image response and display them, so we don't have to manage [a list of commands](https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/js/apibuilder.js#L12) that return an image.
=> Image API commands now return the correct Content-Type

sickbeard/webserve.py
This will fix the first loading of history page when you have a history limit <> 100
@duramato
=> Fix history limit and save on change limit

gui/slick/views/config_general.mako
Make Initial page option more accurately reflect the pages as listed in
the header:
- Rename "Home" to "Shows"
- Move IRC to be after News instead of at the end.
=> Fix "Initial page" option

sickbeard/webserve.py
This add a new template variable `srRoot`.
It is exactly the same as `sbRoot`, but adapted for SickRage.
By having both, we can freely switch the mako files to `srRoot` if we change one, and it shouldn't break anything as both values are available, for now.
Suggested by @OmgImAlexis in https://github.com/SiCKRAGETV/SickRage/pull/2587
=> Add "srRoot" template variable

sickbeard/webserve.py
Add id= to header tags, so that links can be given in the form of `http://localhost:8081/news/#2015-09-26`
=> Add id= to header tags in markdown2

gui/slick/views/config_subtitles.mako
@MGaetan89 we need to get the v2 api points in soon as I can remove this fix. Using the meta tags only works for certain things and stuff like this just doesn't work with it as it's a full JSON object that needs to be parsed to `tokenInput`.
=> Temp fix for config_subtitles

gui/slick/views/config_general.mako, sickbeard/webserve.py
@OmgImAlexis switched from `sbRoot` to `srRoot` in all the mako and JS files in https://github.com/SiCKRAGETV/SickRage/pull/2615.
So this removed `sbRoot`.
=> sbRoot is no longer used anywhere

sickbeard/databases/mainDB.py, sickbeard/subtitles.py
@miigotu babelfish.language_converters['opensubtitles'].codes had some non-opensubtitles codes (i.e 'gre' instead of 'ell'). Please have a look
=> Fix for wrong subtitle language codes

sickbeard/providers/torrentproject.py
The current way works fine,even if the hardcoded ones dont match the torrent ones (as it will fallback to DHT) ,but this it gets the actual ones
Also added torrent name to magnet file so that it gets added to the client with a name and not the hash (its just cosmetic as it gets the name after it handshakes to other peers)
=> Dynamically get torrent trackers instead of hard coded ones

sickbeard/providers/xthor.py
urlsearch was malformed, turning quesrystring into :
?search="<search>&searchin=title&incldead=0"
instead of search="<search>"&searchin=title&incldead=0
=> Fix urlsearch

gui/slick/views/manage_massEdit.mako
All settings values from webserve can have 3 states: None, 0(False) or 1(True)
webserve do all checks to see if there's any diff value in the selected shows. If all values are the same then setting value is None
when we bool(value) and value is None it become false. Which is wrong.
This PR fixes it
@OmgImAlexis do you have another solution other than compare == 1 / == 0  / == None ?
=> Fix SiCKRAGETV/sickrage-issues/issues/2769

gui/slick/views/layouts/main.mako, sickbeard/webserve.py
cf3aabb975a6a41c195b4fb0bcb9a07e25b96c30 removed the "Shows" submenu. I think it adds value. For example, quick access to post processing, which I do fairly frequently. My shows page takes a couple seconds to load so it's annoying to have to navigate there, wait a few seconds and then click the button.
I don't think there is a down side to adding the submenu back. I've added the "disabled" class to the menu so if you click "Shows" it will take you to the show list just like before.
This PR also highlights the "Shows" link when on the Add Shows and Post Processing pages.
=> Convert "Shows" back into a submenu

gui/slick/views/displayShow.mako, gui/slick/views/home.mako
- Add 's' to Column on Shows (home) page.
- Add dropdown arrow to button on displayShow page.
=> Make the "Select Columns" buttons consistent

.gitignore, SickBeard.py, sickbeard/__init__.py
After some discussions in SiCKRAGETV/sickrage-issues#2788 this proposes to change the default DATA_DIR from PROG_DIR to PROG_DIR/data, and adds it to gitignore.
Offcourse, the cmdline switch to specify DATA_DIR is still available, but this way we at least know where user-specific stuff ends up, and we don't have to keep on excluding all kinds of locations. It's all in PROG_DIR/data by default.
Note: Only on new installs!
Also: Previously made backups may not be able to restore, due to changed file locations
=> Change default DATA_DIR to PROG_DIR/data

gui/slick/views/manage_episodeStatuses.mako
This fixes an issue on Chrome when you expand a show and then collapse
it again. Adds a dummy row with 3 columns. Chrome seems to have an
issue with colspan and then hiding rows to where there aren't enough
columns to span.
=> Fix Chrome rendering issue on episode status page

sickbeard/versionChecker.py
This fixes SiCKRAGETV/sickrage-issues#3095. In cases where the "default"
time that I was using of 1970-01-01 could be interpreted as negative
with a positive offset timezone, an exception was thrown by mktime().
Also move to datetime per recommendation from @miigotu.
=> Wrap time calls with try/except to fix #3095

gui/slick/views/editShow.mako
@miigotu @OmgImAlexis 
If user have only 'anyQualities' and then add 'bestQualities' , the 'archive on first match' will only appear in the next page load after user 'submit' changes, isn't?
=> Move 'Archive on first match' closer to 'Quality' in editShow

gui/slick/js/script.js
`initHeader();` hasn't been used since the old SickBeard and I'm sure of that since it uses `$("#header");` and we use Bootstap's `nav` setup.
Also moved `initTabs();` out of a function and into the `$(document).ready(function () {});` since it only ever gets run once and only inside of that file.
=> Removed unused code

sickbeard/providers/btdigg.py
=> Fix BTdigg NameError: global name 'results' is not defined

sickbeard/providers/kat.py, sickbeard/providers/thepiratebay.py, tests/all_tests.py, tests/common_tests.py, tests/config_tests.py, tests/encoding_tests.py, tests/feedparser_tests.py, tests/issue_submitter_tests.py, tests/name_parser_tests.py, tests/pp_tests.py, tests/scene_helpers_tests.py, tests/search_tests.py, tests/snatch_tests.py, tests/ssl_sni_tests.py, tests/test_lib.py, tests/torrent_tests.py, tests/tv_tests.py, tests/xem_tests.py
Moved imports below path insertion in unit tests so they can be run standalone.
Use urlencode for kat and tpb so they can be used with proxy until the new proxy system is in place.
Add the beginnings of a unit test to check uniformity among providers and search failures.
=> Temp patch tpb kat

sickbeard/providers/xthor.py
Error log was :
AA
AANameError: global name 'download_url' is not defined
AA    if not all([title, download_url]):
AA  File "/Applications/SickRage/sickbeard/providers/xthor.py", line 121, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/Applications/SickRage/sickbeard/providers/generic.py", line 352, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/Applications/SickRage/sickbeard/search.py", line 488, in searchProviders
2015-10-09 19:59:34 DEBUG    SEARCHQUEUE-MANUAL-281620 :: [Xthor] :: Traceback (most recent call last):
AANameError: global name 'download_url' is not defined
AA    if not all([title, download_url]):
AA  File …
=> fix typo : downloadURL should be download_url

gui/slick/views/inc_defs.mako
In cases where initial and preferred qualities were the same, the title
of the span incorrectly showed 'None' as the preferred quality.
=> Fix an issue with quality pill title

sickbeard/scene_exceptions.py, sickbeard/show_name_helpers.py
This fixes an issue I had with the second season of the anime show Utawarerumono. It was a two part issue.
Firstly on XEM the show does not have an english name listed, so the allNames call to xem would not get Utawarerumono season 2 name in the result. I spoke with the XEM team about it and their opinion was that it was correct for the show to not have an english name in this instance. So I removed the language=us portion of the url so all shows will be returned.
So now it found the exceptions, but now the next problem was that the exceptions would not get added to the episode search. Upon stepping through what was happening I saw that in makeSceneSearchString() it would just skip adding a name for an episode if the whitelist is empty for it. In my case SickRage won't find any groups or …
=> Fixed a corner case issue where scene exceptions can't be found for some animes

sickbeard/providers/tokyotoshokan.py
@miigotu we can't add minseed and minleecher in init because it will show in the provider settings and we don't parse. So no point asking user a setting that will override with seeders =1 and leechers =0
I comment because when we add 'mode' and parse those, we only need to uncomment
=> Fix tokyotoshokan

tests/search_tests.py
Fix when this happens
test_manual_*_of_Thrones_121361_KickAssTorrents (__main__.SearchTest) ... Show name not in title: *.Of.Thrones.S05E10.FRENCH.REPACK.LD.WEB-DL.XviD.SVR.avi. URL: magnet:?xt=urn:btih:7D4C9A9AEA6EE5031F6A797421B080650037543F&dn=*+of+thrones+s05e10+french+repack+ld+web+dl+xvid+svr+avi&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
=> Lower words while comparing with title

sickbeard/providers/bitcannon.py
Fix exception when title has non unicode in bitcannon.
=> Handle unicode titles better in bitcannon

gui/slick/views/config_providers.mako
some providers don't support backlogSearch (self.supportsBacklog)
@miigotu
=> Hide enable_backlog for dailysearch providers only.

sickbeard/subtitles.py
While saving subtitles there was not specified encoding. As a result saved subtitles with specials characters (e.g. polish signs: ąężźćńół) was not correctly encoded.
=> Saving downloaded subtitles with utf-8 encoding

gui/slick/views/layouts/main.mako, sickbeard/webapi.py, sickrage/show/Show.py
With this PR, the same shows stats are return in `webserve` and `webapi`.
It removes the SQL from the mako file.
And it only uses one SQL query to compute the stats, instead of 3 in `webapi` or sub-queries in `webapi`.
https://github.com/SiCKRAGETV/sickrage-issues/issues/2567
=> Use common code to compute the shows statistics

gui/slick/views/editShow.mako, gui/slick/views/inc_qualityChooser.mako, sickbeard/webserve.py
Changed the "Edit Show" page layout to use tabs similar to settings pages.
The page now has a 3-tab control, "Main" "Format" and "Advanced". Splitting into 3 tabs reduces page height and makes easier to read. No settings were added/removed, just re-arranged with exception of the "Season folders" (formerly "Flatten files"). Setting is now inverted (i.e. tick to group, untick to flatten) - makes more sense to end user I think.
Open to suggestions.
=> Make Edit Show page style consistent with other UI.

gui/slick/views/schedule.mako
Should fix SiCKRAGETV/sickrage-issues/issues/3273
Would use the enddate of previous episodes in the same segment if that segment was already defined. Caused issue when one episode already aired, unaired ones would also show up as overdue.
=> Should fix SiCKRAGETV/sickrage-issues/issues/3273

sickbeard/search.py
@miigotu 
This maybe the one of the causes of the of "Unable to send Torrent: Return code undefined" as we succeeded sending torrent to client BUT SR didn't had knowledge of that and next time will try to send again, creating the empty/None return code
```
2015-10-20 23:31:38 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading *******.S01E01.1080p.HDTV.X264-DIMENSION from Rarbg
2015-10-20 23:31:38 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Calling Transmission Client
2015-10-20 23:31:43 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Transmission: Response to POST request is {"arguments":{},"result":"success"}
2015-10-20 23:32:14 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Traceback (most recent call last):
File "/home/osmc/SickRage/sickbeard/search_queue.py", line 145, in run
self.success = …
```
=> Fix multiple snatches when 'snatch notification' fails

sickbeard/providers/scc.py
Updated the searching to use the new 'all' section of SCC. Changed:
- Searching in all categories now requires only one request instead of a request to all the URLs.
- Foreign categories can be handled just as any other, as the new section doesn't include a second link to the language.
- Season pack search also includes their non-scene sections as they release WEB-DL packs there instead of the archive.
=> SCC search improvements

sickbeard/common.py
Add 480p as a hackaround source for releases groups such as mSD on a test basis
=> Reorganize and normalize name quality detection a bit

gui/slick/views/config_subtitles.mako, sickbeard/__init__.py, sickbeard/subtitles.py, sickbeard/webserve.py
Add gui option to select whether to download hearing impaired subtitles or not.
Best description I found anywhwere: http://www.hometheaterforum.com/topic/196910-subtitle-differences-english-and-english-for-the-hearing-impaired/#entry2233634
`Subtitles for the deaf and hearing impaired also include descriptions of other sounds than dialogue. For instance: [heavy breathing], or [door slams]. BTW, when it would be unclear to see who's speaking the dialogue, subs for the deaf and hearing impaired also mention who's saying stuff, like: [Vito] "I'll make you an offer....". `
Also made subtitle providers password field masked.
=> Add option to subtitle settings for selecting hearing impaired subtitles

sickrage/show/ComingEpisodes.py
Also select UNAIRED episodes whose airdates are in the past but have not yet changed status because of timezone differences
=> Fix SiCKRAGETV/sickrage-issues#3416

lib/libtrakt/trakt.py
We need user to report "Trakt error (404) the resource does not exist" because Trakt may change API.
=> Fix Trakt message log levels

gui/slick/views/displayShow.mako
This fixes shows display an air date of `Never` while still protecting against `dateutil` issues on Windows as referenced in sickragetv/sickrage-issues#3450 and sickragetv/sickrage-issues#3007
=> Hotfix-3450: Fix airdate of 'Never' while avoiding Windows dateutil issues

sickbeard/logger.py
@miigotu
in python works:
```
message = "'_volume1___plugins_AppCentral_sickbeard_tvrage_SickBeard_TVRage_gui_slick_views_schedule_mako'"
if re.search(r"_mako\'$",message):
print "Found"
```
I keept the single quotes from the message error
=> Avoid open mako cache issues and warn user to delete cache folder

gui/slick/views/manage_massEdit.mako
As requested by @fernandog the mass edit page is now consistent with the edit show page and also a bit more intuitive.
=> Make massEdit UI consistent with other pages.

gui/slick/js/new/core.js, gui/slick/views/layouts/main.mako
Here's a proposal to fix https://github.com/SiCKRAGETV/sickrage-issues/issues/1097.
Basically now i am expanding the touchable area for clicking open a dropdown to full button width, so it works nicely on small tablets and phones. Mouse will still have the dropdown appear on hover. And if mouse clicks on the "main" menu item while the dropdown is open, instead of dismissing the dropdown like on touchscreen, it follows the link, as it used to.
Works well on Windows Phone 8.1 and Windows 10 (tablet), but i don't have any Android or iOS devices to test with, so it would be good to get some help there.
=> fix propsal for 1097 - dropdowns not working on touchscreen

sickbeard/__init__.py, sickbeard/dailysearcher.py, sickbeard/db.py, sickbeard/failedProcessor.py, sickbeard/helpers.py, sickbeard/logger.py, sickbeard/metadata/generic.py, sickbeard/metadata/tivo.py, sickbeard/name_parser/parser.py, sickbeard/nzbSplitter.py, sickbeard/postProcessor.py, sickbeard/processTV.py, sickbeard/providers/__init__.py, sickbeard/providers/generic.py, sickbeard/providers/kat.py, sickbeard/providers/thepiratebay.py, sickbeard/rssfeeds.py, sickbeard/search.py, sickbeard/searchBacklog.py, sickbeard/search_queue.py, sickbeard/show_queue.py, sickbeard/tv.py, sickbeard/tvcache.py, sickbeard/webapi.py
No need to import with_statement from future, we don't support Python 2.6
Move providers imports to sickbeard/providers/__init__.py so that __all__ works properly.
=> Intialize providers correctly

gui/slick/views/config_search.mako, sickbeard/__init__.py, sickbeard/nzbget.py, sickbeard/sab.py, sickbeard/webserve.py
This patch allows the user to set backlog vs. daily fetch categories in nzbget and sabnzb. I have fully tested that the config changes work, and that episodes get added to nzbget correctly. I have not tested sabnzb, which consists of 4 lines of code that were almost copy and pasted from the nzbget change.
Upgrade:
the backlog categories are set by default to the value of the daily fetch category
Purpose:
For users who fetch on one machine and then transfer the files to the SickRage host, this will allow them to prioritize daily fetch episodes over backlog episodes by putting them in a completely different directory or doing other post-processing via NZBGet's postprocesor (which doesn't have access to the priorities we set when adding an nzb file, but does have access to the category)
=> add category options to nzbget and sabnzb for backlog episodes

gui/slick/views/config_general.mako, sickbeard/__init__.py, sickbeard/webserve.py
This pull request adds support for Google Calendar Icons to be displayed, and a setting to enable/disable them (General/Advanced, right below the Protected Calendar option).
It is based on the idea (also submitted by me) here: http://feathub.com/SiCKRAGETV/SickRage/+256 which includes screen shots of the feature in action. Please note this DOES include the setting to enable/disable the feature, which is off by default. This pull request uses the SickRage icon I created, though it can be altered to use any icon deemed appropriate.
=> Added support for Calendar Icons in Google Calendar (Develop branch)

sickbeard/sab.py
Fixes an undefined error with sabnzbd:
NameError: global name 'datetime' is not defined
=> Import datetime to fix undefined errors with sabnzbd

gui/slick/views/config_providers.mako, sickbeard/__init__.py
Make the append identifier blank by default ,the only spanish language shows disabled by default and add tooltip exaples to the append identifier..
=> Make "newpct" configs more n00b friendly

sickbeard/helpers.py, sickbeard/name_parser/parser.py, sickbeard/show_name_helpers.py
Shouldnt include normal regexes and confuse the score when we know the show is anime.
Dont ignore results/files that include the word "sample" if it is preceeded by shomin and a seperator.
=> No normal regex anime

gui/slick/views/layouts/main.mako
Pretty much what it says. The text needs to be -inline so that the following caret doesn't get pushed onto the next line.
=> make sure the caret is in the right place on -xs (mobile) layout

SickBeard.py
- Streamline `datetime` call used to time-stamp backup files
- PEP 0008 - Add and remove blank lines for consistency
- PEP 0263 - Add encoding declaration
- Add comments for pylint codes
=> Update sickbeard.py for PEPs 8, 263 and streamline datetime call

sickbeard/clients/__init__.py
- b0ba95e PEP 8: Fix indentation and remove excess blank lines	
- 9f88c26 PEP 263: Add encoding declaration	
- 93990f0 Add a todo for handling duplicate http error codes in dict
=> Update clients/__init__.py for PEPs 8 and 263

sickbeard/metadata/__init__.py
- 91009f7 PEP 0008: Move module level imports to top of file	
- ef5a113 PEP 0008: Add and remove blank lines for consistency	
- 275b55f PEP 0263: Add encoding declaration
=> Update metadata/__init__.py for PEPs 8 and 263

.jshintrc, gui/slick/js/addExistingShow.js, gui/slick/js/ajaxEpSearch.js, gui/slick/js/ajaxEpSubtitles.js, gui/slick/js/configProviders.js, gui/slick/views/layouts/main.mako, sickbeard/webserve.py
All js vars should be `camelCase`, there should be a space before and after all `+`, `-` and `=`.
There shouldn't be any vars in function declarations that aren't used for example [here](https://github.com/OmgImAlexis/SickRage/blob/8c9515e66a26f46c2ddf4aa6df9547b5017e70ca/gui/slick/js/addExistingShow.js#L29) the `i` and `w` aren't used at all.
When listing variables in functions there should be a space after a comma. `function(varOne, varTwo){};`
=> General cleanup

sickbeard/common.py
@miigotu This is a fairly significant change, so should probably get some extra TLC before merging as it will eventually deprecate the old way of doing status strings. Would appreciate some further testing and input before merging this.  I also foresee doing something similar with Quality. 
As it currently exists, though, its should mimic the current `StatusStrings`.  Keys that can't convert to int  raise `ValueError` to match current functionality, but I would like to change that to `KeyError`.   Testing `key in dict` which should now work correctly, except for a key of `None` which raises a `TypeError` (it should check for None as a possible key).
=> Convert StatusStrings to a dict subclass

sickbeard/webapi.py
I update both API commands to add a show to use named parameters.
I didn't have time to test it.. But the hardcoded value in add existing show was replaced with SickRage default. I also added the support of subtitles that was missing.
https://github.com/SiCKRAGETV/sickrage-issues/issues/2914
=> Use names parameters when adding a show from the API

lib/rtorrent/lib/bencode.py
Adding torrents with file sizes greater than `sys.maxint` to rtorrent fails with "return code undefined" when using SickRage with Python 2.7 (on 32-bit systems especially) because the bencode module didn't encode the long data type. The torrent would get added to rtorrent, but SickRage wouldn't get the correct hash from bencode making it seem that adding the torrent failed. This fix encodes the long type the same as int.
Possibly also fixes SiCKRAGETV/sickrage-issues#1105
=> Encode long type as int

gui/slick/views/displayShow.mako, gui/slick/views/home.mako
@OmgImAlexis I figured out how to lint mako fairly ok, I just lint the py files in cache/mako =P
=> Remove unused imports in mako

sickbeard/processTV.py, sickbeard/webserve.py
This makes post processing work again. I am sure there are other ascii decoding fixes needed still in other places, especially notifiers.
Need to make everything work without the reload(sys) and setdefault encoding before moving on to removing ek/ss calls.
=> Fix post processing non-ascii

sickbeard/webserve.py
Multiple plex servers can be provided in the web UI and the test also uses them. But due to the bug only one server would get saved.
=> Save multiple plex servers

sickrage/notifiers/pushbullet.py
The call to self.session.request() cause the following error: 
DEBUG::WEB::Pushbullet authorization failed with exception: 'Traceback (most recent call last):
File "/home/odroid/SiCKRAGE/sickrage/notifiers/pushbullet.py", line 93, in _sendPushbullet
response = self.session.request(method, url, data=data, headers=headers)
AttributeError: \'NoneType\' object has no attribute \'request\'
Changing that to use the srCore.srWebsession.
=> Fix for error in _sendPushbullet() due to missing requests lib

sickrage/core/webserver/views.py
Fixes the following error (when clicking 'Re-scan files')
```
Error
'unicode' object has no attribute 'indexerid'
Traceback
Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1485, in _execute result = self.prepare() 
File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2894, in wrapper return method(self, *args, **kwargs) 
File "/opt/sickrage/sickrage/core/webserver/views.py", line 210, in prepare self.finish(self.route(method, **self.request.arguments)) 
File "/opt/sickrage/sickrage/core/webserver/views.py", line 193, in route recursive_unicode(kwargs.items())]) 
File "/opt/sickrage/sickrage/core/webserver/views.py", line 1568, in refreshShow return self.redirect("/home/displayShow?show=" + str(show.indexerid)) …
```
=> Use showObj when referencing indexerid
